### ISSUE TITLE
Decoding Kafka connect member assignments fails

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#100]
Apache Kafka Connect workers uses consumer groups to coordinate and rebalance. They also utilize member assignments that contain additional information. While decoding these member assignments via franz-go's `kassignment.ReadFrom()` usually works pretty good, it consistently fails in the case of Kafka connect consumer groups.

Here's an example of a member assignment that fails to decode:
Encoded as hex string:
```
00010000003b71756f6b6b615f636f6e6e6563745f636c75737465722d37393835363233362d616637342d343932662d393863662d623736336666643863303761001b687474703a2f2f3137322e32322e3133342e3134303a383038332f00000000000001c600000007000d6461746167656e2d757365727300000002ffffffff00000000000d6861636b7765656b2d64656d6f00000002ffffffff0000000000106461746167656e2d70726f647563747300000003ffffffff000000000000000100116461746167656e2d696e76656e746f727900000003ffffffff00000000000000010016747769747465722d62756e646573746167737761686c00000002ffffffff0000000000116461746167656e2d70616765766965777300000003ffffffff000000000000000100216861636b7765656b2d637573746f6d65722d6f726465722d6176726f2d73696e6b00000002ffffffff000000000000000000000000
```

I think this is the original Java code that shows to the member assignment for connect workers is supposed to be decoded: https://github.com/apache/kafka/blob/f5d5f654db359af077088685e29fbe5ea69616cf/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/ConnectProtocol.java#L213-L236

**Edit:** I just noticed the method is called `NewGroupMemberAssignment()` and therefore connect member assignments are not supposed to be decoded successfully I guess. Let's consider this issue as a feature request then where `ConnectMemberAssignments` can be decoded as well then.

**Comment by twmb** [comment]
Closed with https://github.com/twmb/franz-go/commit/3368fd5afbbfda0f7906d216df95589f40e46466.

That hex decodes as:
```
(kmsg.ConnectMemberAssignment) {
 Version: (int16) 1,
 Error: (int16) 0,
 Leader: (string) (len=59) "quokka_connect_cluster-79856236-af74-492f-98cf-b763ffd8c07a",
 LeaderURL: (string) (len=27) "http://172.22.134.140:8083/",
 ConfigOffset: (int64) 454,
 Assignment: ([]kmsg.ConnectMemberAssignmentAssignment) <nil>,
 Revoked: ([]kmsg.ConnectMemberAssignmentRevoked) <nil>,
 ScheduledDelay: (int32) 0
}
```
