### ISSUE TITLE
Move this to a discussion?

### ISSUE THREAD

**Issue by unicomp21** [twmb/franz-go#101]
https://github.com/vectorizedio/redpanda/blob/0389682ba73138cc2414a0ac0c1f88e434b2b2f3/src/go/rpk/pkg/cli/cmd/topic/produce.go#L87

I need an example of how to use ManualPartitioner, but don't fully understand what's going on here?

The reason I'm asking, could ManualPartitioner be use to create a return path for messages, back to the producer node?  My thinking is all nodes can subscribe via consumer group to a topic of manual partitions.  Upon receiving manual partition assignments, a node can produce.send() to a murmur2 partitioned topic, where the payload includes a manual partition id as the return path for results?  Will this strategy work/scale?

**Comment by twmb** [comment]
The manual partitioner is for producing only, not consuming. I'm not quite following the rest of the proposal about consuming/producing and a manual partition path.

**Comment by unicomp21** [comment]
My thinking, a tcp socket is a full duplex connection, one side for sending, the other side for receiving.  Being somewhat of a kafka newbie, I'm trying to get the same w/ kafka, and have it still work as the number of nodes in a consumer group grow/shrink based on overall load balancing/autoscaling.  The upstream part is simple enough, a partition key goes into murmur2, and voila we have a partition index for producing into.  But in order to get results back to the producer, I need to tag this message w/ a  different manual/topic/partition for the return path, right?

Reiterating.  The return path, to the same node which produced the upstream request, is what I'm struggling with a bit.  If the producing node was subscribed to a manually partitioned topic, such that it receives at least 1 partition, when subscribing  as part of a consumer group.  Then this manual partition can be passed along in the original request as the return path, right?  Am I making sense?

**Comment by unicomp21** [comment]
I'm guessing during a rebalance, all of the above breaks, so I would need to have retry logic built-in, which would catch the failures, in the above scheme, during a rebalance?  When both the upstream and downstream consumer groups are getting rebalanced?

**Comment by twmb** [comment]
When you say,
> But in order to get results back to the producer, I need to tag this message w/ a different manual/topic/partition for the return path, right?
do you mean "in order to get results back to the consumer"?

Is your producer also a consumer?

I think I'd need to see a sketch of what you're trying to accomplish here.

**Comment by unicomp21** [comment]
yes, producer is also a consumer.  i'll try to prototype it can circle back.

**Comment by twmb** [comment]
I'm going to close this for now but if there's more actionable later please let me know!
