### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by unicomp21** [twmb/franz-go#102]
go run main.go -commit-style autocommit -topic dog -logger true -brokers redpanda-1:9092

I'm likely doing something wrong here, but can't figure out what.  The example is still trying to hit localhost:9092 even though I passed an arg for brokers.

https://github.com/twmb/franz-go/tree/master/examples/group_consuming

**Comment by twmb** [comment]
`-logger` does not take an argument, and the Go `flag` library stops parsing flags at the first non-flag argument. So, using `true` there is stopping parsing of the --brokers flag.

I did notice I needed to `go mod tidy` that directory but I think I'll leave that cleanup for a future push. Let me know if this works for you, thanks!
