### ISSUE TITLE
Always ErrDataLoss at startup

### ISSUE THREAD

**Issue by yuzhichang** [twmb/franz-go#107]
I'm trying to use franz-go in [the clickhouse_sinker project](https://github.com/housepower/clickhouse_sinker/blob/franz/input/kafka_franz.go).
Auto commit is disabled. After writing a batch of records to database, I commit the last record of this batch. 
Writing records to database look OK. However I always get an ErrDataLoss at startup like following:

`topic gaoju_test partition 0 lost
 records; the client consumed to offset 2028917583 but was reset to offset 2023643056"`

From kafka-ui, I can confirm that `2028917583` is the consumer offset before I start the clickhouse_sinker.
My question is, where is `2023643056` from?

FYI. My Kafka cluster consist of 3 brokers, version 2.7(docker image confluentinc/cp-kafka:6.1.1). clickhouse_sinker with sarama or kafka-go client work well.

Another question(not related to this issue), franz-go `groupConsumer.loopCommit()` looks doesn't do last commit before partitions being revoked?

**Comment by twmb** [comment]
If you can try setting up kcl, https://github.com/twmb/kcl
I'd like to know the output of `kcl misc list-offsets gaoju_test`. What this reads like is the client is committed past the end offset, so it is resetting to either the beginning or end (depending on your configuration).

Other question: if you're relying on autocommitting, the default `onRevoke` is called; `loopCommit` is a periodic timer for autocommits, and onRevoke also by default causes a commit.

**Comment by yuzhichang** [comment]
```
zhichyu@leno:~$ kcl misc list-offsets gaoju_test && kcl misc offset-for-leader-epoch
BROKER  TOPIC       PARTITION  START      END         ERROR
3       gaoju_test  0          274630495  2783630402  
1       gaoju_test  1          0          1535370077  
BROKER  TOPIC                    PARTITION  LEADER EPOCH  END OFFSET  ERROR
1       gaoju_test               1          0             91612350    
1       sensor_dt_result_online  0          0             535315996   
1       test_uuid_enum           0          0             14          
2       gaoju_20211029           0          0             618875750   
2       mytopic                  0          0             583432      
2       sensor_dt_result_online  1          0             533801327   
2       test                     0          0             2262        
3       gaoju_test               0          0             2023643056  

```

`2023643056` comes from `offset-for-leader-epoch`, which is much less than the number of `list-offsets`.

**Comment by twmb** [comment]
What does `kcl group describe -v <your group>` say?

**Comment by yuzhichang** [comment]
When  clickhouse_sinker stop,
```
zhichyu@leno:~$ kcl group describe -v prom_metric
GROUP        prom_metric
COORDINATOR  3
STATE        Empty
BALANCER     
MEMBERS      0

```
![Screenshot_2020-12-16_10-22-00](https://user-images.githubusercontent.com/153784/142094779-ffeaca35-0408-47fa-9847-77d3a7325111.png)

**Comment by yuzhichang** [comment]
When  clickhouse_sinker stop,
```
zhichyu@leno:~$ kcl group describe -v prom_metric
GROUP        prom_metric
COORDINATOR  3
STATE        Empty
BALANCER     
MEMBERS      0

```
![Screenshot_2020-12-16_10-22-00](https://user-images.githubusercontent.com/153784/142094779-ffeaca35-0408-47fa-9847-77d3a7325111.png)

**Comment by twmb** [comment]
Shoot, kcl doesn't print empty groups. I haven't ported my improvements to do that yet. What I'm trying to do here is view what is committed. Could you potentially temporarily add one consumer (and disable committing) and then run kcl again? Alternatively if you'd like to go through setting up `rpk` I could link you to that (I have improvements to describing groups there). Also if you're open to hopping into discord I could interactively walk through this.

Also I see you're using `kafka-ui`--may want to check out `kowl` as well.

Basically what this looks like so far:
- The client is committed to 2028917583, but with leader epoch == 0.
- The records for leader epoch 0 ended at 2023643056
- Likely, leader epoch 1 resumes after that.

You can check leader epoch one with `kcl misc offset-for-leader-epoch gaoju_test -e 1`. I the end offset to be higher.

What this means, if the commit is accurate, is that the partition has lost data. The client previously consumed to 2028917583 on leader epoch 0, but the broker lost data, and leader epoch 0 ended at offset 2023643056, at which point offsets were produced with leader epoch 1.

**Comment by yuzhichang** [comment]
```
zhichyu@leno:~$ kcl misc offset-for-leader-epoch gaoju_test -e 1
BROKER  TOPIC       PARTITION  LEADER EPOCH  END OFFSET  ERROR
1       gaoju_test  1          0             91612350    
3       gaoju_test  0          0             2023643056  
zhichyu@leno:~$ kcl misc offset-for-leader-epoch gaoju_test -e 2
BROKER  TOPIC       PARTITION  LEADER EPOCH  END OFFSET  ERROR
1       gaoju_test  1          2             91983371    
3       gaoju_test  0          2             2784020682  
zhichyu@leno:~$ kcl misc offset-for-leader-epoch gaoju_test -e 3
BROKER  TOPIC       PARTITION  LEADER EPOCH  END OFFSET  ERROR
1       gaoju_test  1          2             91983371    
3       gaoju_test  0          -1            -1          
zhichyu@leno:~$ 
```

I'm willing to try `rpk`.  I consider `kafka-ui` is better than `kowl`, since the former support multi-cluster, adding partitions, and container deployment.

**Comment by twmb** [comment]
Alright so what this looks like is that gaoju_test went directly from leader epoch 0 to leader epoch 2 (potentially it moved around twice, who knows). After that, offsets were produced for leader epoch 2.

Now we just need to see what the client is committed to. rpk v21.10.1 has the new group improvements, but if you want to install it directly,
```
go install github.com/vectorizedio/redpanda/src/go/rpk/cmd/rpk
```

and then create a redpanda.yaml either in your current directory or home directory, 
```
rpk:
  kafka_api:
    brokers:
      - .. seed
    tls:
      - key_file:
        cert_file:
        truststore_file: <this is just your CA cert, if necessary; I'm planning to fix the name someday>
    sasl:
      - user:
        password:
        type: scram-sha-256
```
I think that's it; I usually don't create a redpanda.yaml because I talk to localhost:9092 without sasl/tls.

Then you can use `rpk group describe <group> --config redpanda.yaml`

**Comment by yuzhichang** [comment]
I guess the problem is from here:
https://github.com/housepower/clickhouse_sinker/blob/682347ccd4cd38a0e8e6784ede67dc3c74ecd49c/input/kafka_franz.go#L112
```
k.cl.CommitRecords(context.Background(), &kgo.Record{Topic: msg.Topic, Partition: int32(msg.Partition), Offset: msg.Offset})
```
Maybe I shall set LeaderEpoch for this Record.

**Comment by twmb** [comment]
Oh, yes, absolutely. The intent of that function is to be passed records that were returned previously from `Poll`. You could commit with `LeaderEpoch: -1` as well, which will disable leader epoch validation. But, I recommend using it to these odd edge case data loss scenarios.

**Comment by twmb** [comment]
I believe we found the issue -- closing now. Please reopen if you still have questions!

**Comment by yuzhichang** [comment]
`LeaderEpoch: -1` fixed the problem. Thanks for your help!
