### ISSUE TITLE
MSK IAM: Too many connections

### ISSUE THREAD

**Issue by clocklear** [twmb/franz-go#109]
Hello!  First off, thanks for a wonderful project. ❤️ 

We are getting started with Kafka using this client to interface with AWS MSK.  Following the examples herein, things seem to work fine, but whenever we have a cold start of our producer (read: when the app is running but has not produced any records to Kafka yet) we see the following sporadically:

```
[ERROR] unable to initialize sasl; broker: 1, err: [74909301-1b7d-44fe-b02e-fe699c66c073]: Too many connects: SASL_AUTHENTICATION_FAILED: SASL Authentication failed
```

We are using the client across many threads, so I'm speculating there are many requests to the AWS STS/IAM all at once.  I'm not super familiar with the mechanics of IAM authentication, but perhaps this could be defended against by utilizing [singleflight](https://pkg.go.dev/golang.org/x/sync/singleflight) to prevent duplicative IAM calls?  It is also possible the error is originating in my func that creates the `Auth` struct:

```
mech = franzAws.ManagedStreamingIAM(func(ctx context.Context) (franzAws.Auth, error) {
	creds, err := c.AWSConfig.Credentials.Retrieve(ctx)
	if err != nil {
		return franzAws.Auth{}, err
	}
	return franzAws.Auth{
		AccessKey:    creds.AccessKeyID,
		SecretKey:    creds.SecretAccessKey,
		SessionToken: creds.SessionToken,
	}, nil
})
```

I will attempt making this a bit more thread safe, but was curious if you had any thoughts.  Thanks again!

**Comment by clocklear** [comment]
Nevermind, I'm relatively confident this is caused by service limits associated with using `kafka.t3.small` instances on the AWS side:

> Brokers of type kafka.t3.small are limited to 1 TCP connection per broker per second. If you want a client to retry connections after 1 second, set the configuration parameter reconnect.backoff.ms to 1000. You can also set this parameter to higher values. For more information, see reconnect.backoff.ms in the Apache Kafka documentation.

I'll close this issue for now because I'm 99% sure that is what is going on.  I'm bumping up the size of our cluster now; if that doesn't resolve the issue, I'll reopen.

**Comment by clocklear** [comment]
Confirmed the problem disappears when I use bigger instance types.  Thanks Amazon. 🤦

**Comment by twmb** [comment]
Awesome, glad you solved that! I was about to go looking through github because I searched "AWS_MSK_IAM" recently for kicks and saw some similar looking issue.
