### ISSUE TITLE
Describing ACLs returns an ACL that doesn't exist...or does it?

### ISSUE THREAD

**Issue by marshmallory** [twmb/franz-go#126]
This could be my naïveté.

**Goal: Determine whether an ACL exists or not.**

**Details:**
We're trying to use the DescribeACLs function.  It's set up like this:
`resp, err := cl.DescribeACLs(ctx, ab)` where `ab` is the builder.
When we call this, we get back the DescribleACLsResult.

What we need is to determine whether an ACL exists or not.  I was expecting to be able to do this by looking at `DescribedACLs` in the above `DescribeACLsResult`.  Based on the docs, this `DescribedACLs` is the actual data coming back from Kafka saying either there is a match on the given pattern or there is not.  What I am seeing is it returns exactly the same data, meaning it appears to already exist.

Does it create it by chance once you search for it?  I see `exists := resp[0].Described[0]` as nil for a split second, which was what we're planning on using to determine whether it exists or not.

**Questions:**
1. Are we going about this the right way?
2. Is it even possible to determine if an ACL exists/doesn't exist in a binary fashion?
3. Is the described behavior above expected?  I was thinking it would return a nil, or empty `DescribedACLs` when it doesn't find it, but instead those fields are populated.

Thank you for your help!  Hopefully I can wrap my brain around how this works.

**Comment by twmb** [comment]
Describing ACLs definitely does not create ACLs. Do you have any ACLs that exist beforehand? What filter are you using (what's your builder input?)?

As an example of how I've used the builder, I integrated it into rpk: 
https://github.com/vectorizedio/redpanda/blob/dev/src/go/rpk/pkg/cli/cmd/acl/common.go#L316-L350
https://github.com/vectorizedio/redpanda/blob/dev/src/go/rpk/pkg/cli/cmd/acl/list.go#L128-L161

**Comment by marshmallory** [comment]
I think we had some lingering that was giving that appearance, so that is sorted.  Thank you for the links. I will check these out!
