### ISSUE TITLE
Is it possible to have a unique ID for each ACL?

### ISSUE THREAD

**Issue by marshmallory** [twmb/franz-go#134]
Curious if this is possible.  We're trying to use k8s to manage Kafka ACLs, and are running into a one to many problem.  K8s thinks there's one ACL:one k8s managed resource.

If there's a unique ID, we can use that as the name in k8s, and it would let us manage each ACL individually, even though they are all using the same name.

Just a thought.  This may be a limitation of Kafka, and that's fine.  I don't understand Kafka intricately enough to make that call.

Thanks!

**Comment by twmb** [comment]
There is no unique name for ACLs, and unfortunately there is no way to uniquely identify an ACL past looking at _all_ of its fields. In the past when I've needed to do something similar, I've created a sha256 of all the fields, where each field is separated by two null characters (numbers being hashed by their byte representation, bools hashed by '0' or '1').

I could theoretically add this to kadm, but it would be my own prescription of the unique name of an ACL and wouldn't be anything "official" -- so, I'm not sure that type of hashing belongs to kadm proper, vs. the user defining it in their code.
