### ISSUE TITLE
errNotInTransaction is not a public error

### ISSUE THREAD

**Issue by Zach-Johnson** [twmb/franz-go#138]
Hello -

I'm curious why `errNotInTransaction` is not a public error. It is returned to the calling client in cases when a transaction has not been opened, and it would be nice to be able to check explicitly for this error type.

**Comment by twmb** [comment]
The original version of franz-go had way too many errors public, most of which were internalized before stabilizing on 1.0. What's the need to check against `errNotInTransaction`? I'd expect that error to mean an application bug, in that you may encounter it when developing but you'd never encounter it in production?

**Comment by Zach-Johnson** [comment]
The need is largely convenience, I'm calling `EndTransaction` with `kgo.TryAbort` when my application receives an exit signal, so it will throw this error if it didn't happen to be in the middle of doing something. I can obviously work around this by keeping track of whether a transaction is in-flight or not, I just think it is an unpleasant API to return un-exported types.

**Comment by twmb** [comment]
What do you think about calling `kgo.AbortBufferedRecords` before that? It takes a context, but it really shouldn't block. The intent is that no record should be buffered when entering `EndTransaction`.

**Comment by Zach-Johnson** [comment]
Hm, yeah, it looks like I'm not calling `kgo.AbortBufferedRecords` at all right now (even in cases where it looks like I should be). I'm not following how this relates to the first question about calling `EndTransaction` when not in a transaction though? Is that because I would expect a different error from `kgo.AbortBufferedRecords` if it's called outside of a transaction?

**Comment by twmb** [comment]
If records are aborted, the client calls promises with the exported `ErrAborted` (this is the case whether in a transaction or not). The API of `EndTransaction` is such that it expects no records are buffered when entering, and nothing will be produced while `EndTransaction` executes (as well as `BeginTransaction`). In short, the `errNotInTransaction` error should never be encountered.

Are you concurrently calling `EndTransaction` while producing? I worry that if you're encountering the error at all, you may be concurrently producing.

**Comment by Zach-Johnson** [comment]
No, in the regular case my application finishes processing data and calling `Produce`, then calls `Flush` and then `EndTransaction` with `TryCommit`. In the case where I'm hitting this error my application is idling when it gets a cancellation signal, and then I'm calling `EndTransaction` with `TryAbort`.

**Comment by twmb** [comment]
Are you seeing this as a return from `EndTransaction`? I thought you were seeing this in a record promise.

**Comment by Zach-Johnson** [comment]
I am seeing this on the return from `EndTransaction`, the error message is `cannot produce record transactionally if not in a transaction` though, so it's a bit confusing. I believe I'm hitting this line 
```	
	if !cl.producer.inTxn {
		return errNotInTransaction
	}
```

**Comment by twmb** [comment]
I can probably relax this error in `EndTransaction` to return nil if not currently in a transaction. To confirm, when you call `EndTransaction` on client close, do you kill and wait for the other goroutine that is beginning / producing / ending?

**Comment by Zach-Johnson** [comment]
That seems reasonable to me.

Yes I do, it's part of the same routine.

**Comment by twmb** [comment]
This has been released in v1.3.5 (v1.4 will be a much larger release, soon)

**Comment by Zach-Johnson** [comment]
> This has been released in v1.3.5 (v1.4 will be a much larger release, soon)

Thank you!
