### ISSUE TITLE
UNKNOWN_TOPIC_OR_PARTITION

### ISSUE THREAD

**Issue by robeng1** [twmb/franz-go#139]
I'm trying to write to a topic and I keep getting this error UNKNOWN_TOPIC_OR_PARTITION: this server does not host this topic-partition

**Comment by twmb** [comment]
Does the topic exist? Do you have any tool that can check the metadata of the topic externally (a cli tool, such as kcl or rpk)?

**Comment by robeng1** [comment]
The topic doesn't exist, I want it to be created on the fly

**Comment by twmb** [comment]
The kgo.AllowAutoTopicCreation option can do that for you

**Comment by robeng1** [comment]
Nice, thanks so much for taking the time. I'll try it out and give you feedback
