### ISSUE TITLE
Who uses this?

### ISSUE THREAD

**Issue by twmb** [twmb/franz-go#142]
I've created a "Who uses this?" small list in the readme. If you would like your company to be on this list, please mention it on this issue or create a PR. Thank you!

**Comment by vtolstov** [comment]
I'm agree about simple list with sites and I can say that you software used in big companies, but in current situation about Russia I don't think that I can do that now.

**Comment by twmb** [comment]
I'm ok with a text list, librdkafka does something similar: https://github.com/edenhill/librdkafka/wiki/Powered-by-librdkafka

**Comment by twmb** [comment]
Mentioning here and updating the issue text -- I've created a "Who uses this?" small list in the readme. If you would like your company to be on this list, please mention it on this issue or create a PR (so, the original desire for logos has changed to a simple list now, which makes things easier).

**Comment by yuzhichang** [comment]
My organization:
[Eoitek](https://eoitek.com/)

**Comment by twmb** [comment]
Now that there is at least a _small_ list, I'm going to close this issue. The readme section that mentions who uses this also mentions people can add their name if they want. Thanks all!

**Comment by chenseanxy** [comment]
Opentelemetry now uses franz-go as default client for kafka [producers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter#configuration-settings) and [consumers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver#getting-started)

**Comment by twmb** [comment]
Please open PRs at this point, I'm wary to open PRs claiming usage in other applications on behalf of authors that may not want to have me add the attribution, thank you!
