### ISSUE TITLE
Manual committing example compilation errror

### ISSUE THREAD

**Issue by binarymatt** [twmb/franz-go#143]
if i try to run the manual commit examples here https://github.com/twmb/franz-go/blob/d0a44929acf4fb47bdb7b78b859b79d2ae38286a/examples/manual_committing/main.go

I'm getting a compile error on line 48:
`./main.go:48:63: cannot use os.Into() (type kadm.Offsets) as type map[string]map[int32]kgo.Offset in argument to kgo.ConsumePartition`

does line 48 need to look like this:
`cl, err := kgo.NewClient(seeds, kgo.ConsumePartitions(os.Into().Into()))`

**Comment by twmb** [comment]
Yep good find, the kadm package has gone through some revisions and this example looks to be written before that.

FWIW I'm not the happiest with the `Into` APIs, but I don't have a great alternative idea yet (#141).
