### ISSUE TITLE
Add produceSync() method

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#15]
In order to await the response of a produced record I have to use a callback. This is a bit cumbersome as I have to use a waitgroup or a channel so that I could proceed with handling the produce response like this:

```go
       var wg sync.WaitGroup
	wg.Add(1)
	err = client.Produce(ctx, &rec, func(rec *kgo.Record, err error) {
		defer wg.Done()
		if err != nil {
			c.logger.Error("failed to produce record",
				zap.String("topic_name", rec.Topic),
				zap.Error(err),
			)
		}
	})
	wg.Wait()
```

Therefore it would be very handy if franz-go offers another method, such as `ProduceSync()` that does that for me and only returns when the produce request has been handled, so that I don't need to use a promise function.

**Comment by twmb** [comment]
After discussing on Discord, I think this is not needed anymore? Please reopen if so!

**Comment by twmb** [comment]
Just as very delayed followup, this was eventually added :)
