### ISSUE TITLE
Stuck at join and sync loop error

### ISSUE THREAD

**Issue by torkelrogstad** [twmb/franz-go#151]
When initializing a new client with invalid authorization for the group it is trying to access, we get stuck in `groupConsumer.manage()`. Would this be a good place to invoke the `OnGroupManageError` hook? So far I've had to implement some custom and semi-hacky logic with the client started hook to detect invalid configuration. 

This is the log line I'm seeing when enabling logging:

```
[ERROR] join and sync loop errored; group: my-consumer-group, err: GROUP_AUTHORIZATION_FAILED: Not authorized to access group: Group authorization failed., consecutive_errors: 10, backoff: 2.5s
```

**Comment by twmb** [comment]
If you're using AWS_MSK_IAM, this may be related to #205, and may be fixed now with https://github.com/twmb/franz-go/pull/242/commits/eb6e3b584d88d0bb32c8d4a856f456e2b2eae913 which is released in v1.9.1.
