### ISSUE TITLE
Get consumer group rebalance event signal

### ISSUE THREAD

**Issue by Max-Cheng** [twmb/franz-go#152]
In the case of some middleware, manual commits with Kafka happen re-consume, for example.

Kafka -> application -> cache -> consume -> commitoffset

In this case, a new client joining the group will occur with an offset not committed. Making the new client re-consume once,When cache become empty I can call AllowRebalance, but this has no effect until the rebalance happens and maybe occur error(message lost).

**Comment by Max-Cheng** [comment]
Although we can use OnPartitionRevoke, in this function you cannot send signals to other goroutine (or channels, since there are only three param).

**Comment by twmb** [comment]
Not sure I understand the first comment fully -- are you saying that `BlockRebalanceOnPoll` and `AllowRebalance` does not prevent the double-processing issue you're running into?

Also, what are you looking for in `OnPartitionRevoke`? In `OnPartitionRevoke`, can pass a method that has the state you need, similar to this: https://github.com/twmb/franz-go/blob/master/examples/goroutine_per_partition_consuming/autocommit_marks/main.go#L127 ?

**Comment by Max-Cheng** [comment]
tks, I missed example of  goroutine_per_partition_consuming.
