### ISSUE TITLE
Some documents are outdated.

### ISSUE THREAD

**Issue by YiuTerran** [twmb/franz-go#157]
When I read [this](https://github.com/twmb/franz-go/blob/master/docs/producing-and-consuming.md) doc, I found many links are outdated.  Can you update them to match the current code? Thanks very much~

**Comment by twmb** [comment]
This was closed in 324a7ff.

I updated links by searching for `**breaking` and then finding any references of the older APIs. I hope that's comprehensive, but if you see more outdated docs, let me know!
