### ISSUE TITLE
fetches.EachTopic empty .Records() and varying size

### ISSUE THREAD

**Issue by JacobSMoller** [twmb/franz-go#159]
Note: I am only consuming a single topic:
Im not sure this acutally an issue, but more of an issue with my understanding of the differences between.
When using this code i see some varying prints, where in some cases ft.Records() is all 5k messages from PollRecords and in some other cases there I will see 3 prints of varying size combining to be 5k messages.  

And then in some cases I see a couple of fetches coming in with len(ft.Records()) == 0
```golang
func (s *Service) poll() {
	for {
		fetches := s.kafkaClient.PollRecords(context.Background(), 5000)
		if fetches.IsClientClosed() {
			zap.L().Info("shutting down: KafkaClient closed")
			return
		}
		fetches.EachError(func(_ string, _ int32, err error) {
			panic(err)
		})
		fetches.EachTopic(func(ft kgo.FetchTopic) {
			fmt.Println(len(ft.Records()))
		})
	}
}
```

On the other hand using fetches.Records() as below i see 5k messages consistently(Until the consumer group is caught up to the kafka offset)
```golang
func (s *Service) poll() {
	for {
		fetches := s.kafkaClient.PollRecords(context.Background(), 5000)
		if fetches.IsClientClosed() {
			zap.L().Info("shutting down: KafkaClient closed")
			return
		}
		fetches.EachError(func(_ string, _ int32, err error) {
			panic(err)
		})
                fmt.Println(fetches.Records())
	}
}
```

Any clarification on this behaviour would be greatly appreciated.

**Comment by twmb** [comment]
When using Poll functions, the client waits until there is at least something to return (you're not going to see no records _and_ no errors). `PollRecords` is upper bounding the return to 5k, but it's possible you'll see fewer records if there are fewer records buffered in the client that are ready to be returned. Seeing a consistent 5k to me signals that either you're consuming that has a lot of records in the broker; eventually you should reach the end and see fewer than 5k.

When the client buffers records to be returned, it buffers them per fetch if a fetch has _any_ records. If I fetch foo partition 1 and 2, and 2 has records while 1 doesn't, the client actually buffers the metadata that was returned for partition 1 as well. This metadata is the FetchPartition, which contains the high watermark, log start offset, and last stable offset.

So, the difference between your cases is that in the first case, you're seeing these empty partitions (or topics, if you fetched a topic that has no records while another topic did), and in the latter case, you're just seeing all records.

**Comment by twmb** [comment]
Let me know if the above isn't clear or doesn't answer the issue fully; I'll go ahead and close this for now.
