### ISSUE TITLE
PollFetches / PollRecords doesn't seem to be obeying context timeout.

### ISSUE THREAD

**Issue by freeformz** [twmb/franz-go#160]
I have a small cli application that "tails" a topic's partition and displays an abbreviated version of the records it receives. The program uses a context to limit the amount of time spent tailing records (optionally). I was expecting the ctx to abort both PollFetches / PollRecords, but that doesn't seem to be the case and the program runs forever unless it also checks ctx.Done().

Here is the main loop. Unless I uncomment the select block the program runs forever (or at least until I cancel it well after 5 seconds).

```go
ctx, cancel := context.WithTimeout(context.Background, 5 * time.Second)
defer cancel()

for {
		fetches := client.PollRecords(ctx, maxRecords) // or client.PollFetches(ctx)
		if fetches.IsClientClosed() {
			os.Exit(0)
		} 
		/*
			select {
			case <-ctx.Done():
				os.Exit(0)
			default:
			}
		*/
		fetches.EachError(func(t string, p int32, err error) {
			log.Fatal(t, p, err)
		})

		fetches.EachRecord(func(m *kafka.Record) {
			printRecord(m)
		}
}
```

Will attach some logging in a few

**Comment by freeformz** [comment]
I added the following Opt to the client:
```go
		kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelDebug, func() string {
			select {
			case <-ctx.Done():
				return "done"
			default:
				return "not done"
			}
		})),
```

And the log looks like this

```
not done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 54.997µs, time_to_write: 35.467µs, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 29.281µs, time_to_write: 25.746µs, err: <nil>
not done[DEBUG] read Fetch v12; broker: 6, bytes_read: 540, read_wait: 35.514µs, time_to_read: 18.84603ms, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 36.067µs, time_to_write: 24.24µs, err: <nil>
not done[DEBUG] read Fetch v12; broker: 6, bytes_read: 2183, read_wait: 48.451µs, time_to_read: 146.539608ms, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 33.822µs, time_to_write: 40.027µs, err: <nil>
not done[DEBUG] read Fetch v12; broker: 2, bytes_read: 464, read_wait: 43.486µs, time_to_read: 177.598088ms, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 32.347µs, time_to_write: 26.25µs, err: <nil>
not done[DEBUG] read Fetch v12; broker: 6, bytes_read: 3932, read_wait: 53.752µs, time_to_read: 21.088223ms, err: <nil>
not done[DEBUG] read Fetch v12; broker: 2, bytes_read: 508, read_wait: 40.796µs, time_to_read: 474.86287ms, err: <nil>
not done[DEBUG] read Fetch v12; broker: 5, bytes_read: 495, read_wait: 34.876µs, time_to_read: 2.242187223s, err: <nil>
not done[DEBUG] read Fetch v12; broker: 4, bytes_read: 2234, read_wait: 37.943µs, time_to_read: 898.613955ms, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 26.369µs, time_to_write: 43.604µs, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 5, bytes_written: 89, write_wait: 20.238µs, time_to_write: 24.678µs, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 16.395µs, time_to_write: 24.694µs, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 4, bytes_written: 89, write_wait: 19.626µs, time_to_write: 22.857µs, err: <nil>
not done[DEBUG] read Fetch v12; broker: 6, bytes_read: 12250, read_wait: 48.973µs, time_to_read: 21.479406ms, err: <nil>
not done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 26.707µs, time_to_write: 28.694µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 2759, read_wait: 78.865µs, time_to_read: 232.573331ms, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 2030, read_wait: 43.496µs, time_to_read: 209.544982ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 26.177µs, time_to_write: 23.292µs, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 15.996µs, time_to_write: 24.323µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 4, bytes_read: 443, read_wait: 73.867µs, time_to_read: 302.630934ms, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 2061, read_wait: 39.782µs, time_to_read: 69.955989ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 4, bytes_written: 89, write_wait: 31.544µs, time_to_write: 28.45µs, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 16.618µs, time_to_write: 18.314µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 464, read_wait: 63.018µs, time_to_read: 88.690956ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 22.854µs, time_to_write: 20.756µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 464, read_wait: 29.092µs, time_to_read: 125.585756ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 36.081µs, time_to_write: 25.226µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 5872, read_wait: 34.239µs, time_to_read: 145.718258ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 23.731µs, time_to_write: 19.838µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 555, read_wait: 33.312µs, time_to_read: 309.606681ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 35.483µs, time_to_write: 42.382µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 624, read_wait: 29.476µs, time_to_read: 308.493372ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 29.363µs, time_to_write: 21.35µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 461, read_wait: 43.857µs, time_to_read: 28.672624ms, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 4244, read_wait: 36.365µs, time_to_read: 28.585356ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 2, bytes_written: 89, write_wait: 32.92µs, time_to_write: 21.882µs, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 23.183µs, time_to_write: 17.001µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 1887, read_wait: 35.485µs, time_to_read: 33.268064ms, err: <nil>
done[DEBUG] wrote Fetch v12; broker: 6, bytes_written: 89, write_wait: 27.252µs, time_to_write: 19.553µs, err: <nil>
done[DEBUG] read Fetch v12; broker: 2, bytes_read: 462, read_wait: 35.024µs, time_to_read: 343.010062ms, err: <nil>
done[DEBUG] read Fetch v12; broker: 6, bytes_read: 2369, read_wait: 25.031µs, time_to_read: 309.544702ms, err: <nil>
```

**Comment by freeformz** [comment]
Nevermind, I misread the docs at first.

**Comment by twmb** [comment]
I _think_ what you were running into is that if a context is canceled, polling returns anything currently buffered but does not wait. So, records were being fetched quickly enough that polling with a canceled context was still making forward progress.

Also, good to hear from you again, hope you're doing well and things are going great! :smile:

**Comment by freeformz** [comment]
I was in the for loop and expecting either `IsClientClosed` or `EachError`/`Errors` to start returning `context.Canceled` on the next Poll{Records,Fetches}. It doesn't so you also need to check the context itself.

**Comment by freeformz** [comment]
Also 👋

**Comment by twmb** [comment]
I could add an option to inject an error if the context passed to Poll is canceled and to _not_ drain any currently buffered records. This would need to be in v1.6, because v1.5 was just released so I want to let a backlog of features grow for a bit.

Perhaps,
```go
func ErrorPollOnCanceledContext() ConsumerOpt
```

**Comment by freeformz** [comment]
Essentially I would expect Poll{Records,Fetches} with a canceled Context to just return and not do any work. If the context is canceled while it's working then I would expect it to finish work and return. In a scanner-type setup (like this is) I would expect the context.Canceled error to be exposed in the Errors or some other means.

I would expect this to be the default behavior since it takes a context, but if that is too big of a change then a consumer option is fine.

**Comment by twmb** [comment]
The client performs no waiting if the context is canceled, it does a ping of what exists and is ready and returns it if anything is available. The context is used if waiting occurs _at all_. The context basically replaces the model that exists in a lot of client implementations:

* [`poll`](https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#poll-java.time.Duration) takes a timeout in the Java
* [`consume`](https://docs.confluent.io/3.0.0/clients/librdkafka/classRdKafka_1_1KafkaConsumer.html#a7dc106f1c3b99767a0930a9cf8cabf84) takes a timeout in librdkafka
* clients implemented using librdkafka (confluent-kafka-*) all use millisec timeouts for poll

I figured a context is a more powerful way to control quitting the poll, and since quitting the poll isn't an error, an error doesn't need to be outright returned here. I'm not sure if there actually are use cases to cancel a context and for a client to be perfectly ok with it, but the thought here is that it is at least a valid use case. I can't be sure if people rely on the current behavior or not -- a new option would be a safer default, but I'll ask around a bit.

**Comment by freeformz** [comment]
@twmb most methods (but probably not all of them) that take a context will return `ctx.Err()` if the context is "done".

Take this for example:

```go
	ctx, cancel := context.WithTimeout(context.Background(), time.Nanosecond)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "http://google.com/", nil)
	if err != nil {
		log.Fatal(err)
	}
	cancel()

	resp, err := http.DefaultClient.Do(req)

	log.Println(resp)
	log.Println(err)
	log.Println(<-ctx.Done())
	log.Println(ctx.Err())
```

```console
$ go run main.go
2022/05/04 14:08:40 <nil>
2022/05/04 14:08:40 Get "http://google.com/": context deadline exceeded
2022/05/04 14:08:40 {}
2022/05/04 14:08:40 context deadline exceeded
```

**Comment by freeformz** [comment]
And that is the behavior I would expect from a library and expected from `Poll*`

**Comment by twmb** [comment]
Most, but not all. There aren't obvious examples exported within the stdlib, but there are multiple examples in the modload [source](https://github.com/golang/go/blob/0bd7408f901f33c6f0a5a542f8de6bf17c901e79/src/cmd/go/internal/modload/load.go#L495-L617).

I don't fully agree with the necessity for returning ctx.Err. The http case is obvious: a request is being issued, any cancelation means the request cannot be fulfilled, which is an error. The context here is just a wait.

Regardless, this doesn't really affect me and I've seen one instance where this could benefit a person, so I've changed the default behavior in v1.5.1. More reasoning is written inside the commit referenced just above.
