### ISSUE TITLE
Log with context.Context

### ISSUE THREAD

**Issue by victoraugustolls** [twmb/franz-go#162]
Hi! First of all I wanna thanks for all the work you put in this library, it's usage is far superior than anything I've used so far!

That being said, I was wondering if it would be possible to, somehow, have access to the `context.Context` on the `Logger` interface. Maybe by creating a new one?

The motivation is that, with zerolog context integration, it would be possible to recover a logger from the context with some key fields already set by the application!

Don't know the best approach here, but I was thinking about a new interface like `LoggerCtx` and create a validation when creating a new client so only one of the `Logger` options are used.

**Comment by twmb** [comment]
I'm not sure how a context here would be useful, because all log calls currently don't use a context. What context would be passed to the logger other than `context.Background()`? And, if it's just `context.Background()`, wouldn't it be easier to instantiate that _within_ the logger?

**Comment by victoraugustolls** [comment]
I'm going to be honest and say that I dint't do a deep dive to where the `Logger` was being used, and I'm sorry for that. If thats the case, forget about it and thanks a lot for the quick response @twmb !

**Comment by twmb** [comment]
No worries, lmk if you think of a use case for the context -- it's something worth considering if there's a need.
