### ISSUE TITLE
[Question] Why does franz-go override the timestamp (Record.Timestamp) on produce?

### ISSUE THREAD

**Issue by brunsgaard** [twmb/franz-go#166]
Hi @twmb,

Why does franz-go override the timestamp (Record.Timestamp) on produce?
https://github.com/twmb/franz-go/blob/v1.5.3/pkg/kgo/record_and_fetch.go#L93-L94

This behaviour seems to be different from other clients where one is able to set the event origin timestamp on a record?
From your documentation you seem to be fully aware of this behaviour, could you elaborate on this decision/behaviour?

And the natural question, is there a way to set a custom timestamp on records?

**Comment by twmb** [comment]
I'm not sure why I eventually blocked this, but I've added a commit to allow setting the timestamp type yourself: https://github.com/twmb/franz-go/commit/653010d65361bf96730f251c5a2b34ff35a0a5ba

This will be in v1.6, which I aim to release ~today.

**Comment by brunsgaard** [comment]
Got it, thanks for the answer

**Comment by twmb** [comment]
Released in v1.6.0: https://github.com/twmb/franz-go/releases/tag/v1.6.0
