### ISSUE TITLE
Client.CommitRecords failed with REQUEST_TIMED_OUT

### ISSUE THREAD

**Issue by yuzhichang** [twmb/franz-go#168]
franz-go version: v1.5.0
clickhouse_sinker version: v2.4.1

clickhouse_sinker quits due to franz-go `Client.CommitRecords REQUEST_TIMED_OUT` failure. This failure occurs every 20 minutes to several hours when clickhouse_sinker consuming from a somewhat busy Kafka cluster. There's no old GC or leader swiching occur on the Kafka cluster at that time. I'm not sure why the requests timeout.

The debug log of franz-go and clickhouse_sinker are as follow:

![franz_commit_timeout](https://user-images.githubusercontent.com/153784/170934709-7ce9890c-b81c-4281-8f27-cf9299204bd6.jpeg)

I think the franz-go client will retry for at last [20 times](https://github.com/twmb/franz-go/blob/7689d6ffb9909e9017d6c77ad7cf58035a201e3d/pkg/kgo/config.go#L676) for [REQUEST_TIMED_OUT](https://github.com/twmb/franz-go/blob/7689d6ffb9909e9017d6c77ad7cf58035a201e3d/pkg/kerr/kerr.go#L83) error. However I don't see the retry action from the log. Shall I retry at user level?

**Comment by twmb** [comment]
Some of the logs look a little out of order, which is very weird (the `wrote OffsetCommit` should come after `in CommitOffsetsSync`). I didn't even know that OffsetCommit _could_ timeout, so this isn't something coming from within franz-go.


Perhaps you're running into this issue? https://issues.apache.org/jira/browse/KAFKA-8334

**Comment by yuzhichang** [comment]
@twmb Do you want to get the traceback within franz-go of the error? I used to wrapping errors of third-party libraries at the first place with `github.com/pkg/errors`.

**Comment by twmb** [comment]
I think broker logs would be more relevant here, to see if this is the Kafka issue I linked above (KAFKA-8334)

**Comment by yuzhichang** [comment]
@twmb I've added retry on commit failure in clickhouse_sinker. The Kafka version is 2.2.1, and log level is INFO. 
Judging if this issue is KAFKA-8334 reuires changing the log level to DEBUG. This' not allowed due to some reason.
Close now. I'll keep watching.
Thanks for your kind help!
