### ISSUE TITLE
Missing example for maunal commiting (new kadm 1.0)

### ISSUE THREAD

**Issue by huuhait** [twmb/franz-go#173]
`os.Into()` was removed idk what i gonna use

**Comment by twmb** [comment]
I'll update the examples/manual_committing/main.go to use Koffsets, my mistake on forgetting this older example.

**Comment by twmb** [comment]
https://github.com/twmb/franz-go/commit/6b131bfdd70cdb878658d0f564baf188952554bc

I think that does it (and shows I botched v1.1.0 so kadm is now v1.1.1...)
