### ISSUE TITLE
Build failed when using go 1.15 and franz-go 1.6.0

### ISSUE THREAD

**Issue by ly931003** [twmb/franz-go#176]
# github.com/twmb/franz-go/pkg/kgo
/root/go/pkg/mod/github.com/twmb/franz-go@v1.6.0/pkg/kgo/record_formatter.go:1588:13: undefined: io.ReadAll

io.ReadAll not available in go 1.15

**Comment by ly931003** [comment]
Maybe we can replace io.ReadAll with ioutil.ReadAll. As of Go 1.16, ioutil.ReadAll simply calls io.ReadAll.

**Comment by twmb** [comment]
Yes that's the proper solution.

Someday, the minimal version should be bumped to go1.16 -- 1.15 has been unsupported for two releases now.

**Comment by twmb** [comment]
This will be out in v1.6.1 or v1.7.0, whichever comes first.

**Comment by twmb** [comment]
Since this is minor and the only change so far for 1.6.0, I'll probably wait until I address #175 and then release both at once for 1.7.0

**Comment by twmb** [comment]
This has been released in v1.7
