### ISSUE TITLE
Git Tags/Versions Not Quite Right?

### ISSUE THREAD

**Issue by steve-gray** [twmb/franz-go#183]
Edit: Ignore, can delete. Turns out we'd were go getting the root package which is't a go package root.

**Comment by godwhoa** [comment]
Would an import statement in the [getting started](https://github.com/twmb/franz-go#getting-started) example help prevent this confusion?

**Comment by twmb** [comment]
I think an "install" block might be useful, since there are many modules in this one repo which is pretty uncommon.

**Comment by twmb** [comment]
lmk if the recently pushed install block clears things up or not :)

**Comment by steve-gray** [comment]
I suspect it'd be far more informative/better to add the `import` directives to the examples showing that the package is not rooted at the base of the repo - which is essentially the de-facto standard for most mainstream pages. Otherwise people will be trying to figure out where kgo comes from (and as in my case, referencing the root and wondering why go get fails silently).

**Comment by twmb** [comment]
I've expanded the wording a little bit. However, given the many examples, and the readme, and how other projects do it, I'm not sure how much more it makes sense to continue adding to the readme.
