### ISSUE TITLE
Question: Should PollRecords create batches close to the max records argument if a consumer is lagging

### ISSUE THREAD

**Issue by kklipsch** [twmb/franz-go#184]
Recently saw behavior in one of our applications where a consumer that was very behind on a topic was getting record sizes well below the max record parameter in the Client.PollRecord method.  Is that expected?  If so for what reason?

**Comment by twmb** [comment]
`PollRecord` only drains from the currently buffered queue, _up to_ the requested record limit. The client buffers up to `MaxConcurrentFetches` of fetches at once (by default, one fetch per broker). Each fetch itself is controlled in size by `FetchMaxBytes` (by default, 50MiB per fetch) and `FetchMaxPartitionBytes` (by default, 1MiB per partition within each fetch).

* How many partitions are being fetched?
* Are any of the given limits overrode?

**Comment by kklipsch** [comment]
- 15 (spread 10/5 across 2 topics).
- No overrides.

**Comment by twmb** [comment]
Might want to increase the FexMatchPartitionBytes as well, but 1MiB _should_ be enough for the default small-records case. Anyway, lmk if tuning any settings fixes things, thanks!

**Comment by kklipsch** [comment]
Our records are a fairly big (1.5K-75K) so I think the partition limit is precisely the problem.  Have upped it and am running experiments now.

**Comment by twmb** [comment]
I've also always considered if a second fetch should be buffered for a single broker in some circumstances, but I don't think the ramifications for that are great (nor do I know what that'd affect inside the code)

**Comment by kklipsch** [comment]
I agree that would be harder to reason about.  For us it was simply hitting the partition maximum.  Changing that to a more appropriate value fixed the issue.

If we had more partitions its possible we'd hit the fetch max but currently we are off of that a bit.
