### ISSUE TITLE
Consuming topics with a different poll rate

### ISSUE THREAD

**Issue by un000** [twmb/franz-go#188]
Hey!

I have 2 topics with a same handler:
| topic  | msg/sec |
| ------------- | ------------- |
| fast | 50 000 |
| slow | 5 |

But for a `slow` topic it's needed to process messages as fast as possible. `fast` topic blocks polling until it's be processed.
Is there any easy way without creating a second client to poll messages separately? Or maybe I have to write a code which distinguishes which topic is slow, and pauses fetching messages from it for a time.

<details>
  <summary>Poll code</summary>

```
func (c *Consumer) pollAndProcess(logger *zap.Logger, processor ConsumerProcessor) error {
	pollCtx, pollCancel := context.WithTimeout(context.Background(), c.config.PollTimeout)
	fetches := c.client.PollRecords(pollCtx, 128)
	pollCancel()

	switch {
	case fetches.IsClientClosed():
		logger.Info("consumer client closed", field.Error(fetches.Err()))
		return fetches.Err()
	case fetches.Err() != nil:
		fetches.EachError(func(t string, p int32, err error) {
			logger.Error("consume error", field.Topic(t), field.PartitionID(p), field.Error(err))
		})
	}

	defer c.client.AllowRebalance()

	if len(fetches.Records()) == 0 {
		return nil
	}

	eachRecord := c.createEachRecordFunc(logger, processor)

	wg := &wait.Group{}
	fetches.EachTopic(func(t kgo.FetchTopic) {
		t.EachPartition(func(p kgo.FetchPartition) {
			metricName := fmt.Sprintf("consumer.%s.%s", processor.Name(), t.Topic)
			wg.Add(func() {
				p.EachRecord(func(record *ConsumerRecord) {
					eachRecord(metricName, record)
				})
				if !c.config.DisableAutoCommit {
					c.client.MarkCommitRecords(p.Records...)
				}
			})
		})
	})
	wg.Wait()

	return nil
}
```
</details>

**Comment by un000** [comment]
Also, I propose to make helper function `MarkLatestRecord()` because we don't need to sort records when sequent per-partition consuming is done.

**Comment by twmb** [comment]
+1 to `NumRecords`. I'm not sure what `MarkLatestRecord` does / how does it differ from MarkCommitRecords (which currently allocates and could potentially be improved in that manner)?

w.r.t. slow/fast, heoretically, a lot could be added within a client that can check rates of topic consumption or something else, but this would be a lot of assumed intelligence and the client likely would make a bad choice for most people.

> Or maybe I have to write a code which distinguishes which topic is slow, and pauses fetching messages from it for a time.

This is the option I'd go with, although it might be a bit challenging. There are `PauseFetch{Topics,Partitions}` and `ResumeFetch{Topics,Partitions}` APIs that you can use to tell the client to stop polling / resume polling a specific topic.

One way this could potentially be done to use `kadm` to list end offsets periodically and if the consumer is more than X number of messages behind total across all partitions in the slow topic, pause the fast topic. It'd be a bit involved. It'd be easier to use two clients and then send all polls down a channel. A processing goroutine could:

```go
select {
case work = <-slowWork:
default:
        select {
        case work = <-slowWork:
        case work = <-fastWork:
}
```

such that the slow channel is always prioritized, but the fast channel is used if the slow channel has no pending items.

**Comment by twmb** [comment]
> `MarkLatestRecord`

There is a guarantee that within each partition, the highest number record is at the end. One option would be to just use the last topic/partition/offset. It is _possible_ that the same partition will be returned twice if it moved across brokers, so you would need sorting within that, but this is effectively nearly-always-one, rarely-more. With `MarkLatestRecords`, are you relying on autocommit marks? I wonder if this could be `MarkCommitUncommittedRecords`, or `MarkUncommittedRecords`. The former pairs 1:1 with how `MarkCommitRecords` is the mark equivalent to `CommitRecords`, the latter is just ... less ugly 😅 

> consumer-loop polls too frequent when topic empty

How is it polling too frequently? Is your code that calls `PollRecords` polling with a very small deadlined context? What is your `FetchMaxWait` time? The 5s default should be fine.

w.r.t. poll at least MIN, that doesn't exist -- the kgo package will return everything buffered, and if nothing is buffered, `Poll` hangs until something is available.

**Comment by twmb** [comment]
Interesting, have you checked out the `FetchMinBytes` option? It'll allow requests to hang on the broker itself before returning to the client. The default is 1 byte, meaning the broker will return as soon as any data is available. I wonder if that could largely replace your sleep?

**Comment by un000** [comment]
> Interesting, have you checked out the `FetchMinBytes` option? It'll allow requests to hang on the broker itself before returning to the client. The default is 1 byte, meaning the broker will return as soon as any data is available. I wonder if that could largely replace your sleep?

 I think it will work, but, I don't want to test this option because I can "lose" some messages or make an unpredictable latency.

**Comment by twmb** [comment]
What do you mean that this can lose some messages?

And w.r.t. latency, this can be controlled with `FetchMaxWait` as well -- the broker will return when either the min bytes _or_ the max wait are hit.

**Comment by un000** [comment]
@twmb I mean that if inside the topic will be like 1 megabyte of new messages and the FetchMinBytes will be set to 20 megabytes, the latency will be unpredictable, so my system will not know about them for an unknown period.

**Comment by twmb** [comment]
LMK if the combination of those two options solves your issue, I don't think there's much more that can be done within franz-go. Looks like your sleep loop basically sleeps for up to 1s depending on how much you expected to consume within that second -- perhaps setting FetchMinBytes to a higher value and then FetchMaxWait to 1s can approximate that as well.

(not sure if this issue can be closed or not, lmk)

**Comment by un000** [comment]
Thank you
