### ISSUE TITLE
Return more descriptive error messages for kerr.Error

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#19]
I often want to return a proper error message for one of Kafka's returned error codes. I use `kerr.ErrorForCode(partition.ErrorCode)` for this purpose that returns an error which is of type `kerr.Error`.  I'd only like to return a single descriptive string rather than the whole error object and therefore I call the `Error()` method which unfortunately only returns the `Message` property of that `kerr.Error` struct which is something like `UNKNOWN_TOPIC_OR_PARTITION`. A more descriptive error string would be something like this:

```go
func (e *Error) Error() string {
	return fmt.Sprintf("%v (%v))", e.Description, e.Message)
}
```

That would for example return: `"This server does not host this topic-partition. (UNKNOWN_TOPIC_OR_PARTITION)"`

**Comment by twmb** [comment]
How about `return fmt.Sprintf("%v: %v)", e.Message, e.Description)` to result in `UNKNOWN_TOPIC_OR_PARTITION: This server does not host this topic-partition.` Also, should this be under a different method?

**Comment by weeco** [comment]
Yes also fine. I think the default Error() return should be a more descriptive error message than just the error code, so no I think it shouldn't be a different method. Regarding errors I would also suggest to use a non pointer receiver so that the errors are compatible with `errors` package where I can use `errors.As()`. What do you think?

**Comment by twmb** [comment]
I think the pointer receiver is still compatible with `errors.As`, because the example of `errors.As` in the errors package itself uses a pointer receiver:
```go
var perr *os.PathError
if errors.As(err, &perr) {
	fmt.Println(perr.Path)
}
```
