### ISSUE TITLE
Confusion about EpochOffset and exporting less()

### ISSUE THREAD

**Issue by mikijov** [twmb/franz-go#192]
Hi. I am writing a batch consumer that will have very long times (possibly hours) between commits. So I have to use manual committing. I use CommitOffset/CommitOffsetSync as I cannot keep the actual records all this time.

1. As part of calculating the EpochOffset for each of my partitions, I replicated something very similar to the code in [consumer_group.go#2121](https://github.com/twmb/franz-go/blob/eb731e4a05b4aaa9f43e20178e410088c3e0596c/pkg/kgo/consumer_group.go#L2121). Later I found [EpochOffset.less()](https://github.com/twmb/franz-go/blob/eb731e4a05b4aaa9f43e20178e410088c3e0596c/pkg/kgo/consumer_group.go#L1629), which does the same comparison, but for some reason is not exported, and not even used in the rest of franz-go. My question is, can we export less(), and should we use it throughout? (Or am I missing something?)

2. To the best of my research, when manually creating EpochOffset and committing, the offset has to point to ONE AFTER the last message consumed. I am really not sure about this, as no document explicitly says this. Can someone please confirm this? I volunteer to update EpochOffset docs with this and less() details, if you can please confirm that I am using these properly.

**Comment by twmb** [comment]
1) I'd be open to exporting it, I'm always a bit wary about adding new APIs to avoid package bloat / API stability problems, but I think this one is fine

2) Yes the offset has to point _after_ the recently consumed record. It's a little confusing and I know I mention it in some random places. Internally, it's mentioned [here](https://github.com/twmb/franz-go/blob/514f3638dbf5e74cfdcfdca4e93f7e04b9fcf1ac/pkg/kgo/consumer_group.go#L1671-L1676). I'm not sure `Less` would be the best place to document it, vs. just on the Offset field itself in `EpochOffset`, but I'm not 100% sure.

How does the API look like for you? Also, why commit incredibly infrequently?

**Comment by mikijov** [comment]
Thank you very much!

**Comment by twmb** [comment]
This has been released in v1.7.0 :+1:
