### ISSUE TITLE
[Question] Dynamically leave and join to consumer group

### ISSUE THREAD

**Issue by dwagin** [twmb/franz-go#195]
Please help me figure out how to dynamically leave and join to consumer group?
I only found LeaveGroup(). Is there no possibility to join back?

**Comment by twmb** [comment]
The client doesn't implement the option to rejoin after leaving. What's the use case for this?

**Comment by twmb** [comment]
I'd recommend recreating the client, it's cheap to do so and would have roughly the same effect. If possible, don't leave the because leaving and rejoining would cause rebalance storms. lmk if you have a feature proposal here, closing this issue for now

**Comment by dwagin** [comment]
This requires the ability to validate configuration from the outside. I will prepare a pull request about it.
