### ISSUE TITLE
Heartbeat function supported

### ISSUE THREAD

**Issue by ekeric13** [twmb/franz-go#199]
I have been combing through the docs and maybe I missed it, but does franz-go support a heartbeat function?

Similar to these:
https://pkg.go.dev/github.com/Shopify/sarama#Broker.Heartbeat
https://pkg.go.dev/github.com/segmentio/kafka-go#Client.Heartbeat

I think it would essentially just be exposing the ability to make heartbeat requests directly:
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#HeartbeatInterval

**Comment by twmb** [comment]
What is the use case for heartbeating manually?

**Comment by ekeric13** [comment]
I have been having issues with a library that uses `kafka-go` and I am trying to narrow it down to whether it is something with MSK or the client library setup or authentication (msk IAM), etc.

https://github.com/segmentio/kafka-go/issues/516#issuecomment-1234917797

So I am running some tests against popular golang client libraries to see which can reproduce the error and under what circumstances.

One of the tests is a simple heartbeat function.

**Comment by twmb** [comment]
Is the ask to completely control the heartbeat, or to send additional heartbeats as you want? I don't think it's beneficial to completely control it (there's a lot of logic around guarding cooperative stuff before/after).

To send additional heartbeats, you could use the newish `GroupMetadata` function and construct your own heartbeat:

```go
memberID, generation := cl.GroupMetadata()
if generation == -1 {
    // not in a group
}
req := kmsg.NewHeartbeatRequest()
req.Group = ...
req.Generation = generation
req.MemberID = memberID
resp, err := req.RequestWith(cl)
...
```

**Comment by ekeric13** [comment]
Yeah the ask is to completely control the heartbeat. I agree in general it is not beneficial in normal workflow, but this is for debugging purposes and I think it makes sense in that context.

And I will try the GroupMetadata then!

**Comment by twmb** [comment]
I don't think it's a good idea to allow disabling the heartbeating within the client,

[this loop](https://github.com/twmb/franz-go/blob/master/pkg/kgo/consumer_group.go#L848-L958)

is pretty complex and does more than just heartbeat on a tick interval.

Does the above manual heartbeat suffice?

**Comment by ekeric13** [comment]
Yeah the above works. No intention of disabling heartbeating.

**Comment by ekeric13** [comment]
Okay I guess I am getting an issue but not explicitly related to the heartbeat thing.

As mentioned above I am creating a myriad of kafka clients in go and testing them out.
Hitting an error when I try to create a franz-go reader and another reader (see same error when creating a reader via sarama or kafka-go). I am using different topics for each client but the same consumer group.

I am getting 
```
"err":"INCONSISTENT_GROUP_PROTOCOL: The group member's supported protocols are incompatible with those of existing members or first group member tried to join with empty protocol type or empty protocol list.","message":"join group failed"
```

Is this referring to the groupBalancerProtocol?
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Balancers

Or the groupProtocol?
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#GroupProtocol

**Comment by ekeric13** [comment]
Okay I figured it out.

It was the `groupBalancerProtocol`. Other clients either don't support or don't default to `CooperativeStickyBalancer`, which is franz-go's default.

I am curious, why not default to sending in multiple balancers? Like CooperativeStickyBalancer, RangeBalancer, and then lastly RoundRobinBalancer.
An array of balancers is already supported:
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Balancers

**Comment by twmb** [comment]
Once a group has upgraded to cooperative-sticky, it cannot be reverted unless all members leave the group. To read in more full detail, the writeup is here: https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol#KIP429:KafkaConsumerIncrementalRebalanceProtocol-CompatibilityandUpgradePath

Using cooperative-sticky in a group that is currently range is fine, but once on cooperative-sticky, a live rollback is unsafe.

You can use multiple balancers, but usually only for an upgrade path:

`range` => `cooperative-sticky` + `range` => `cooperative-sticky`

This client chooses a default that is prepared for the new defaults that Kafka is moving to, in which case range / round robin will not be used and will not be rolled back to.

But, if you want to work with a group that currently is using one of those older balancers, you can use more balancers in the array.

**Comment by ekeric13** [comment]
Ah, so I was starting up all the clients in go-routines.
Given that cooperative + range is acceptable if range is there first, that means Franz-go must have been joining first and the consumer group was complaining once it received a client that wanted to use range.

So I guess the reason for now updating this:
https://github.com/twmb/franz-go/blob/eb2e62d8b4a08e9c5729f419c92d51a8aeb9aa1d/pkg/kgo/config.go#L497
to include `RangeBalancer()` is cooperative can already work with `range` if a consumer group had already joined with `range`, and if franz-go client connects first than cooperative will just be chosen anyway as it has the highest precedence in choices.
