### ISSUE TITLE
During Turbulence in Kafka Cluster, Can End-Up Holding No Partitions

### ISSUE THREAD

**Issue by steve-gray** [twmb/franz-go#204]
We had an issue recently with our Kafka cluster where it was provisioned to some nodes using `strimzi` that were over-comitted on memory, causing OOM errors and pod restarts periodically. We observed that whilst the cluster would invariably come healthy afterwards, the franz-go based driver clients we were using would end up essentially with an empty consumer group/no consumer would be holding any partitions to read from.

Adding diagnostic logging, we'd see:

- Partitions claimed - all the partitions we'd expect
- .... Partitions revoked - all of the above.

Then invariably if these happened close together, the consumer would essentially sit forever idle. Restarting the consumer process would cause the group to re-balance and distribute the partitions fairly, but it seems like __something__ is getting confused during adverse network circumstances and not trying to re-join (or maybe not "leaving" the generation after being handed no partitions?).

We're going to build a suicide timer in so that if we lose our last partition, we'll set a timer to terminate the connection if no partitions are allocated to a consumer after N seconds - but it seems like potentially a gap in the driver somewhere? Other drivers like sarama/segmentio don't seem to suffer this specific issue though.

**Comment by twmb** [comment]
What franz-go version are you using?

**Comment by twmb** [comment]
If you're not yet on 1.7.1, I'm wondering if what you're running into was fixed by 3191842a81033342e8d37a529bd0a1b3d190fd9f.

**Comment by steve-gray** [comment]
We upgraded to 1.7.1 when it came out, as we thought it might be related to that issue. However it seems that it was equally affected in this scenario. What we'd see in kubectl was all process up, however in kowl the consumers were just idle/empty group:

![image](https://user-images.githubusercontent.com/14563775/190016397-2cd888ce-6a4d-4b1b-b5c7-266d718b2899.png)

We've put some resource protection in for the ZooKeeper and Kafka nodes to prevent OOM's, and the issue hasn't recurred in the intervening time. However if there's something to look for in the goroutines/pprof let us know and I can try and laser in on that area when there's an issue next time.

**Comment by twmb** [comment]
Hrmm that's no good... if you could let it sit for a few minutes and then ctrl+\ it go get a dump of all goroutines, I'll run the goroutine trace through my undocumented but helpful https://github.com/twmb/gr and see what's hanging and try to investigate. Would that be a possibility?

**Comment by twmb** [comment]
Also, if you have logs from both the leader (i.e. what are the balancing decisions being made) and the member that has no partitions, that'd be great.

**Comment by twmb** [comment]
@steve-gray lmk if you're able to grab any goroutines, I'm particularly interested in tracking down any hung consumer problems.

**Comment by steve-gray** [comment]
Will do. Thanks for the heads up - this really hasn't happened again since we fixed the resourcing on the zookeepers/brokers, so it's going to be potentially a while before we see this again.
