### ISSUE TITLE
Community plugins

### ISSUE THREAD

**Issue by yianni** [twmb/franz-go#211]
Hello @twmb, as you may know, we are writing a opentelemetry plugin for franz-go. We are figuring out where the plugin should belong. What are your thoughts on adding the plugin to this repo?

**Comment by twmb** [comment]
+1 on adding a new plugin in `/plugin/`, the main follow up I have to do (besides reviewing & merging code) is tag the plugin :)

Do you expect the plugin to be relatively static, or are you expecting it to change frequently?

**Comment by brennan-airtime** [comment]
How about getting it into the contrib repo of the otel project?

https://github.com/open-telemetry/opentelemetry-go-contrib

**Comment by yianni** [comment]
> +1 on adding a new plugin in `/plugin/`, the main follow up I have to do (besides reviewing & merging code) is tag the plugin :)
> 
> Do you expect the plugin to be relatively static, or are you expecting it to change frequently?

We wouldn't expect the plugin to change often.

**Comment by yianni** [comment]
> How about getting it into the contrib repo of the otel project?
> 
> https://github.com/open-telemetry/opentelemetry-go-contrib

Otel team suggests the instrumentation plugin should live in:

1. Native to the instrumented package
2. A dedicated public repository
3. In the opentelemetry-go-contrib repository

If @twmb is okay with it being native, then it aligns with the top suggestion

The following documentation gives an overview [https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation#new-instrumentation]

**Comment by twmb** [comment]
lmk if there's anything to be done for this specific issue or if it can be closed -- I'm +1 on merging new plugins into `plugin/`, I can take care of the tagging and releasing

**Comment by twmb** [comment]
(closing for now--lmk if it should be reopened)
