### ISSUE TITLE
Sequence numbers wrap around when 2^31 messages have been produced

### ISSUE THREAD

**Issue by JGShaw** [twmb/franz-go#216]
When lots of messages have been produced message sequence numbers seem to wrap around to a negative number, the resulting sequence numbers are suspiciously close to -2^31 suggesting a signed 32 bit int to wrapping around. Some rough maths based on our produce rate and how long our producer was running for confirms that we would have hit around 2^31 messages produced before it started to fail. 

kgo error:
```
{"level":"error","message":"INVALID_RECORD: This record has failed the validation on broker and hence be rejected.","time":"2022-10-07T10:32:44+01:00"}
```

kafka logs error:
```
[2022-10-07 11:47:26,227] ERROR [ReplicaManager broker=1234] Error processing append operation on partition topic-2 (kafka.server.ReplicaManager)
org.apache.kafka.common.InvalidRecordException: Invalid sequence number -2147483407 in record batch with producerId 70000 in topic partition topic-2.
```

**Comment by twmb** [comment]
What franz-go version are you using? This sounds like what I fixed in v1.5.3: https://github.com/twmb/franz-go/blob/master/CHANGELOG.md#v153 (ctrl+f "wrap")

**Comment by twmb** [comment]
Also out of curiosity, how long has your producer been running to hit this? 😅

**Comment by JGShaw** [comment]
Ah I think you are right, that does sound like our issue and we are on v1.2.6, so I will close the issue and update. Many thanks 😁

It was running for around a month. We have lots of small messages so it does not take too long to reach 2^31. It has made me realise that never changed the number of partitions from the default of 3 though!

**Comment by twmb** [comment]
If you upgrade, be a bit aware of the behavior change for canceling the context passed to PollFetches that was introduced in v1.5.1: https://github.com/twmb/franz-go/blob/master/CHANGELOG.md#v151

(the commit message has a lot of details on why :|)
