### ISSUE TITLE
How can I store offset manually with enabled auto commit?

### ISSUE THREAD

**Issue by Fector** [twmb/franz-go#217]
Hello.
How can I store offset manually with enabled auto commit?
It means that I want to save offset after every processing.
I did it in confluentic lib with options `enable.auto.offset.store` = `false` and `auto.commit.interval.ms`.

**Comment by twmb** [comment]
Does `AutoCommitMarks` and `MarkCommitRecords` work for this?

**Comment by Fector** [comment]
Thank you. It works=)
I just have not found it in API.
