### ISSUE TITLE
feature: consumer option to balance partition lags

### ISSUE THREAD

**Issue by erenboz** [twmb/franz-go#222]
In one of our use-cases we had significantly different production/consumption rate on different partitions and ended up writing a logic of pausing unpausing fetched partitions to balance lag. It would be quite handy to add a consumer option to influence how many records pulled from each partitions or directly option to pull proportionately to the lag.

**Comment by twmb** [comment]
@erenboz that really isn't a thing that belongs in a client. A single client doesn't know anything about lag -- lag is a calculation that is determined from a few individual requests. It isn't up to a client itself to determine its own lag. Manual pausing & unpausing is the best path forward for your problem.

For the "how many records pulled from each partition" problem, I tried designing something like this in the past in https://github.com/twmb/franz-go/issues/55#issuecomment-897125512. In short, though, it doesn't really make sense and would be pretty difficult to implement. Fetches behind the scenes are per broker. Even if you only drain partition A from the fetch, other partitions will remain in the fetch buffered within the client. The client cannot request another fetch for a broker until the entirety of its current buffered fetch is drained.

There could be some weird hacky option that allows you to control _which_ partitions actually get issued in a request: the client could build candidate partitions, then your function could return partitions to actually issue in the request. I'm not sure this is a great idea ... but it could be feasible if a good API exists. What do you think?

**Comment by yuzhichang** [comment]
@twmb From Kafka code [here](https://github.com/apache/kafka/blob/2b8aff58b575c199ee8372e5689420c9d77357a5/clients/src/main/resources/common/message/FetchResponse.json#L66), the client know the lag of every partitions, and has the chance to adjust preference(proportionately, or large lag)?

**Comment by twmb** [comment]
My mistake, you're right, the client is given that information. I never historically used that field because the client hasn't needed to know lag. I'll try to think of some method of calculating how to prefer lag while also avoiding partition starvation.

**Comment by twmb** [comment]
PR #251 should close this, feel free to take a look / check it out if you want before it is merged for release 1.10

**Comment by erenboz** [comment]
@twmb @yuzhichang Oh I'm very late to the party cause I completely missed the mention notification. The solution looks great solving many similar issues. Thanks a lot.
