### ISSUE TITLE
Question: kadm.CalculateGroupLag documentation is very confusing on how to get the inputs

### ISSUE THREAD

**Issue by kklipsch** [twmb/franz-go#228]
https://github.com/twmb/franz-go/blob/master/pkg/kadm/groups.go#L1050-L1054

- I don't think the function FetchOffsets has the signature expected in that comment
- Its not obvious how to get the middle parameter 'commit OffsetResponse'

Perhaps an actual example test would make it more clear?

**Comment by kklipsch** [comment]
FetchManyOffsets returns FetchOffsetsResponse seems to have CommittedPartitions function on its signature but doesn't meet OffsetResponse signature.

**Comment by twmb** [comment]
Example here: https://github.com/redpanda-data/redpanda/blob/b4232edad290078fb9b204af40a0a2834c484b44/src/go/rpk/pkg/cli/cmd/group/describe.go#L50-L78
I'll update the docs

**Comment by kklipsch** [comment]
Perfect thank you.
