### ISSUE TITLE
Add support for go-logr 

### ISSUE THREAD

**Issue by rmb938** [twmb/franz-go#237]
Would be nice to have a plugin that supports https://github.com/go-logr/logr so it can be used with `kgo.WithLogger`

**Comment by twmb** [comment]
I'd be open to have this in a plugin at /plugin/klogr perhaps. Writing logger plugins is pretty small, if you want to take a stab (otherwise, I'm not sure where _this_ particular issue falls on my priority list 😅).

**Comment by rmb938** [comment]
Sounds good. And yea myself or one of my co-workers will contribute within the next few weeks if you don't get to it first :)

**Comment by twmb** [comment]
Is #356 what you're thinking?

**Comment by rmb938** [comment]
Yup that is perfect
