### ISSUE TITLE
[Question] PollFetch Error Handling

### ISSUE THREAD

**Issue by sbkoo9** [twmb/franz-go#25]
While writing a cooperative consumer, I read in the doc that all FetchErrors should be inspected prior to iterating records. I'm wondering what'd be the best course of action to handle retriable & non-retriable errors respectively from consumer side.

My current implementation simply ignores any records from partitions that returned errors, and retries `PollFetch()` later on, hoping that the next `PollFetch()` will return records from subscribed partitions (assuming all broker & network errors are fixed).

Is it safe to assume that retrying `PollFetch()` will return records from partitions that returned either retriable or non-retriable errors?

For a bit of context, this is how my consumer loop currently works:
1. Calls `PollFetch()`
2. Loop `Fetches.Errors()` and build a map of `map[topic][partition] = error`
3. For each `Record`, checks if the record's topic & partition exists in the map from step 2.
    * If true, skip the record
    * If false, process the record and commit offset
4. Repeat

**Comment by twmb** [comment]
The client internally retries the retriable errors and does not bubble those up. There are a few potential errors that can be returned from a poll, all of which the client can't handle and essentially unrecoverable:

- not authorized
- unsupported compression (you should not receive this)
- unsupported message version (you should also not receive this
- unknown error

I think in these cases, the partition is repeatedly fetched, so these errors should crop up continuously.

If the partition requires loading offsets or listing the broker epoch (for data loss detection), if these fail with non-retriable errors (auth), the client does not try fetching the partition again.

It's an oversight at the moment to continue retrying on auth failures in the fetch response itself.

---

For step 2, the records should always be processed -- any successfully processed record in the client advances the client's offset. So, skipping records is not necessary and could actually lead to missed records.

Primarily, you should not get any errors from `PollFetches`, so any that you do receive should be investigated.

**Comment by sbkoo9** [comment]
@twmb Thanks for clarification. It sounds like the only errors that the consumer will get are non-retriable errors, and there isn't much consumer can do do other than logging the errors and manually intervening.

**Comment by twmb** [comment]
Yep that's the goal!

Here is the place where errors are inspected when consuming records, note that only the default case does not clear the error, all other cases are for retriable errors and the client clears the error: https://github.com/twmb/franz-go/blob/8178f2cc5883304d409f653ff7e5d42163cf3e8e/pkg/kgo/source.go#L673-L752

This is the place where ListOffsets or OffsetForLeader epoch can have a fatal error: https://github.com/twmb/franz-go/blob/8178f2cc5883304d409f653ff7e5d42163cf3e8e/pkg/kgo/consumer.go#L893-L907. Here, if data loss is detected, an error is injected but the partition continues to be used. Only non-retriable errors stop using the partition.

As mentioned in my prior comment, I'm going to address the source.go code to _stop_ using a partition if there is an auth error, and I'll also add a configuration option to force continuing to use the partition on auth errors (and make the list offsets non-retriable error behave the same as the source.go error).

**Comment by sbkoo9** [comment]
Thanks. I'll reopen the issue if I have any further question regarding this.

**Comment by twmb** [comment]
I'm going to reopen this issue to keep track of this open inconsistency; I plan to address this soon. There's a need to handle the client retrying on auth failure, allowing an operator to start a client before it is authorized, or to rotate credentials.

**Comment by twmb** [comment]
I closed this with the most recent commit (which will be in the next tagged release in a week or so-ish). The new behavior continues to retry loading a partition's offset or epoch even in the face of non-retriable errors: we will back off 1s and retry, rather than permanently failing the partition.
