### ISSUE TITLE
Add support for querying consumer group coordinator id in DescribeGroupsResponseGroup

### ISSUE THREAD

**Issue by amuraru** [twmb/franz-go#28]
Kafka `kafka-consumer-groups --describe` supports getting the cg coordinator id:

```
GROUP                                               COORDINATOR (ID)          ASSIGNMENT-STRATEGY  STATE           #MEMBERS
p-xp-writer-prod                        kafka-101:9206 (206) range                Stable
```

It would be really useful to get this when using franz-go as well

**Comment by twmb** [comment]
Hello!

That struct reflects the definition of the DescribeGroupsResponse, and the coordinator is not a part of that struct.

The Java client first issues a FindCoordinator per group and then uses the coordinator returned along with the information from a DescribeGroups request to print the output you posted. The kgo client does something similar, and the coordinator ID requests were issued to is available as the in the Meta.NodeID in response shards if using `RequestSharded`. 

Is it possible to use `RequestSharded`?

**Comment by amuraru** [comment]
Thanks @twmb - will give that a try

**Comment by twmb** [comment]
Cool! Let me know if that works. I'm going to close this issue but please reopen it if that does not resolve things.
