### ISSUE TITLE
support for updating replicationFactor?

### ISSUE THREAD

**Issue by dseapy** [twmb/franz-go#284]
I can see how to update the partitions and configs for a topic, is there a way to update the number of replicas for each partition?

I think maybe kadm's `AlterPartitionAssignments` and `ListPartitionReassignments` are maybe what I want to use?

**Comment by twmb** [comment]
Altering RF is a pretty advanced sequence of operations that I've never done myself. It's also different on different systems (i.e. Kafka and Redpanda do it differently).

https://stackoverflow.com/questions/37960767/how-to-change-the-number-of-replicas-of-a-kafka-topic

I'm not sure if it makes sense to add to kadm.

**Comment by dseapy** [comment]
Cool, makes sense.  Just making sure I wasn't missing anything.  Thanks!
