### ISSUE TITLE
Is it possible to update the kgo.ConsumeTopics option during the running of a kgo client?

### ISSUE THREAD

**Issue by moming00** [twmb/franz-go#291]
hello, in my case multiple tasks are sharing one kgo client to prevent much stress on kafka server, different task may correspond to different topic. In the case certain task run into fatal, to prevent stopping the whole process, is that possible I just remove the corresponding topic from the kgo client topics without restart a new client?

**Comment by twmb** [comment]
Two options:
* PurgeTopicsFromClient removes a topic completely, it will no longer be consumed (and it removes any metadata that exists for producing)
* AddConsumeTopics adds topics

**Comment by moming00** [comment]
hello @twmb , calling AddConsumeTopics is not working for me because of `"msg":"metadata update triggered","why":"re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_r72}"}`, could you help confirm if this is the case? BTW, I'm using the latest release v1.10.4.

**Comment by moming00** [comment]
hello @twmb , calling AddConsumeTopics is not working for me because of "msg":"metadata update triggered","why":"re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_r72}"}, could you help confirm if this is the case? BTW, I'm using the latest release v1.10.4.

**Comment by moming00** [comment]
my fault, something cannot be reproduced. It works fine now, will open an issue when get enough log.
