### ISSUE TITLE
kadm create topic always fails

### ISSUE THREAD

**Issue by bnkamalesh** [twmb/franz-go#292]
First off, thanks for the awesome library!

I found this issue, when I was quickly *scripting* a tool to create topic from within my "Go Docker container". 

Here's the Go code: https://go.dev/play/p/AD8dpg6A363

And here's the error I'm facing:
```
KAFKA_SEEDS=127.0.0.1:9092 go run main.go my_topic1 my_topic2
New topics to be created: [my_topic1 my_topic2]
2022/12/16 16:07:38 topic creation failed: unable to dial: dial tcp: lookup kafka: no such host
exit status 1
```

Fetching metadata of the topic works fine, but create topic fails. I'm **_assuming_** there's some hardcoded host address within the code (I haven't gotten the time to check code yet).

**Comment by twmb** [comment]
What's your advertised addresses on the brokers? It sounds like they are different from the address that is accessible externally.

**Comment by twmb** [comment]
CreateTopics under the hood just goes to the controller broker, which is a number corresponding to one of the brokers returned in the Metadata response. What does the BrokerMetadata in your code return?

**Comment by bnkamalesh** [comment]
> {Rn4K4us9SHK5RM99pSiodQ 1001 [{1001 9092 kafka <nil> {}}] map[]}
JSON for readability
>  {"Cluster":"Rn4K4us9SHK5RM99pSiodQ","Controller":1001,"Brokers":[{"NodeID":1001,"Port":9092,"Host":"kafka","Rack":null}],"Topics":{}}

aah interesting, it's returning "kafka" 🤦

**Comment by twmb** [comment]
Let me know if there's some other issue that may point to the client, but so far it looks like a container / flag / setup issue (although I'm not sure how consuming and producing could be working) -- closing for now
