### ISSUE TITLE
CLUSTER_AUTHORIZATION_FAILED 

### ISSUE THREAD

**Issue by houmanka** [twmb/franz-go#293]
```
	tlsConfig, err := NewTLSConfig(KafkaSSLCertLocation, KafkaSSLKeystoreLocation, KafkaSSLCALocation)
	opts := []kgo.Opt{
		kgo.SeedBrokers(broker),
		kgo.DialTLSConfig(tlsConfig),
		kgo.ProducerBatchMaxBytes(1000000),
	}
	cl, err := kgo.NewClient(opts...)
	defer cl.Close()
```
TLS Config:
```
func NewTLSConfig(clientCertFile, clientKeyFile, caCertFile string) (*tls.Config, error) {
	tlsConfig := tls.Config{}
	// Load client cert
	cert, err := tls.LoadX509KeyPair(clientCertFile, clientKeyFile)
	if err != nil {
		return &tlsConfig, err
	}
	tlsConfig.Certificates = []tls.Certificate{cert}
	// Load CA cert
	caCert, err := ioutil.ReadFile(caCertFile)
	if err != nil {
		return &tlsConfig, err
	}
	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caCert)
	tlsConfig.RootCAs = caCertPool
	tlsConfig.BuildNameToCertificate()
	return &tlsConfig, err
}
```
When I use kafka-go lib I can push into Kafka byt with franz-go I get:
`panic: could not write message CLUSTER_AUTHORIZATION_FAILED: Cluster authorization failed.`

Can you please let me know what I am doing wrong???
Am I missing any other settings?
Thanks

**Comment by twmb** [comment]
Looks like your cluster requires SASL, and it doesn't look like you're using any SASL options when initializing a client?

**Comment by houmanka** [comment]
I had permission issue. I asked the Ops to sort it out for me. It worked by adding `kgo.DisableIdempotentWrite()`
thanks for your response

**Comment by twmb** [comment]
Idempotent production is a pretty big win, you might want to ask them to add IDEMPOTENT_WRITE on CLUSTER for kafka-cluster for your SASL user.

Alternatively, Kafka v3.0+ does not need that permission anymore.
