### ISSUE TITLE
Simpler function for creating a single topic in admin client

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#297]
**Problem**

Creating a single topic is possibly one of the most popular functions used in the franz-go admin client. Currently there's only a function for creating multiple topics with the same configuration which may be handy. However, if you only want to create one topic and check if that was successful the required error checking remind me of using the `kmsg` package. I don't like the fact that I have to check for an error at multiple places to figure out whether my operation was successful or not:

```go
		createTopicResponses, err := k.admCl.CreateTopics(
			ctx,
			1,
			1,
			map[string]*string{
				"cleanup.policy": kadm.StringPtr("compact"),
				"segment.bytes":  kadm.StringPtr("8388608"), // 8 MiB
			},
			k.cfg.kafkaTopicName,
		)
		if err != nil {
			return fmt.Errorf("failed to create topic: %w", err)
		}

		topicResponse, exists := createTopicResponses[k.cfg.kafkaTopicName]
		if !exists {
			return fmt.Errorf("no topic response for the requested topic creation request")
		}
		if topicResponse.Err != nil {
			return fmt.Errorf("failed to create topic: %w", err)
		}
```

**Proposal:**

I think there should be an API that offers the creation of a single topic:

```go
// CreateTopic issues a create topics request with the given partitions,
// replication factor, and (optional) configs for the given topic name. Under the hood,
// this uses the default 15s request timeout and lets Kafka choose where to
// place partitions.
//
// This package includes a StringPtr function to aid in building config values.
//
// If the topic could not be created this function will return an error. An error may be returned
// due to authorization failure, a failed network request, a missing controller or other issues.
func (cl *Client) CreateTopic(
	ctx context.Context,
	partitions int32,
	replicationFactor int16,
	configs map[string]*string,
        topic string) (CreateTopicResponse, error) {}
```

**Note:** While this looks very similar to the `CreateTopics` API - just for a single topic - the error handling here is more opinionated as errors reported on the Kafka API (for each individual topic) will also be returned as plain errors. This does not make sense for the `CreateTopics` method as partial failure/success may be an option. To make this difference clearer one could also consider naming this `CreateTopicSimple()`

**Comment by twmb** [comment]
I think CreateTopic is common enough to have a dedicated function, but there's also going to be generics to extract one element from any response: https://github.com/twmb/franz-go/pull/279
