### ISSUE TITLE
How can I set the offset while rebalancing?

### ISSUE THREAD

**Issue by NghiaHa-97** [twmb/franz-go#309]
If Kafka is shut down but the consumer is still running, then after restarting Kafka, the consumer takes the location of "reset.offset." and the message is lost.

**Comment by NghiaHa-97** [comment]
Thank you. I found a solution with the function AdjustFetchOffsetsFn.

**Comment by twmb** [comment]
@NghiaHa-97 the consumer should be committing before shutdown, so that once the consumer restarts, the consumer will restart from the last committed offset. Are you not seeing this?
