### ISSUE TITLE
Subscritpion does not seem to be working

### ISSUE THREAD

**Issue by bnkamalesh** [twmb/franz-go#321]
Hello,

I have setup a repository with docker compose file to show what's going on. Hopefully it's easier + you have the time to check.

https://github.com/bnkamalesh/kafkacheck

Most of the admin(kadm) functions seem to work as expected, the app is even able to create the topic on Kafka, which would mean there's no connectivity issues. But the subscription doesn't work.

**Comment by bnkamaleshwar** [comment]
I found the issue by adding a logger with `kgo.BasicLogger()` and it logged the following error:

> kafkacheck-application-1  | [ERROR] join and sync loop errored; group: kafkacheck, err: INVALID_SESSION_TIMEOUT: The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms)., consecutive_errors: 34, backoff: 2.5s

Finally, I've been at this for like 2 days. Wouldn't it make sense for Pollfetches to return error since it's not retriable? Because the SessionTimeout configuration says:

> SessionTimeout sets how long a member in the group can go between heartbeats, overriding the default 45,000ms. If a member does not heartbeat in this timeout, the broker will remove the member from the group and initiate a rebalance.

**Comment by bnkamalesh** [comment]
I found the issue by adding a logger with kgo.BasicLogger() and it logged the following error:

> kafkacheck-application-1 | [ERROR] join and sync loop errored; group: kafkacheck, err: INVALID_SESSION_TIMEOUT: The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms)., consecutive_errors: 34, backoff: 2.5s

Finally! I've been at this for like 2 days. Wouldn't it make sense for Pollfetches to return error since it's not retriable? Because the SessionTimeout configuration says:

> SessionTimeout sets how long a member in the group can go between heartbeats, overriding the default 45,000ms. If a member does not heartbeat in this timeout, the broker will remove the member from the group and initiate a rebalance.

**Comment by twmb** [comment]
@bnkamalesh the main problem with trying to return this error through `PollXyz` is that this error is separate from and independent of the record polling logic. The error might happen once a minute, where you might be polling once a second. Should the code internally repeat the error 60 times, one for every poll, until the error itself resolves?

Instead I took a different approach -- arguably, it's probably worse, and it's definitely less discoverable -- where you can provide a `HookGroupManageError` to hook into these group rebalancing errors.

I'm not 100% convinced on repeatedly returning an error from Poll until an issue is resolved, but it is a pretty decent way of addressing confusing / problems. I think I'd be a bit more convinced if there's a bit more evidence on this type of API change being needed.

**Comment by bnkamalesh** [comment]
@twmb I agree with not returning _unrecoverable_ error. In this case, no matter how many times you retry it's not possible to recover, right? And it seems to have identified the error type accurately as well (INVALID_SESSION_TIMEOUT), so there's no assumptions going on either. Would it still not make sense to return the error, or would an error type check in pollfetch cause significant performance hit?

**Comment by twmb** [comment]
I'll start injecting group errors into polling just once in the next release with this PR: https://github.com/twmb/franz-go/pull/387
