### ISSUE TITLE
Question: How to produce in batches?

### ISSUE THREAD

**Issue by ErlendFax** [twmb/franz-go#322]
The examples in the README show that it's possible to produce in batches, but I don't really understand how to do it.

I'm trying to rewrite a kafka-go program and I want to replace this line: `err := k.writer.WriteMessages(ctx, k.buffer...)`, where `k.buffer` is a list of records. 

What would the equivalent be?

**Comment by vtolstov** [comment]
simply publish messages. batch forms based on passed client params - batch max size and wait time to send.

**Comment by ErlendFax** [comment]
Thanks, so something like this?

```golang
list := []*kgo.Record{{Topic: "foo", Value: []byte("bar")}, {Topic: "foo", Value: []byte("bar")}}
for _, r := range list {
    client.ProduceSync(ctx, r)
}
```

**Comment by vtolstov** [comment]
dont forget to add options to client:
ProducerBatchMaxBytes
ProducerLinger if needed

**Comment by ErlendFax** [comment]
Thank you! I'm assuming it handles concurrency and that I really can't do anything wrong.

**Comment by twmb** [comment]
@ErlendFax I wouldn't recommend using ProduceSync unless there's a reason you want sync producing. The client internally batches -- if you produce 50 times immediately, those 50 messages will probably be in the same batch. If you produce 50 messages over 10s, then the client will send records as fast as possible and probably split these into a bunch of small batches.

**Comment by ErlendFax** [comment]
This program will pass on our IoT data to a queue, a few thousand messages each second, with ACK enabled. May be helpful for understanding our case.

So just be sure, switching to `Produce` will be correct?

```golang
list := []*kgo.Record{{Topic: "foo", Value: []byte("bar")}, {Topic: "foo", Value: []byte("bar")}} // long array
for _, r := range list {
    client.Produce(ctx, r, func(r *kgo.Record, err error) {
        if err != nil {
            fmt.Printf("record had a produce error: %v\n", err)
        }
    })
}
```

**Comment by twmb** [comment]
if you are _just_ producing two, and you want to wait, you can use ProduceSync there.

Otherwise, use a wait group to ensure all the records are produced or errored before shutting down

**Comment by artemklevtsov** [comment]
I used the following snippet. `p.Err()` calls `wg.Wait` underhood.
```go
	var batchSize int16 = 0
	var naxBatchSize int16 = 50
	p := kgo.AbortingFirstErrPromise(kafkaClient)
	for rows.Next() {
		batchSize++
		var buf []byte
		if err := rows.Scan(&buf); err != nil {
			panic(err)
		}
		record := &kgo.Record{Value: buf}
		kafkaClient.Produce(ctx, record, p.Promise())
		if batchSize >= maxBatchSize {
			// wait to send batch
			if err := p.Err(); err != nil {
				panic(err)
			}
			batchSize = 0
		}
	}
	// wait to send last batch
	if err := p.Err(); err != nil {
		panic(err)
	}
```

**Comment by twmb** [comment]
I'd worry less about trying to build batch sizes from the end-user side -- the client actually can send batches before you reach your own tracked `batchSize`. If you _absolutely_ want to control batching, you can use the `ManualFlushing` option.

**Comment by ErlendFax** [comment]
Thanks. But, what happens internally in franz-go if producing fails, e.g. during an upgrade of broker cluster? Would messages be kept in memory until the connection is back up and writing?


I swapped out the old lib with franz-go and kept most of the other stuff in the program. I probably _should_ have done this from the ground up, but it was quicker this way. Ended up just doing this: `result := k.writer.ProduceSync(ctx, messages...)`

We have an in-memory queue of MQTT messages that is constantly filled. Program used to take batches from this queue and feed them to Kafka producer. I just kept it that way. I guess it was done to make sure all messages were produced and kept in this memory queue until it was produced and ACKed. But if franz-go can do this using `Produce`thats great!

**Comment by artemklevtsov** [comment]
@twmb thank for the explanation.

So my code should be like this:
```go
p := kgo.AbortingFirstErrPromise(kafkaClient)
for rows.Next() {
	var buf []byte
	if err := rows.Scan(&buf); err != nil {
		panic(err)
	}
	record := &kgo.Record{Value: buf}
	kafkaClient.Produce(ctx, record, p.Promise())
}
if err := p.Err(); err != nil {
	panic(err)
}
```
`ProduceSync` is very slow in my case. I tried to speed up it.

**Comment by twmb** [comment]
> Thanks. But, what happens internally in franz-go if producing fails, e.g. during an upgrade of broker cluster? Would messages be kept in memory until the connection is back up and writing?

The client buffers messages until they are able to be sent, unless you override settings with retries, delivery timeout, etc.

ProduceSync forces a serialization point, such that it will not return until all messages are flushed. For higher throughput, you can produce messages individually and trust the client to buffer, batch, and send them, and then you hook into the promise to be called when they are finally delivered. The client always attempts to send things ASAP.
