### ISSUE TITLE
Can not parse records with large timestampDelta

### ISSUE THREAD

**Issue by tfriedrichs** [twmb/franz-go#324]
Hey,

after a while of using this great library we noticed that some of our consumers were occasionally missing messages. Some investigation shows that this seems to be related to record batches which contain TimestampDeltas that are too large for the 5 bytes that the current varint allows. 

The Kafka message spec appears to allow varlong (up to 10 bytes) here: https://kafka.apache.org/33/documentation.html#record

Example of a record that should be parsable:
```go
func TestLargeTimestampDelta(t *testing.T) {
	data := []byte{
		0x34, 0x00, 0xF0, 0xE7, 0xF7, 0xDD, 0x5B, 0x06, 0x0E, 0x74, 0x65, 0x73,
		0x74, 0x4B, 0x65, 0x79, 0x12, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6C,
		0x75, 0x65,
	}
	r := &kmsg.Record{}
	err := r.ReadFrom(data)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by twmb** [comment]
I used that same documentation while writing this library, as it turns out, the documentation was incorrect when I wrote this in 2019:

https://github.com/apache/kafka/commit/94ccd4d

This looks to be yet another instance where Kafka documentation was different from implementation.

**Comment by twmb** [comment]
I can fix this this evening. Out of curiosity, how are you generating timestamps with such as significant delta? A varint itself allows up to 24 day deltas from the first timestamp.

**Comment by tfriedrichs** [comment]
Thanks.
We hit the problem on a compacted topic that is only sporadically written to. If I remember correctly the compaction cleaner also messes with the batch timestamps, so I think that might be the cause in our case.

**Comment by twmb** [comment]
This should be fixed in v1.11.4; it required a major version bump to pkg/kmsg.

**Comment by twmb** [comment]
Actually I am going to retract v1.11.4, this technically is a breaking change in kgo as well.

**Comment by twmb** [comment]
This is done better in v1.11.5 in a backwards compatible way.
