### ISSUE TITLE
Question: Whats the expected behaviour of Producer when abruptly losing connection?

### ISSUE THREAD

**Issue by ErlendFax** [twmb/franz-go#336]
We did some testing using `Produce` while _deleting_ our Redpanda Cluster with three nodes. This might not be a realistic case but I got curious if the following outcome could happen in other ways, e.g. slow rolling broker upgrades. etc.

Our franz-go routine listens to a channel that's constantly receiving new messages to handle (~500 sec). When receiving a message it's sent directly to `Produce`:

```golang
for {
    select {
    case <-ctx.Done():
	    k.logger.Info("Context cancelled")
	    break loop
    case <-ticker.C:
	    k.logger.Info("Current status: RUNNING. Buffer length: ", k.client.BufferedProduceRecords(), ". Channel length: ", len(k.C))
    case m := <-k.C:
	    k.logger.Trace("Kafka routine received MQTT message from channel")
	    record := parse(m)
    
	    k.client.Produce(ctx, &record, func(_ *kgo.Record, err error) {
		    if err != nil {
			    log.Error("Error producing!")
		    }
	    })
	    k.logger.Trace("Message was added to producer. Length internal buffer: ", k.client.BufferedProduceRecords(), ", Length channel: ", len(k.C))
    
    }
	}
```

When left alone this runs fine, so that's good. 

We then delete the cluster, and the client loose connection and tries to reconnect as expected. During this, I log with a 500ms interval the `BufferedProduceRecords` (see snippet above). Buffered messages increase since the connection is lost, as expected, but when all three nodes are gone the interval stops... which means we are stuck in the`Producer` somewhere, does this makes sense? Wouldn't think so but, Idk.

**So is failing buffering expected when the connection is abruptly lost?** 

[downloaded-logs-20230131-142923.csv](https://github.com/twmb/franz-go/files/10546801/downloaded-logs-20230131-142923.csv)

**Comment by ErlendFax** [comment]
Just after posting this, I found out that the MaxBufferedRecords was sat really low... which might have caused the stop ... Didn't find any ErrMaxBuffered in the logs though but I'm sure this was my fault. Sorry!

**Comment by twmb** [comment]
The client blocks Produce when MaxBufferedRecords is hit -- if you instead want the client to fail additional records, you can use TryProduce

that might help
