### ISSUE TITLE
Transactional example not working on latest version

### ISSUE THREAD

**Issue by g-freire** [twmb/franz-go#34]
Transactional example seems not to be working on the latest  v0.6.14 release
When downgrading to v0.6.0 it works

**Comment by twmb** [comment]
Hi there,

I just created a topic `test` and ran `go run .` in the examples directory on v0.6.14, and it works from me.

What's the output when you add `kgo.WithLogger(kgo.BasicLogger(os.Stderr, LogLevelDebug, nil))` to the options passed to both invocations of `NewClient`?

**Comment by g-freire** [comment]
Hi @twmb , I think I got the problem. 

In fact it's running. 
What happened is that my kafka brokers was not auto creating the topics (kafka 2.7.0) and with the v0.6.14 the error was not raised, while with the v0.6.0 the exception was clear, than I manually created the topic and all worked. So at the end was the error explanation from the previous version that got it working, and not a problem with the lastest one :)  

With latest version the error was not explicit
<img width="330" alt="Franz1" src="https://user-images.githubusercontent.com/25310481/116287399-bd568980-a766-11eb-9dac-546959f2efc1.png">


With  version 6.0.0 the error is explicit
<img width="365" alt="franz2" src="https://user-images.githubusercontent.com/25310481/116287423-c5162e00-a766-11eb-95d0-2da0a5542b55.png">

Anyway, thanks for the fast response.

**Comment by g-freire** [comment]
Adding the logger made  it clear on the latest version

<img width="529" alt="logger" src="https://user-images.githubusercontent.com/25310481/116289203-ab75e600-a768-11eb-928e-c86881acacf7.png">

<img width="1021" alt="debug" src="https://user-images.githubusercontent.com/25310481/116289433-de1fde80-a768-11eb-8280-35317fdf5ae7.png">

**Comment by twmb** [comment]
Ah yep cool, so v0.6.0 actually had a bug that never retried if discovering the topic failed -- I recently fixed that, which means that when the topic does not exist, the client now retries (refresh metadata, does it exist? no, retry, and so on). The default retries is unlimited, so this would look like the client has hung / is not working.

Glad it's fixed! :)
