### ISSUE TITLE
kadm: Helper function to iterate over all partitions returned by kadm.Metadata

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#342]
If I want to iterate over all reported partitions of kadm.Metadata(ctx), I'd need to write the following boilerplate code:

```go
	for _, t := range metadata.Topics {
		if t.Err != nil {
			continue
		}
		for _, p := range t.Partitions {
			if p.Err != nil {
				continue
			}
		}
	}
```

Would be nice to have an `EachPartitionFn(p PartitionDetails, err error)`. If there's a partition error it will be set in the second param. If the topic itself could not be fetched (e.g. authorization) the function will not be called at all for this specific topic. 

Similarly an `EachTopicFn(t TopicDetails, err error)` would be nice to have.

**Comment by weeco** [comment]
Would almost always be helpful for topic/partitions maps are returned. For example in `kadm.DescribeAllLogDirs` too

**Comment by twmb** [comment]
This exists?
```
func (ds TopicDetails) EachPartition(fn func(PartitionDetail))
```
You still need to check the partition error

EachError also exists, but EachTopic does not. 

Each also exists for DescribedLogDirs, but it's not fully broken into partitions. Could be a few more helpers there.

**Comment by weeco** [comment]
I don't know how I've missed these. That's great. I'll close this issue, but I'll consider adding more helper functions which I regularly need. Super helpful to reduce the boilerplate code and make my own code more maintainable.
