### ISSUE TITLE
kadm: Support both incremental and normal alter topic configs

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#352]
Currently the kadm client supports `AlterTopicConfigs` which is incremental altering. It mentions that the original AlterConfigs request is not supported, because it would remove existing dynamic configurations that are not specified in the alter request. However, this behaviour is exactly what you'd want to have when enforcing a set of given configurations (e.g. topic reconciler).

@twmb I can add a second method, but I'm unsure how to name this and whether we want to change the original name `AlterTopicConfigs` to e.g. `AlterTopicConfigsIncrementally`

**Comment by twmb** [comment]
A topic reconciler cannot know secret values, meaning they will always be stripped. How would you approach that?

**Comment by weeco** [comment]
What secret values would exists as a dynamic topic config? A topic reconciler such as Terraform would have this secret value stored in the Terraform state - if it had been set as part of the Terraform resource of course.

**Comment by twmb** [comment]
Not sure, I don't know all configuration. Since the protocol does not return secret values, Terraform cannot compare what is stored in the broker to what the final state we want the resource to be. How is this done today for other providers? Are configurations just always updated, or do we trust configurations don't have secret values?

**Comment by twmb** [comment]
I'd be ok with a new set of functions:

```go
// AlterTopicConfigsState changes the entire state of a topic configuration.
// All previous configuration is removed, and all new configs are set.
// The Op field on any configuration is ignored (it is always set).
// Unlike AlterTopicConfigs, this is not an incremental operation.
func (*Client) AlterTopicConfigsState(context.Context, configs []AlterConfig, brokers ...int32) (AlterConfigsResponses, error)

// similar docs for the next three
func (*Client) ValidateAlterTopicConfigsState(context.Context, configs []AlterConfig, brokers ...int32) (AlterConfigsResponses, error)
func (*Client) AlterBrokerConfigsState(context.Context, configs []AlterConfig, brokers ...int32) (AlterConfigsResponses, error)
func (*Client) ValidateAlterBrokerConfigsState(context.Context, configs []AlterConfig, brokers ...int32) (AlterConfigsResponses, error)
```
