### ISSUE TITLE
kotel: error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by brennan-airtime** [twmb/franz-go#364]
With the kotel tracing plugin enabled, try producing a record where the record contains an invalid utf-8 sequence. It ends up dropping the span.

```
client.ProduceSync(ctx, &kgo.Record{
	Key:   []byte{0xe2, 0x28, 0xa1},
	Value: []byte{},
	Topic: topic,
})

traces export: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```

I'm happy to submit patches, just making the issue known.

**Comment by twmb** [comment]
Yes it was known on the original issue ;) https://github.com/twmb/franz-go/pull/294#issuecomment-1416350683

I think this can be resolved with one or two options:

```go
// EscapedUTF8 replaces any invalid UTF-8 with the UTF-8 replacement character
// (more doc on why)
func EscapedUTF8() TracerOpt
// StrictUTF8 drops any tracing span that contains invalid UTF-8 (more doc why)
func StrictUTF8() TracerOpt
```

**Comment by twmb** [comment]
Actually, I think we should just always check `utf.ValidString` and, if not valid, always do the replacing. The options are more confusion.

**Comment by brennan-airtime** [comment]
I'm not sure using the replacement character is advised. Some keys are just straight binary.

Maybe if not valid `utf-8` use some reasonable text encoding base64, hex, w/e so a user can reverse it?

**Comment by twmb** [comment]
That feels like something that might rather be option driven, `HexEscapeKeys` or something. I'd expect that a person using otel would also only use keys that are valid in open telemetry, rather than trying to directly log binary data in a utf8 text field. Is that not the case?

**Comment by brennan-airtime** [comment]
I don't think that is the case at all.

I may want to use otel but I use protobufs or avro binary formats for my keys+values.

**Comment by twmb** [comment]
Given that documentation, there is no clear canonical string form of a binary key, and we should just drop it. That seems to me that the default behavior should be:
* _either_ drop keys with invalid utf-8 by default, or use the utf-8 replacement character
* add KeyEscaping(how KeyEscapeHow) option
* Add HexEscape, HexEscapeInvalid, Utf8InvalidCharReplace options
?

**Comment by brennan-airtime** [comment]
I agree with drop if invalid on default. If absolutely necessary someone could take the topic+partition+offset info and go lookup the key in question.

For protobuf and avro there do exist canonical json representations that would meet the needs of the `MessagingKafkaMessageKeyKey` documentation (just as an example).

I think its good to provide an option to let users decide how they want to encode things if they need to but I don't think its necessary to have to carry around a bunch of different implementations.

In other otel libs like the http or sql libs I find myself customizing the spans based on the things they are instrumenting and having the options that let me customize it is great and they don't need to anticipate my wonky needs ahead of time, they just give me control in the places I need it.

So I wouldn't even phrase it like `KeyEscaping`, I think `KeyFormatter` would be better. I could pass an implementation that turns all my protobufs into their json forms, or just does hex escaping. You don't need to know or care.

**Comment by twmb** [comment]
```go
// KeyFormatter specifies a formatting function to run on record keys before
// adding them to a span's attributes. This can be used to escape invalid
// utf-8 (if your keys may not be strictly text) or apply hex escaping, protobuf
// unmarshalling, etc.
func KeyFormatter(func([]byte) ([]byte, error))

// Utf8Formatter is a KeyFormatter that replaces all invalid UTF-8
// characters with utf8.RuneError, the UTF-8 replacement character.
func Utf8Formatter(key []byte) ([]byte, error) {
  if utf8.Valid(key) {
    return key
  }
  ...
}
```
Good idea on KeyFormatter.

So,
* Drop invalid by default
* Support KeyFormatter
* Provide Utf8Formatter as a drop in replacement character fix

**Comment by twmb** [comment]
Let me know if you'd like to get to this today, otherwise I'll push a PR anytime between 2 hours from now and when I go to bed -- I think we're in agreement on how to proceed.

**Comment by brennan-airtime** [comment]
I can't pick it up til Monday, but I am willing to do it.

I wonder if `KeyFormatter` may need some additional context like the topic the thing is on? Maybe even passing the entire record?

**Comment by twmb** [comment]
Monday works -- I was aiming to close all issues today / tag a new release, but the plugin can be released separately.

I worry a bit about the whole record being overkill, do you anticipate much of a use for the other fields? Overall, it should be ok, though.

```
KeyFormatter(func(*kgo.Record) ([]byte, error)
```
If any error is returned, the key is not added as an attribute. Either way, both solutions are ok to me.

**Comment by brennan-airtime** [comment]
I could see key, topic, headers, and context being useful.

If using the schema registry topic + first few bytes of the key should be enough to figure out what the key type is.

context could be useful if I'm being cheeky and smuggling some extra information in it for the key formatter to use.

Headers if there is some identifying information being sent.

**Comment by brennan-airtime** [comment]
Sorry something came up today.

**Comment by brennan-airtime** [comment]
And more things came up. Sorry.

**Comment by yianni** [comment]
Thanks for looking at this. In case anyone's wondering, here's what the otel spec says about the key:

"If the key type is not string, it's string representation has to be supplied for the attribute. If the key has no unambiguous, canonical string form, don't include its value."

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#apache-kafka

**Comment by brennan-airtime** [comment]
@twmb Awesome thanks for the change.
