### ISSUE TITLE
WithHooks() can fail in non-obvious ways

### ISSUE THREAD

**Issue by brennan-airtime** [twmb/franz-go#365]
Since `kgo.Hook` is an empty interface anything implements it, even `[]kgo.Hook`. When adding `kotel` I was surprised when the tracing wasn't firing at all because I didn't inline the slice.

```golang
// opps, []kgo.Hooks is valid but implements no hooks
kgo.WithHooks(kotelService.Hooks())
// good
kgo.WithHooks(kotelService.Hooks()...)
```

I'm wondering if it would be palatable to change `WithHooks` to inspect the passed in hooks and flatten the slice/s if it detects it was passed something that implements no individual hooks. The inspection would only be done at client construction time.

That way the following invocations are all equivalent.

```golang
var xs, ys []kgo.Hook
var someHook kgo.Hook
var all []kgo.Hook
for _, v := range xs {
  all = append(all, v)
}
for _, v := range ys {
  all = append(all, v)
}
all = append(all, someHook)

kgo.WithHooks(all)
kgo.WithHooks(all...)
kgo.WithHooks(xs, ys, someHook)
kgo.WithHooks(xs..., ys..., someHook)
```

**Comment by twmb** [comment]
Technically a person can provide a type that is a slice that implements hooks:

```go
type foo []int

func (f *foo) OnBrokerDisconnected(...)
```

How can the client differentiate?

**Comment by brennan-airtime** [comment]
It can test for it right? If the slice implements one of the available hooks, don't flatten. If it implements no available hooks but the things inside do, it is likely an error right?

**Comment by twmb** [comment]
That's the same thing I was thinking.

> it is likely an error right?

And if things inside do, then flatten, right? That's the proposal? +1 to that.

This can also check that if a type doesn't implement any hook, and if elements of a slice don't implement any hook, return an error.

Also hooks.go should have a large `// NOTE` at the top to add checking any new hook to the section being added for this proposal.

**Comment by brennan-airtime** [comment]
Sounds good. I can open a PR since it sounds like we're on the same page.

w.r.t. the true error case (passed a thing that implements nothing), how do you envision that returning an error since `kgo.WithHooks()` is an option? Remember the error and return it from `kgo.NewClient`?

**Comment by brennan-airtime** [comment]
And yeah to be exhaustive:

- If arg implements any hook use it as is
- If arg is a slice and implements no hook methods, unpack it
- If no passed args implement some hook interface return error

**Comment by twmb** [comment]
> since `kgo.WithHooks()` is an option
I mean in cfg.validate() at the top of NewClient

> any passed thing fails to implement any hook interface
I'd be ok with that, since that's likely a mistake
