### ISSUE TITLE
allow to set different consumer groups for different topics

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#368]
kgo already have ability to pull multiple topics via single client, but if app needs different consumer group per topic?
may be add new option that combines ConsumerGroup and AddConsumeTopics , so i can pass topic and group id for it?

**Comment by twmb** [comment]
This would be a massive change to the guts of consuming / consumer groups, and I'm not sure it's feasible at all. This is similar to (I think your) old request to have a connection pool under the hood -- it's just not clear how to really do some aspects. Most APIs are designed around the single consume group aspect of a client. I don't think this is feasible to implement within the client.

**Comment by vtolstov** [comment]
Yeah this is complicated stuff as I see. Mostly this means that for different consumer groups I need different connection.
