### ISSUE TITLE
AssignGroup fails with an invalid coordinator ID

### ISSUE THREAD

**Issue by sbkoo9** [twmb/franz-go#37]
The first AssignGroup() call with a new consumer group name always fails with this error: `Kafka replied that group xxx has broker coordinator -1, but did not reply with that broker in the broker list`. The weird thing is when I restart my consumer, it successfully creates and joins the group. I'm using `v0.7.0`, but I confirmed that the same issue occurs with `v0.6.10`.

Here are the logs from the consumer:
```
DEBUG	kgoclient   opening connection to broker	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient   connection opened to broker	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient   issuing api versions request	{"broker": -2147483648, "version": 3}
DEBUG	kgoclient   wrote ApiVersions v3	{"broker": -2147483648, "bytes_written": 29, "write_wait": "193.9µs", "time_to_write": "270.4µs", "err": null}
DEBUG	kgoclient   read ApiVersions v3	{"broker": -2147483648, "bytes_read": 404, "read_wait": "114.5µs", "time_to_read": "17.6136ms", "err": null}
DEBUG	kgoclient   connection initialized successfully	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient   wrote Metadata v9	{"broker": -2147483648, "bytes_written": 34, "write_wait": "22.8808ms", "time_to_write": "309.6µs", "err": null}
DEBUG	kgoclient   read Metadata v9	{"broker": -2147483648, "bytes_read": 108, "read_wait": "94.4µs", "time_to_read": "5.4235ms", "err": null}
INFO	kgoclient   beginning to manage the group lifecycle
INFO	kgoclient   joining group
DEBUG	kgoclient   wrote FindCoordinator v3	{"broker": -2147483648, "bytes_written": 52, "write_wait": "87.9µs", "time_to_write": "339.1µs", "err": null}
DEBUG	kgoclient   read FindCoordinator v3	{"broker": -2147483648, "bytes_read": 59, "read_wait": "99.9µs", "time_to_read": "48.9366ms", "err": null}
DEBUG	kgoclient   wrote Metadata v9	{"broker": -2147483648, "bytes_written": 23, "write_wait": "121.6µs", "time_to_write": "72.5µs", "err": null}
DEBUG	kgoclient   read Metadata v9	{"broker": -2147483648, "bytes_read": 481, "read_wait": "91.4µs", "time_to_read": "2.9127ms", "err": null}
DEBUG	kgoclient   wrote Metadata v9	{"broker": -2147483648, "bytes_written": 23, "write_wait": "108.7µs", "time_to_write": "62.6µs", "err": null}
DEBUG	kgoclient   read Metadata v9	{"broker": -2147483648, "bytes_read": 481, "read_wait": "292.6µs", "time_to_read": "5.8912ms", "err": null}
ERROR	kgoclient   join and sync loop errored	{"err": "Kafka replied that group XXXXX has broker coordinator -1, but did not reply with that broker in the broker list", "consecutive_errors": 1, "backoff": "2s"}
```

Maybe my broker isn't setup correctly? I'm running a Kafka broker and a Zookeeper locally with docker-compose, making sure `broker.id` is set correctly:
```yaml
zookeeper:
  image: zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:latest
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  depends_on:
      - zookeeper
```

**Comment by twmb** [comment]
I've noticed this as well, this happens for me immediately when I start a cluster. What I know so far is that Kafka actually does not create a group coordinator (nor transaction coordinator) until a group (or txn id) is used at least once. During the period of time it's creating these, it replies that no group coordinator exists.

You can see this by issuing a metadata request against your broker for all topics: the `__consumer_offsets` topic will not yet exist.

If you leave the client running, does it eventually recover? I just looked at the franz-go code and I'm actually suspicious that I cache the invalid coordinator (under ID -1). I'll skim this a bit more, but if you can vet that too, that'd be great.

**Comment by sbkoo9** [comment]
I left my consumer running for an hour but it didn't recover. On a side note, I noticed that `kafka-console-consumer.sh` from the Kafka cli works fine with a new group id.

**Comment by twmb** [comment]
Cool, I'm going to patch this quickly, I'm confident the issue is because the invalid node ID is cached permanently.

With that side note, do you mean that the `kafka-console-consumer` does not run into this problem when a cluster first starts? If so, yeah I'd expect that, I definitely am seeing a caching bug within the client.

**Comment by sbkoo9** [comment]
Correct. I didn't see any issues with `kafka-console-consumer`.

**Comment by twmb** [comment]
I think https://github.com/twmb/franz-go/commit/528f007f561ed117126fbb74e7eb7352731a6eed (and the quick patch from the laptop I can actually test this on, https://github.com/twmb/franz-go/commit/ef9a16ab37350ccf0d19b279fff7752d3c5c39d0) should fix this.

Would you mind giving the latest commit a shot? If it fixes this, I can tag 0.7.1.

**Comment by sbkoo9** [comment]
I tried `528f007` locally. I don't see coordinator -1 error anymore, but it seems the client gets stuck while joining the group. 
```
DEBUG	kgoclient	opening connection to broker	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient	connection opened to broker	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient	issuing api versions request	{"broker": -2147483648, "version": 3}
DEBUG	kgoclient	wrote ApiVersions v3	{"broker": -2147483648, "bytes_written": 29, "write_wait": "184.8µs", "time_to_write": "139.6µs", "err": null}
DEBUG	kgoclient	read ApiVersions v3	{"broker": -2147483648, "bytes_read": 352, "read_wait": "92.9µs", "time_to_read": "11.524ms", "err": null}
DEBUG	kgoclient	connection initialized successfully	{"addr": "kafka:9092", "broker": -2147483648}
DEBUG	kgoclient	wrote Metadata v9	{"broker": -2147483648, "bytes_written": 34, "write_wait": "16.057ms", "time_to_write": "256.5µs", "err": null}
DEBUG	kgoclient	read Metadata v9	{"broker": -2147483648, "bytes_read": 108, "read_wait": "157.5µs", "time_to_read": "3.1607ms", "err": null}
INFO	kgoclient	beginning to manage the group lifecycle
INFO	kgoclient	joining group
DEBUG	kgoclient	wrote FindCoordinator v3	{"broker": -2147483648, "bytes_written": 52, "write_wait": "113.8µs", "time_to_write": "80.5µs", "err": null}
DEBUG	kgoclient	read FindCoordinator v3	{"broker": -2147483648, "bytes_read": 59, "read_wait": "69.8µs", "time_to_read": "57.0043ms", "err": null}
DEBUG	kgoclient	reaped connections	{"time_since_last_reap": "20.011064s", "reap_dur": "149.9µs", "num_reaped": 1}
```

**Comment by twmb** [comment]
Sorry, I phrased that confusingly, can you try ef9a16a?

What I meant in that prior comment is that 528f007 was the initial fix, and ef9a16a was a patch on that fix. I do most of my development on a mac, but docker doesn't play too well with a mac, so I when I went to integration test, I noticed that my initial bugfix needed a small patch itself.

**Comment by sbkoo9** [comment]
Great, `ef9a16a` did fix the issue.  🎉

**Comment by twmb** [comment]
Cool! I'll go ahead and tag this as 0.7.1

**Comment by twmb** [comment]
Alright, I've pushed v0.7.1!

**Comment by sbkoo9** [comment]
Cool, thanks for the help!
