### ISSUE TITLE
sort field names in logger before output

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#370]
{"level":"warn","@timestamp":"2023-02-25T12:51:25.834+0300","caller":"kgo/logger.go:123","msg":"unable to commit offset for topic partition","group":"TestAssign","topic":"mytopic","partition":35,"commit_from":120957}
{"level":"warn","@timestamp":"2023-02-25T12:51:25.834+0300","caller":"kgo/logger.go:123","msg":"unable to commit offset for topic partition","partition":42,"commit_from":119818,"group":"TestAssign","topic":"mytopic"}

not so serious , but if that possible best to sort field names

**Comment by twmb** [comment]
The logger implementation can do that -- far too complicated to manage at callsites.
