### ISSUE TITLE
Is there a "simple" way to use a consumer group with a compacted topic?

### ISSUE THREAD

**Issue by freeformz** [twmb/franz-go#378]
I have a compacted topic that stores/updates the state of a record by key. I'd like to use consumer groups, not for the committing of offsets, but for dealing with partition assignment/revocation/etc. I was looking through the docs and initially thought I could use `ConsumeResetOffset` to tell kgo to always read the entire topic, which is necessary to build up local state, but the docs indicate that consumer groups won't use this setting if the partition has commits. So I am looking for a way to do this w/o having to write my own GroupBalancer/whatever else would be needed.

**Comment by freeformz** [comment]
Lol me ... I guess the answer is [AdjustFetchOffsetsFn](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#AdjustFetchOffsetsFn) ?

**Comment by twmb** [comment]
If I'm understanding this correctly, you want to replay the state of a partition entirely on any consumer that is assigned the partition? (and this should be fine since records should be compacted out, in time?)

Is another option to never commit, so that every group member, when partitions are assigned, starts from the beginning? I think with this, you'll still need ConsumeResetOffset to be the beginning.

Not sure this is answering what you're trying to do, though..

**Comment by freeformz** [comment]
On a compacted topic (`cleanup.policy=compact`) log compaction is based on keys, not time, so yes. All consumers need to consume from the beginning of their assigned partitions of the topic.

I ended up using the following options...

```
		kgo.ConsumeResetOffset(kgo.NewOffset().AtStart()),
		kgo.AdjustFetchOffsetsFn(
			func(_ context.Context, offsets map[string]map[int32]kgo.Offset) (map[string]map[int32]kgo.Offset, error) {
				v := make(map[string]map[int32]kgo.Offset, len(offsets))
				for topic, partitions := range offsets {
					v[topic] = make(map[int32]kgo.Offset, len(partitions))
					for partition := range partitions {
						v[topic][partition] = kgo.NewOffset().AtStart().WithEpoch(-1)
					}
				}
				return v, nil
			}),
		kgo.Balancers(kgo.StickyBalancer()),
```

Do those seem reasonable? Any changes/additional options/tactics you recommend?

**Comment by twmb** [comment]
I think that looks like it'll do the job, but I think you can also `kgo.DisableAutoCommit()` and never call commit. If you do this, then every rebalance will:
* Fetch offsets
* See none are committed
* ListOffsets to start consuming from the ResetOffset

**Comment by freeformz** [comment]
Thanks!
