### ISSUE TITLE
Support for IAM roles in AWS_MSK_IAM SASL mechanism

### ISSUE THREAD

**Issue by gokul2411s** [twmb/franz-go#38]
Hi, currently (as of v0.7.4) the `aws.Auth` object only accepts `AccessKey` and `SecretKey`, which is good for supporting long-lived IAM user credentials. However, this struct does not support short-lived IAM role credentials, which also need a session token.

Support for IAM roles will be quite given the common use of EC2 instance profile roles to identify applications.

This is something that the [canonical Java implementation](https://github.com/aws/aws-msk-iam-auth) supports. As described in there, the session token (if present) will need to be wired into the `x-amz-security-token` field in the SASL authentication JSON payload.

Would be nice if we could support this in franz-go as well.

**Comment by twmb** [comment]
Yep, can do! I saw your comments on the commit I linked in the aws-msk-iam-auth issue, I'll copy my reply to this here:

If I'm not mistaken, this should be pretty easy to support: If a (new) SessionToken field is non-empty, then I add v.Set("X-Amz-Security-Token", auth.SessionToken) in the parameter map below. Would you be willing to test this? I haven't used session tokens before and have destroyed my AWS environment.

**Comment by twmb** [comment]
I've re-setup my cluster and have tested session tokens locally; I'll push a commit for this soon.

**Comment by twmb** [comment]
I pushed https://github.com/twmb/franz-go/commit/89001208851bed31ceb207163cf1da0d776b9d2f, which should address this. Will tag in v0.7.5
