### ISSUE TITLE
Support for user-agent in AWS_MSK_IAM SASL mechanism

### ISSUE THREAD

**Issue by gokul2411s** [twmb/franz-go#39]
Hi, currently (as of v0.7.4), the franz-go implementation of the AWS_MSK_IAM SASL mechanism does not plumb in the `user-agent` field.

Allowing users to specify a user agent allows them to authorize based on the [aws:UserAgent condition key](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-useragent).

This is something that the [canonical Java implementation](https://github.com/aws/aws-msk-iam-auth) supports.

Would be nice if we could support this in franz-go as well.

**Comment by twmb** [comment]
Yep, can do! I saw your comments on the commit I linked in the aws-msk-iam-auth issue. I think `User-Agent` is usually not included in the signing token.

From my reply on your comment:

Sure, I can add this. I can default to a package constant, and allow overrides via an optional UserAgent override in the Auth struct. I'd have to dig in again into the Java source to find the default UA, unless you have a better suggestion.

**Comment by twmb** [comment]
I pushed 8900120, which should address this. Will tag in v0.7.5.

**Comment by gengjie** [comment]
@twmb  Actually sorry to you, what you implement was totally different from java. And I think you misunderstood @grsubramanian . For java configuration, user doesn't need to configure awsAccessKey. If possible please reference here - https://github.com/segmentio/kafka-go/commit/fcb5875e8e6a1e1530ee733d6a17f86b84ec3963 to implement. Thanks!

**Comment by gengjie** [comment]
And also suggest to reopen this issue, Thanks!

**Comment by twmb** [comment]
@gengjie segmentio's code retreives an [aws.Credentials](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Credentials), which itself has `AccessKeyID`, `SecretAccessKey`, and `SessionToken`.

I show the same thing in my example here: https://github.com/twmb/franz-go/blob/0ca6478600c632deed4c7d65c13c3459d19071bd/examples/sasl/aws_msk_iam/main.go#L41

The benefit with this example is that the credentials can be loaded on every authorization. By requiring Credentials as input, I'm not sure the segmentio code handles key rotation / token refreshes.

**Comment by gengjie** [comment]
@twmb  Thanks! Got it!
