### ISSUE TITLE
Benchmark of kafka-go

### ISSUE THREAD

**Issue by bgranvea** [twmb/franz-go#395]
In README there is this sentence:

"This client is 2.4x faster at producing than segment's kafka-go, and so much faster at consuming that I'm not sure I wrote the consuming comparison correctly here."

I ran the benchmark with franz-go and kafka-go. I think there is a mistake on kafka-go code for a fair comparison:

```
			m, err := r.ReadMessage(context.Background())
```
should be replaced by:
```
			m, err := r.FetchMessage(context.Background())
```

Because with a consumer group, `ReadMessage ` reads a message and commits offset. As an alternative, you can also set `CommitInterval ` I think, it seems to be 0 by default, meaning a synchronous commit.

With this modification, I get a more reasonable speed up factor in favor of franz-go of x2 or x2.5

**Comment by twmb** [comment]
Good find! Would you be open to opening a PR fixing the flaw?

**Comment by bgranvea** [comment]
here it is: https://github.com/twmb/franz-go/pull/401

I let you update the README as I'm not sure how you did the benchmark (with or without compression, consumer group....)

**Comment by twmb** [comment]
At this point, I can't remember either -- I probably ran with and without and saw the average slow down. Compression / consumer group shouldn't affect throughput _too_ much. I might just copy your 2 to 2.5x into the README itself.

**Comment by bgranvea** [comment]
I would prefer that you redo the benchmark because today I didn't find the same numbers. I haven't investigated to understand why.

**Comment by twmb** [comment]
What differences are you seeing?

**Comment by bgranvea** [comment]
I retested with a 10 partition topic and messages produced with `go run . -topic foo` (no compression).

Here are my results:

- consume without group:

franz-go: 4200k records/s
segment: 600k records/s

- consume with group:

franz-go consume: 4200k records/s
segment consume: 750k records/s

**Comment by twmb** [comment]
Took a bit of setup and I could only really get it working with groups (unless you create 1-partition topics), with groups I got 6x throughput. I'll put it from 2 to 6x just to be comprehensive.
