### ISSUE TITLE
kmsg Request/Response kind output

### ISSUE THREAD

**Issue by owenhaynes** [twmb/franz-go#396]
Have a case where I would like to log the message kind of the request/response in a generic way. I could use reflect but this has a performance hit.

The issue now is request and response have stable apis so maybe we need a extra interface like Stringify but this seems overkill.

**Comment by owenhaynes** [comment]
a message key enum thing could also work

**Comment by twmb** [comment]
kmsg.Key.Name exists for exactly your purpose -- you can do kmsg.Key(resp.Key()).Name
