### ISSUE TITLE
Question: PollRecords timeout

### ISSUE THREAD

**Issue by xgalaxy** [twmb/franz-go#407]
I'm a bit confused about the interplay between `PollRecords` and `BlockRebalanceOnPoll` in regards to timeouts. If I'm calling `PollRecords` with a non-nil context is it possible that `PollRecords` would block long enough to kick us out of a consumer group because it didn't respond to a rebalance in time?  Would you recommend passing a nil context in the case of using `BlockRebalanceOnPoll`?

Thanks.

**Comment by twmb** [comment]
Realistically the function should be named something like
```go
func (*Client) BlockRebalanceAsSoonAsFetchesAreAvailable,NotBefore
```
but that's a bit of a mouthful

The blocking only takes effect once a fetch is available -- if there are no fetches available, rebalancing is not blocked.

The code in question:
https://github.com/twmb/franz-go/blob/1a59c2d62d0d0ebd115f4f507379189644972c1f/pkg/kgo/consumer.go#L500-L510
while waiting on the context, rebalancing is not blocked. On line 510 we call a closure that internally first blocks rebalancing, and then grabs any available fetches.

**Comment by twmb** [comment]
Yes exactly 👍
