### ISSUE TITLE
Question: Is documentation up to date

### ISSUE THREAD

**Issue by EduardoLaranjo** [twmb/franz-go#418]
Hey,

I'm bit confused with documentation on [consumer group](https://github.com/twmb/franz-go/blob/master/docs/producing-and-consuming.md#consumer-groups)

> By default, the group consumer will autocommit every 5s, commit whenever a rebalance happens (in [OnPartitionsRevoked](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#OnPartitionsRevoked)), and will issue a blocking commit when leaving the group. For most purposes, this can suffice. The default commit logs any errors encountered, but this can be overridden with the [AutoCommitCallback](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#OnPartitionsRevoked) option or by disabling autocommit and instead committing yourself.

The auto commit every 5s isn't actually true after this [PR](https://github.com/twmb/franz-go/commit/c6df11da978a4219b09a4d8ec031bf6cff80d9d0), with this changes we are commiting after polling again instead of every 5s

Btw thanks for this awesome lib

**Comment by twmb** [comment]
Autocommit still happens every 5s. That PR changed what records are considered candidates for committing. Previously, it was all records ever returned from poll -- which could lead to data loss if the application crashed before you actually processed the current poll. Now, it's all records that were _previously_ returned, with the understanding that when you call poll again, you've completed processing of the prior poll's records.
