### ISSUE TITLE
kadm: Add ErrorSummary() for sharded responses

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#435]
The `kadm` client is super handy for administrative tools, especially when working with sharded responses such as fetching many consumer group offsets. The package already offers a `func (rs FetchOffsetsResponses) EachError(fn func(FetchOffsetsResponse))` function to log all errors from a response. 

Oftentimes I want to bubble up a single descriptive error message in case all shards have failed after checking with `res.AllFailed()`. I propose adding another method `func (rs FetchOffsetsResponses) ErrorSummary() error` which would offer that for all sharded responses which may contain more than one error. The returned error message could be something like this: "8 out of 13 total shard requests have failed. The last error is: GROUP_COORDINATOR_NOT_AVAILABLE - the returned error message by the respective broker."

Usage would then be:

```go
res := s.kafkaSvc.ListConsumerGroupOffsetsBulk(ctx, groups)

res.EachError(func(shardRes kadm.FetchOffsetsResponse) {
	s.Logger.Warn("failed to fetch group offset",
		zap.String("group", shardRes.Group),
		zap.Error(shardRes.Err))
})

if res.AllFailed() {
	return nil, res.ErrorSummary()
}
```

What do you think? Happy to contribute it.

**Comment by twmb** [comment]
wdyt about instead switching `Error` to return `ShardErrors`, which already does the summary you're looking for? And we can improve the ShardErrors.Error function.

So then your example would switch to,

```
if res.AllFailed() {
        return nil, res.Error()
}
```

**Comment by twmb** [comment]
Actually, the sharding aspect is already lost in FetchOffsetResponses. Each error can be from any shard. I'm not sure this is worth providing by default in kadm -- usually Error returns the first encountered error -- I'm leaning to close this without a proposed implementation.

**Comment by twmb** [comment]
Closed due to prior comment
