### ISSUE TITLE
add option to return error on non exiting topic for ConsumeTopics opt 

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#439]
sometimes someone =) specify invalid topic name (non exiting), but kgo does not fails on subscribe with ConsumeTopics, does it possible to add ability to return error if topic unknown or client does not have rights to fetch from it or produce?

**Comment by twmb** [comment]
So are you thinking an option to return _all_ retryable errors in fetches, or just this one?

**Comment by vtolstov** [comment]
does it possible to add option to handle all retryable errors so inside this func we can decide to continue retry or not?

**Comment by vtolstov** [comment]
like
type RetryFunc func(ctx context.Context, retryCount int, err error) (bool, error)
so we know how much retries already done, error happened, and can return continue (via first arg), may be via second return arg return something if continue not needed like fmt.Errorf("retry count reached")

**Comment by twmb** [comment]
The client already internally retries following roughly that exact pattern. For fetching, failed partitions are always retried forever. I thought you were asking for an option like,
```
func KeepFetchRetryableErrors() Opt
```
such that that retryable errors here: https://github.com/twmb/franz-go/blob/5379fb0eaea2d6c21595b508ed770662e5650e04/pkg/kgo/source.go#L864 would not be stripped.

**Comment by vtolstov** [comment]
Internally, but if user wants to handle errors via own logic? One use-case - check that topic exists when subscribe to it.

**Comment by twmb** [comment]
In that case, existence checking needs to be done _before_ subscribing to it. However, with the option, you could react to errors (such as a topic being deleted). Would the option above satisfy what you're looking for?
