### ISSUE TITLE
question: Should `client.PollRecords` return uncommitted records on each poll?

### ISSUE THREAD

**Issue by marclop** [twmb/franz-go#440]
## Context and current behavior

Based on <https://github.com/twmb/franz-go/blob/master/examples/goroutine_per_partition_consuming/manual_commit/main.go>, where records are automatically committed after they are processed. I modified the code slightly to accept a `process` function which processed the records and commits the records if the process function is successful, otherwise, prints an error.

The added test:

- produces 10 records and the fetches consume up to 2 records at a time.
- passes in a processor that returns an error the first time the records are processed, but process without an error the rest of the time.
- Currently, only 10 records are successfully processed, and messages aren't redelivered when not committed.

<details><summary>twmb_consumer_test.go</summary>
<p>

```go
package kafka

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twmb/franz-go/pkg/kadm"
	"github.com/twmb/franz-go/pkg/kfake"
	"github.com/twmb/franz-go/pkg/kgo"
)

type tp struct {
	t string
	p int32
}

type pconsumer struct {
	cl        *kgo.Client
	topic     string
	partition int32

	quit chan struct{}
	done chan struct{}
	recs chan []*kgo.Record
}

type process func(r ...*kgo.Record) error

type splitConsume struct {
	// Using BlockRebalanceOnCommit means we do not need a mu to manage
	// consumers, unlike the autocommit normal example.
	consumers map[tp]*pconsumer
	process   process
}

func (pc *pconsumer) consume(process process) {
	defer close(pc.done)
	fmt.Printf("Starting consume for t %s p %d\n", pc.topic, pc.partition)
	defer fmt.Printf("Closing consume for t %s p %d\n", pc.topic, pc.partition)
	ctx := context.Background()
	for {
		select {
		case <-pc.quit:
			fmt.Printf("exiting consumer for %s p %d\n", pc.topic, pc.partition)
			return
		case recs := <-pc.recs:
			if err := process(recs...); err != nil {
				fmt.Printf("failed processing %d records, continuing to process records...\n",
					len(recs),
				)
				continue
			}
			fmt.Printf("processed %d records, about to commit t %s p %d\n",
				len(recs), pc.topic, pc.partition,
			)
			if err := pc.cl.CommitRecords(ctx, recs...); err != nil {
				fmt.Printf("error when committing offsets to kafka err: %v t: %s p: %d offset %d\n", err, pc.topic, pc.partition, recs[len(recs)-1].Offset+1)
			}
		}
	}
}

func (s *splitConsume) assigned(_ context.Context, cl *kgo.Client, assigned map[string][]int32) {
	for topic, partitions := range assigned {
		for _, partition := range partitions {
			pc := &pconsumer{
				cl:        cl,
				topic:     topic,
				partition: partition,

				quit: make(chan struct{}),
				done: make(chan struct{}),
				recs: make(chan []*kgo.Record, 5),
			}
			s.consumers[tp{topic, partition}] = pc
			go pc.consume(s.process)
		}
	}
}

// In this example, each partition consumer commits itself. Those commits will
// fail if partitions are lost, but will succeed if partitions are revoked. We
// only need one revoked or lost function (and we name it "lost").
func (s *splitConsume) lost(_ context.Context, cl *kgo.Client, lost map[string][]int32) {
	var wg sync.WaitGroup
	defer wg.Wait()

	for topic, partitions := range lost {
		for _, partition := range partitions {
			tp := tp{topic, partition}
			pc := s.consumers[tp]
			delete(s.consumers, tp)
			close(pc.quit)
			fmt.Printf("waiting for work to finish t %s p %d\n", topic, partition)
			wg.Add(1)
			go func() { <-pc.done; wg.Done() }()
		}
	}
}

func (s *splitConsume) poll(ctx context.Context, cl *kgo.Client) {
	for {
		// PollRecords is strongly recommended when using
		// BlockRebalanceOnPoll. You can tune how many records to
		// process at once (upper bound -- could all be on one
		// partition), ensuring that your processor loops complete fast
		// enough to not block a rebalance too long.
		fetches := cl.PollRecords(ctx, 2)
		defer cl.AllowRebalance()
		if err := fetches.Err0(); fetches.IsClientClosed() ||
			errors.Is(err, context.DeadlineExceeded) ||
			errors.Is(err, context.Canceled) {
			return
		}
		fetches.EachError(func(_ string, _ int32, err error) {
			// Note: you can delete this block, which will result
			// in these errors being sent to the partition
			// consumers, and then you can handle the errors there.
			panic(err)
		})
		fetches.EachPartition(func(p kgo.FetchTopicPartition) {
			if len(p.Records) == 0 {
				return
			}
			tp := tp{p.Topic, p.Partition}
			// Since we are using BlockRebalanceOnPoll, we can be
			// sure this partition consumer exists:
			//
			// * onAssigned is guaranteed to be called before we
			// fetch offsets for newly added partitions
			//
			// * onRevoked waits for partition consumers to quit
			// and be deleted before re-allowing polling.
			s.consumers[tp].recs <- p.Records
		})
	}
}

func TestKafkaDataLoss(t *testing.T) {
	var once sync.Once
	var counter atomic.Int32
	s := &splitConsume{
		consumers: make(map[tp]*pconsumer),
		process: func(records ...*kgo.Record) error {
			var err error
			once.Do(func() {
				err = errors.New("procesing error")
			})
			if err == nil {
				counter.Add(int32(len(records)))
			}
			return err
		},
	}

	topic := "topic"
	cluster, err := kfake.NewCluster()
	require.NoError(t, err)
	t.Cleanup(cluster.Close)

	brokers := cluster.ListenAddrs()

	client, err := kgo.NewClient(kgo.SeedBrokers(brokers...))
	require.NoError(t, err)

	kadmClient := kadm.NewClient(client)
	t.Cleanup(kadmClient.Close)

	_, err = kadmClient.CreateTopics(context.Background(), 2, 1, nil, topic)
	require.NoError(t, err)
	opts := []kgo.Opt{
		kgo.SeedBrokers(brokers...),
		kgo.ConsumerGroup("group"),
		kgo.ConsumeTopics(topic),
		kgo.OnPartitionsAssigned(s.assigned),
		kgo.OnPartitionsRevoked(s.lost),
		kgo.OnPartitionsLost(s.lost),
		kgo.DisableAutoCommit(),
		kgo.BlockRebalanceOnPoll(),
	}

	cl, err := kgo.NewClient(opts...)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	if err = cl.Ping(ctx); err != nil { // check connectivity to cluster
		t.Fatal(err)
	}
	go s.poll(ctx, cl)

	for i := 0; i < 10; i++ {
		r := kgo.StringRecord(fmt.Sprintf("value %d", i))
		r.Topic = topic
		res := client.ProduceSync(ctx, r)
		assert.NoError(t, res.FirstErr())
	}
	assert.Eventually(t, func() bool {
		return counter.Load() == 10
	}, time.Second, time.Millisecond)
	t.Log(counter.Load())
}
```

</p>
</details>

<details><summary>test output</summary>
<p>

```console
$ go test -v .
=== RUN   TestKafkaDataLoss
Starting consume for t topic p 0
Starting consume for t topic p 1
failed processing 2 records, continuing to process records...
processed 2 records, about to commit t topic p 1
processed 2 records, about to commit t topic p 1
processed 2 records, about to commit t topic p 1
processed 2 records, about to commit t topic p 1
    twmb_consumer_test.go:206:
        	Error Trace:	/kafka/twmb_consumer_test.go:206
        	Error:      	Condition never satisfied
        	Test:       	TestKafkaDataLoss
    twmb_consumer_test.go:209: 8
--- FAIL: TestKafkaDataLoss (1.01s)
FAIL
exit status 1
FAIL	github.com/elastic/apm-queue/kafka	1.820s
```

</p>
</details> 

## Expected Behavior

I was expecting the uncommitted messages to be re-delivered to the consumer with the assigned partitions on the next `cl.PollRecords(ctx, 2)` call or after some time if the offset wasn't committed. Currently, this doesn't seem to be the case, and I'm unsure if it is the intended behavior.

Should I be approaching the problem differently? I would like _at least once_ delivery guarantees, but it seems that with the current model is prone to data loss when some records can be processed for some reason (maybe transient).

**Comment by twmb** [comment]
Messages are not redelivered, you must explicitly rewind with SetOffsets. Instead, what I'd recommend is to keep the messages locally and only drop them after you process them (rather than trying to expect them to be redelivered) -- or send them to a dead letter queue.

Kafka consumers basically read partitions as if there's a big cursor into a file behind the scenes. Once the cursor advances, it doesn't rewind. From the perspective of a client, the cursor advanced two messages -- even if they failed to be processed by you, the cursor is not automatically rewound.

The commit is a signal for when you restart your application -- where should the cursor start from? Or, when a partition gets rebalanced to another consumer -- where should that consumer's cursor start from?

It's similar to how there's no mechanism for an io.Reader to automatically rewind _after_ the read. `SetOffsets` can be seen as the client equivalent of an `io.Seek` -- you trigger a manual rewind, so that you can reread.

But, I would recommend keeping the failed messages buffered and retrying them in your function rather than trying to rewind the client and reprocess some redelivered messages.

**Comment by marclop** [comment]
Thanks @twmb! I expected as much but I wanted to make sure. I'll think about it and see how to implement it in a way that makes sense.

**Comment by twmb** [comment]
By the way, I didn't realize you found and were already using kfake. I'll try not to break the API, but I'm impressed you found it and am glad it's useful for somebody else already :)

My aim is to implement transactions and a few other requests, iron out a few more TODOs, and make it a core part of franz-go. I _might_ leave it as a separate module, but I don't anticipate the API changing much / any more than kgo.

**Comment by marclop** [comment]
@twmb yeah it's been very handy to use for unit tests. Small breaking changes aren't a big deal, I understand it's a very new package and it's bound to change over time.

**Comment by rostislaved** [comment]
I ran into the same confusion while using the goroutine_per_partition_consuming/manual_commit example.

At first glance, it looks like skipping CommitRecords after a processing failure would cause the records to be returned by the next PollRecords, but that's not how it works. Since the example only simulates successful processing with time.Sleep, it was easy to make that assumption.

A short note in the example or documentation mentioning that uncommitted records are not automatically returned by subsequent PollRecords calls would likely help others avoid the same confusion.
