### ISSUE TITLE
Stuck partition on transactional producer - KAFKA-12671

### ISSUE THREAD

**Issue by Zach-Johnson** [twmb/franz-go#451]
Hello! I've managed to hit the stuck partition issue on a transactional producer once again 😄 and wanted to see if you had any further insight after our last conversation about this in https://github.com/twmb/kcl/issues/10.

As far as I can tell, here's what happened:
- The producer is using version `v1.9.1` of this library.
- The producer idled for a long period of time (multiple days). During this time, it _should_ have been doing a begin/abort transaction periodically to heartbeat the transaction ID (TBD whether there is a bug in this code path, this may have not been functioning?).
- Our cluster seemingly had two unplanned leader elections during this idle period
- On resume, the producer errored: `INVALID_PRODUCER_ID_MAPPING: The producer attempted to use a producer id which is not currently assigned to its transactional id`
- - This error has occurred before (a bunch of times) with no issues, as the service just restarts and begins producing on a new ID
- The partition it was producing to is now stuck
- Running the "unstick" command from `kcl` found the partition in question, but hung on on the step when it tries to find the transaction ID, i.e. `. . .looking in __transaction_state to find its transactional id...`

So somehow this seems to have triggered the KAFKA-12671 bug, and the transaction ID in question seems to be entirely missing. Is there any other diagnostic information I might be able to collect that might shed some light on exactly how this triggered? Obviously I'd like to avoid this happening again. I think my producer code might be mis-behaving on idle, and I'm thinking perhaps it makes sense to just shut down the producer entirely when its idling, rather than trying to keep the transaction alive. I'm also going to update to the latest version of this library, although I didn't see anything in release notes that would indicate that this issue has been revisited - is that correct?

No worries if you want to close this issue - I realize it probably isn't anything to do with this library at this point, but I thought it might be of interest to others.

**Comment by twmb** [comment]
With transactions, the client actually _does not_ communicate with the server if nothing is going on. `BeginTransaction` is a signal for the client itself, nothing is written to the server. `EndTransaction` only writes the the server if something happened. So, eventually, the producer ID that was initialized expired. This is why when you eventually did communicate again, you saw `INVALID_PRODUCER_ID_MAPPING` -- the producer ID no longer exists.

However, things getting stuck is bad.

Is your partition still stuck?

**Comment by Zach-Johnson** [comment]
Ah okay - it does seem like doing a `BeginTransaction`, a single produce, and then `AbortTransaction` does successfully keep the producer ID alive. It looks like the code that was doing this heartbeat was occasionally not running in some circumstances and I'm guessing that combined with broker restarts somehow caused us to hit this issue.

Yeah, the partition appears to be permanently stuck. The application uses a custom partitioner though, so I was able to work around this by moving all that partition's data to another partition. Not ideal, but better than re-creating a topic! We can close this if you like - thanks for the insight as always.

**Comment by twmb** [comment]
If it’s still stuck, we can try interactively debugging it on the discord
channel?

**Comment by Zach-Johnson** [comment]
Sure, what discord? I'm also in the redpanda slack, I can message you on there.

**Comment by twmb** [comment]
For posterity: we had a conversation on Slack, but since it's been a week and this is production data, we've decided to just leave the partition broken. My theory for how to fix likely wont work anyway because the txid is expired, and my known way to fix requires the txid to at least exist within the broker -- if it's been too long, my fix can't work.
