### ISSUE TITLE
Question: best strategy for retrying indefinitely, but stopping when a rebalance occurs

### ISSUE THREAD

**Issue by stampy88** [twmb/franz-go#457]
Hi,

I am reading through the examples and the code to try and get a hang as far as how to best implement the following: I want to be able to process a batch of records via a `PollRecords` and retry reprocessing a record (on an retryable error) indefinitely _unless_ there is a rebalance occurring where we would be losing partitions. In this case, I want to be able to detect that and _not_ continue to retry, but commit the work I did and allow the rebalance to proceed. I am thinking it is a combination of the `OnPartitionsRevoked` and feeding this "signal" into the main consumer loop, but like to get your thoughts.

But while looking at this example, https://github.com/twmb/franz-go/blob/master/examples/goroutine_per_partition_consuming/manual_commit/main.go, I see that you are setting `BlockRebalanceOnPoll`. I may be misunderstanding, but I thought that since you are holding up the `OnPartitionsRevoked` [here](https://github.com/twmb/franz-go/blob/master/examples/goroutine_per_partition_consuming/manual_commit/main.go#L84), you wouldn't specifically need to set that option. Or is that only to ensure that the consumers aren't mutated during processing, i.e. `s.consumers[tp].recs <- p.Records`?

Thanks

**Comment by twmb** [comment]
> I am thinking it is a combination of the OnPartitionsRevoked and feeding this "signal" into the main consumer loop
yes exactly, however there is a catch: after signaling, you also want to wait inside `OnPartitionsRevoked` until your processing loop is complete and until you've committed. Once you return from `OnPartitionsRevoked`, the client continues rebalancing, so if you do any work for the _prior_ generation _after_ rebalancing, you may be doing work for the new generation for partitions you no longer own.

`BlockRebalanceOnPoll` switches the client behavior to make this slightly easier to reason about: it switches the client to block itself from continuing a rebalance until you specifically say "I'm done processing what I polled" with the `AllowRebalance` function. Only after `AllowRebalance` is `OnPartitionsRevoked` called. This option actually makes kgo more similar to Sarama (if you have any familiarity). In Sarama, the client calls your ConsumeClaim function, and only once that function returns, the client can call Cleanup. This is analogous to ConsumeClaim == PollFetches, and Cleanup == OnPartitionsRevoked. The _big_ downside with this way of processing is you need to ensure that your record processing function is fast enough that a rebalance isn't blocked by your processing function for long enough that your consumer is kicked from the group.

For your purposes, it sounds like _not_ using `BlockRebalanceOnPoll` is better, and you should just use the plain rebalance-at-any-time default client. Just be sure to orchestrate your `OnPartitionsRevoked` to wait for the work to be interrupted and for your commit to complete.

**Comment by stampy88** [comment]
Thanks for the quick reply, @twmb. Sorry, yes, I meant to say that `OnPartitionsRevoked` needed to wait until the loop was completed as well, but thank you very much for confirming my understanding. Appreciate it!
