### ISSUE TITLE
Goroutines Shoot-Up while partition leadership changes happens in Redpanda/Kafka cluster

### ISSUE THREAD

**Issue by anuraj381** [twmb/franz-go#462]
Hi, I have a use-case where my GoLang service is producing data in a topic in Redpanda cluster, this service produces a high rps to Redpanda, every k8s pod of this service produces 5000 messages/sec. Now whenever there is a situation when there is any partition leadership changes happening with the Redpadna cluster topic (Partition Leadership changes in Redpadna cluster is not rare and actually keep on happening every now and then), ideally producer retries should be able to help us in producing even while leadership change is happening (as leader partition becomes unavailable for small duration only), however issue is that since my service is at high rps, meanwhile the leadership change for a partition, franz-go library created huge amount of goroutines (maybe as the requests keep on coming and high rps of the service). Attaching a screenshot of goroutines shoot-up, these increased goroutines takes up a lot of memory and my service performance degrades completely for that short time when leadership changes are happening.

<img width="1649" alt="Screenshot 2023-05-27 at 12 45 04 AM" src="https://github.com/twmb/franz-go/assets/17931142/78226d66-2428-4a8a-bd5c-c6efc5886f8d">

<img width="1649" alt="Screenshot 2023-05-27 at 12 54 26 AM" src="https://github.com/twmb/franz-go/assets/17931142/39262a5b-f8fd-4026-bc25-fae948bab9c6">

How should I deal with this situation ?
Is there a way to maybe limit the number of goroutines created by franz-go library ?

Here are the producer configs - 
maxBatchBytes : 200000,
maxBufferedRecords : 5000,
lingerDurationInMillis : 100,
recordRetryCount :  1
produceRequestTimeoutInMillis : 250
compression : gzip

**Comment by twmb** [comment]
Are you able to capture a pprof goroutine dump so we can see which goroutines are spiking? If you can recreate this,
* capture /runtime/pprof/goroutine before the spike (I think debug=1 or 2 collapses goroutines but I forget which,... maybe it's the default?)
* capture during

Also I'm a bit surprised to see 100K goroutines -- is that all from franz-go? The library is pretty optimized to use as few goroutines as possible so I'm surprised to see such a spike.

**Comment by anuraj381** [comment]
> Also I'm a bit surprised to see 100K goroutines -- is that all from franz-go

Hi @twmb , the goroutines metric I shared is sum across all k8s pods for the application and at the application level, which can be upto 600.
Also I won't say that adding franz-go library increased goroutines significantly, however whenever there is a partition leadership change happens in Redpanda cluster and from whichever our application pod a batch is targeted for that partition, it might be failing or whatever is happening internally, we do see a huge spike in goroutines on that k8s application pod.

> The library is pretty optimized to use as few goroutines as possible so I'm surprised to see such a spike

during the time when retries are happening for a batch or is blocked for publish, and further requests are coming for publishing, do we limit number of goroutines created that time ? Again this is what I am assuming looking at the graphs, I don't know internally how the library works.

> capture /runtime/pprof/goroutine before the spike (I think debug=1 or 2 collapses goroutines but I forget which,... maybe it's the default?)

sure, I will try to capture the profiling data

**Comment by anuraj381** [comment]
Hi @twmb , this is resolved, as I mentioned my service is publishing messages at a high rps and since there some Partition Leadership changes happening in the Redpanda cluster, so the application pods which are producing to the affected partition, will experience produce request failures and new produce request keeps on coming, also we were using `Produce` method to publish which seems to be blocking till the message/record it is called with gets added into a batch. This blocking behaviour actually led to multiple goroutines from gin (as the requests keep on coming). 
To resolve this we actually found another method with franz-go `TryProduce` which is not blocking.
