### ISSUE TITLE
How to get topic size?

### ISSUE THREAD

**Issue by cloud-66** [twmb/franz-go#468]
I need to find and delete empty topics. I was wondering if you could tell me How to find empty topic?
Redpanda Console   shows topic size. I tried to undestand how it do it, but unsuccessfully.
Thank you.

**Comment by weeco** [comment]
You can use the `DescribeBrokerLogDirs` request to retrieve the size that brokers store for each partition and then aggregate that per topic. The kadm client has a `DescribeBrokerLogDirs` function that you probably want to use.

**Comment by twmb** [comment]
^^ as said above
