### ISSUE TITLE
Possible small documentation issue - SessionTimeout

### ISSUE THREAD

**Issue by Hetex** [twmb/franz-go#471]
I've been using "BlockRebalanceOnPoll" with default client settings, and I've noticed that some records take longer than the default allowed period.

In the docs [here](https://github.com/twmb/franz-go/blob/master/docs/producing-and-consuming.md?plain=1#L158 ), it says "ensure your [SessionTimeout][ST] is long enough to encompass any processing you do between polls" but [here](https://github.com/twmb/franz-go/blob/master/pkg/kgo/config.go#L1476), it says "group member is kicked from the group because it exceeded the rebalance timeout".

It seems to me, that I just need to increase the rebalance timeout to accommodate the longer processing time, but wanted to check if I was missing something because of the docs. Is there any downsides other than longer rebalancing if I increase this to 5 minutes (assuming its less than "max.poll.interval.ms")?

Thanks for all your work on this, it's definitely my favourite Kafka client.

**Comment by twmb** [comment]
* heartbeat interval: time between your client checking in
* session timeout: time broker allows your client to go without a heartbeat until the broker kicks your client from the group
* rebalance timeout: once a rebalance begins, how long your client can go without issuing JoinGroup (i.e., you can block a rebalance with OnPartitionsRevoked, but you must return before the rebalance timeout). I _think_ the maximum rebalance timeout of the group is chosen

The downside of bumping the rebalance is that the entire group might be waiting on your one member to finish whatever it's doing before the group can continue -- this has a bit of a "stop the world" effect. That's less true in the new world of cooperative consuming, so bumping the rebalance timeout might be fine.

Closing for now but if you have another question we can reopen -- or if you have a doc improvement suggestion.

**Comment by Hetex** [comment]
Thanks for replying.

I'll open a PR to change the document to say: "ensure your [RebalanceTimeout][RT] is long enough to encompass any processing you do between polls" instead of SessionTimeout.

**Comment by twmb** [comment]
OH I see what you mean, yes, good catch that needs to be fixed.
