### ISSUE TITLE
Add validation for sasl.username and sasl.password

### ISSUE THREAD

**Issue by tmgstevens** [twmb/franz-go#472]
Compared to [librdkafka](https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_sasl_plain.c#L125), franz-go does not appear to validate whether sasl.username and sasl.password are set to valid values.

Ideally the client should prevent empty values being set and sent to the server (noting also that Redpanda does not handle empty values well either)

**Comment by twmb** [comment]
This requires adding an optional `Validate() error` method and then implementing it on all SASL implementations. This is small, but will wait for v1.14.

**Comment by twmb** [comment]
Actually, with how the interfaces are defined, it's a bit challenging to validate up front. I can add non-empty validation before the client first message is sent to the server -- this will bubble up as errors to the client in failed requests, but will not fail NewClient.
