### ISSUE TITLE
Serde doesn't talk with Schema registry itself

### ISSUE THREAD

**Issue by sarsony1** [twmb/franz-go#473]
I have observed that the ser/deser instance doesnt really talk to the schema registry. I guess we will have to register IDs explicitly after adding schema with the registry which is not what you would expect. Am I missing something. Can someone help me with how this is usually handled ?

**Comment by twmb** [comment]
(discussion continued in Redpanda Data community slack)
Type registering is needed because _something_ needs to tie an ID to a type and how to encode it.
