### ISSUE TITLE
OAuth2 support with client credentials

### ISSUE THREAD

**Issue by cthtrifork** [twmb/franz-go#482]
I see you can supply a long lived token, but we need to support short-lived tokens using client credentials and a token endpoint. 

Any plans to support this?

**Comment by twmb** [comment]
The oauth package itself provides an `Oauth` function,

```
func Oauth(authFn func(context.Context) (Auth, error)) sasl.Mechanism {
```

You can use this to create a new Auth with a new short lived token:

```
kgo.SASLs(oauth.Oauth(ctx context.Context) (oauth.Auth, error) {
    shortToken, err := aquireToken(ctx)
    return oauth.Auth{Token: shortToken}, err
})
```
The `Auth.AsMechanism` function is only provided if you don't intend to change the token

note the aws_msk_iam example, which is similar in concept:
https://github.com/twmb/franz-go/blob/a61b2fa4407091ae3679cea5868dbd128f3a995b/examples/sasl/aws_msk_iam/main.go#L41

**Comment by cthtrifork** [comment]
Thanks for the hints! it seems to be working perfectly. I have done some testing in the related PR, but not verified corner-cases such as expired tokens etc. I am hoping this is handled by this library 😄
