### ISSUE TITLE
franz-go  don`t support  golang version 19

### ISSUE THREAD

**Issue by elPoem** [twmb/franz-go#488]
when i run my  project 19 golang verson i got this error log, but on 16 golang version all worked fine

`# github.com/klauspost/compress/huff0
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:774:21: cannot convert out (variable of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:775:24: cannot convert out[dstEvery:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:776:24: cannot convert out[dstEvery * 2:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:777:24: cannot convert out[dstEvery * 3:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:1013:21: cannot convert out (variable of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:1014:24: cannot convert out[dstEvery:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:1015:24: cannot convert out[dstEvery * 2:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
/home/ro/go/pkg/mod/github.com/klauspost/compress@v1.16.3/huff0/decompress.go:1016:24: cannot convert out[dstEvery * 3:] (value of type []byte) to type *[256]byte:
	conversion of slices to array pointers requires go1.17 or later (-lang was set to go1.16; check go.mod)
`

**Comment by brunsgaard** [comment]
The -lang flag is an option of the Go compiler.

It is usually set by go commands that compile sources, e.g. go build, based on the go <version> directive in go.mod. You likely have a version in go.mod lower than 1.17, which is the version that introduces conversion from slice to array pointers.

You can fix the Go version in go.mod by hand or by running `go mod edit -go=1.19`

**Comment by twmb** [comment]
Yeah not really sure what to say besides the above^^, thanks @brunsgaard. I've tested this project on 1.19 and 1.20.
