### ISSUE TITLE
 how to improve performance?

### ISSUE THREAD

**Issue by igor9292** [twmb/franz-go#492]
I'm trying to split a topic into several, but it seems to me not quite the right solution, to read and write right away? At the moment, if there is one condition, then there is no lag, if there are more than 2 conditions, then the lag grows ....

If you do write to /dev/null, then everything has time to read, even under >5 conditions..
```
p2 := kgo.AbortingFirstErrPromise(cl2)
fetches.EachPartition(func(p kgo.FetchTopicPartition) {
   p.EachRecord(func(r *kgo.Record) {
      for i := 0; i < len_cond; i++ {
         idx := bytes.Index(r.Value, cond_bytes[i])
         if idx != -1 {
            r.Topic = topicss[i]
            cl2.Produce(ctx, r, p2.Promise())
            break
         } else {
            if i+1 == len_cond {
               r.Topic = topicss[len_topic-1]
               cl2.Produce(ctx, r, p2.Promise())
            }
         }
      }
   })
   ```

**Comment by twmb** [comment]
Hey I'd need to see the consumer side as well. I don't really understand what's going on with len_cond, or really with that function at all.
