### ISSUE TITLE
pkg.go.dev reports there is a github.com/twmb/franz-go/pkg/kmsg/v2@v2.0.1 but it does not exist

### ISSUE THREAD

**Issue by nyetwurk** [twmb/franz-go#494]
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kmsg/v2@v2.0.1

**Comment by twmb** [comment]
This was a mistake that was quickly undone, but the version persists due to Go being Go. I remember trying to add a retract statement for this version but that didn't work, maybe it'll work now (maybe it was too soon originally).

**Comment by twmb** [comment]
I don't think it's possible in Go to retract a major version :|

**Comment by twmb** [comment]
Solved by publishing a v2.0.2 which retracted v2.0.0, v2.0.1, and v2.0.2 -- now v2 isn't showing when searching pkg.go.dev

**Comment by nyetwurk** [comment]
You can't do this w/o re-namespacing all of franz-go
```
module github.com/twmb/franz-go/v2
```
and all references need to point to that as well.

**Comment by twmb** [comment]
Not sure what you mean here -- kmsg being a separate module is managed independently.

**Comment by nyetwurk** [comment]
then https://github.com/twmb/franz-go/blob/master/pkg/kmsg/go.mod needs to read
```
module github.com/twmb/franz-go/pkg/kmsg/v2
```

**Comment by twmb** [comment]
It did, in a tag that was immediately deleted. The point is to completely hide v2. It exists in a retracted form only in the gosumdb. I don't want v2 to exist, that's the point.
