### ISSUE TITLE
[Question] using multiple clients in the same process

### ISSUE THREAD

**Issue by voidense** [twmb/franz-go#512]
Hi I have a question -- is it generally advised to use a single client (kgo.Client) or can I use multiple ones (in 1 process)? In my case I have a webserver that needs to produce multiple kinds of events to the same kafka cluster (to different topics). These events have different performance requirements and I'm leaning towards having multiple kgo.Client instances and tune client options differently (for example, different buffer sizes), would be helpful if I can get some insights here, thank you.

**Comment by brunsgaard** [comment]
My take is that both patterns are okay, as long as you keep the number of clients reasonable and if you use more clients there should be a reason for it. You batch size and network overhead will be smaller with two clients, but in most cases you don't care.

**Comment by voidense** [comment]
> My take is that both patterns are okay, as long as you keep the number of clients reasonable and if you use more clients there should be a reason for it. You batch size will be better and network overhead will be smaller with one client, but in most cases you don't care. You are also establishing more connections, but unless you have many many clients it is not an issue for the Network(e.g. nat gateways), Kafka node (conntrack) or Kafka broker

Thanks for chiming in. i don't foresee having more than 3 clients per process and if it ever goes beyond like 5 clients perhaps it's a hint to rearchitect the service. From a global view, we have about 10-20 server instances (pods, we're on k8s) producing to a kafka cluster, so that's <100 clients in total and we should be able to scale out the kafka cluster whenever needed.

**Comment by twmb** [comment]
Multiple clients per process is fine. Using one client is more efficient because the single client is able to create larger batches per produce request. Also, each client connects to every broker, so multiple clients in the same process is a multiplying factor on the number of connections opened. But, if these downsides are alright with you -- then multiple clients is fine (and easier to manage if you need to do different things with each of them)
