### ISSUE TITLE
question: clarify batch producing behavior

### ISSUE THREAD

**Issue by stampy88** [twmb/franz-go#515]
Hi,

I am trying to make sure I understand the batch producing behavior. [Per](https://github.com/twmb/franz-go/blob/master/docs/producing-and-consuming.md#record-reliability), "If a record is ever failed, all records buffered on the same partition are failed.".   Also, [per](https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L326) "Records are
// produced in order per partition if the record is produced successfully". So if I call `ProduceSync(ctx, r1, r2, r3, r4)`, and those records are for the same partition, those records are always produced in order, correct? And if there is an error, all subsequent records are _not_ attempted, e.g. `r2` fails, the library returns and does not attempt `r3` or `r4`. 

Thanks!

**Comment by twmb** [comment]
"and those records are for the same partition" is key, since internally they may go to different partitions (unless you use the ManualPartitioner)
yes to in order, always
Depends on the error -- if r1 and r2 are on the first batch, and r3 and r4 are on the second batch, if the first batch times out, r1 and r2 are failed -- the client will then try r3 and r4. A hard error may fail everything in the partition (say you close the client).

**Comment by stampy88** [comment]
ok, so I need to make sure I am publishing to the same partition, and also ensure that my records don't get split into multiple batches. 

What I am trying to do is consume X number of records from a partition, transform them, and then produce X events to an Event Hub topic. I want to try and not publish out of order so that I can commit things in order, so if there is a failure publishing, I know that I can commit up to the failure point.

**Comment by twmb** [comment]
You can't ensure that your records aren't split into batches.

I did just look and forgot the detail -- all buffered records for a partition are failed, not just the batch.
```go
1306
1307 // failAllRecords fails all buffered records in this recBuf.
1308 // This is used anywhere where we have to fail and remove an entire batch,
1309 // if we just removed the one batch, the seq num chain would be broken.
1310 //
1311 //   - from fatal InitProducerID or AddPartitionsToTxn
1312 //   - from client closing
1313 //   - if not idempotent && hit retry / timeout limit
1314 //   - if batch fails fatally when producing
1315 func (recBuf *recBuf) failAllRecords(err error) {
1316         recBuf.lockedStopLinger()
1317         for _, batch := range recBuf.batches {
1318                 // We need to guard our clearing of records against a
1319                 // concurrent produceRequest's write, which can have this batch
1320                 // buffered wile we are failing.
1321                 //
1322                 // We do not need to worry about concurrent recBuf
1323                 // modifications to this batch because the recBuf is already
1324                 // locked.
1325                 batch.mu.Lock()
1326                 records := batch.records
1327                 batch.records = nil
1328                 batch.mu.Unlock()
1329
1330                 recBuf.cl.producer.promiseBatch(batchPromise{
1331                         recs: records,
1332                         err:  err,
1333                 })
1334         }
1335         recBuf.resetBatchDrainIdx()
1336         recBuf.buffered.Store(0)
1337         recBuf.batches = nil
1338 }
1339
```

**Comment by stampy88** [comment]
ok, so that means from my example, if `r2` failed, it would fail not only `r2`, but `r3` and `r4` as well? Just confirming.

**Comment by twmb** [comment]
yes

**Comment by stampy88** [comment]
Great, thanks!

**Comment by Neal** [comment]
I have a similar use case but there is still a potential race condition where suppose `r4` is about to be buffered so if `r1` fails, `r2` and `r3` will fail but somehow I need to also make sure `r4` fails so I can rollback my internal state and reproduce all the messages back in order.

Any ideas on the implementation?

**Comment by twmb** [comment]
I suggest using transactions, since the client can't control against something that's about to happened but hasn't yet.

**Comment by Neal** [comment]
Makes sense, I don't mean to expect the client to handle it but can implement something on my side too. I was thinking of buffering the records on my side and then calling ProduceSync at some interval (somewhat reimplement what kgo does) -- would ProduceSync be enough here or do you think I'd need transactions?

**Comment by twmb** [comment]
Theoretically? Using transactions is the only way to guarantee. Internally, ProduceSync buffers each messages individually, and there could be a failure in the middle of this buffering.
Practically? Likely will never happen like that.

But, I err on theoretical safety, this sounds like a situation that transactions are meant to solve.

**Comment by Neal** [comment]
Fair enough. I will try it out and get back if I have any more questions. Thanks!
