### ISSUE TITLE
Redpanda: Weird consumer group offsets and message count

### ISSUE THREAD

**Issue by nicodega** [twmb/franz-go#517]
Hi, first of all thank you for such a great library and I'm sorry if what I'm about to report is not really an issue given I don't have much experience with kafka's API details but here it goes:

**Context**:

Using redpanda 23.1.13, franz 1.14.1 and the eos transaction example with some changes (code below):

```go
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/twmb/franz-go/pkg/kgo"
)

var (
	seedBrokers  = flag.String("brokers", "localhost:9092", "comma delimited list of seed brokers")
	group        = flag.String("group", "eos-example-group", "group to use for EOS consuming")
	consumeTxnID = flag.String("consume-txn-id", "eos-example-eos-consumer", "transactional ID to use for the EOS consumer/producer")
)

func die(msg string, args ...any) {
	fmt.Fprintf(os.Stderr, msg, args...)
	os.Exit(1)
}

func main() {
	flag.Parse()

	inputProducer()
	go eosConsumer()

	select {}
}

func inputProducer() {
	cl, err := kgo.NewClient(
		kgo.SeedBrokers(strings.Split(*seedBrokers, ",")...),
		kgo.ProducerBatchCompression(kgo.ZstdCompression(), kgo.SnappyCompression(), kgo.NoCompression()),
		kgo.DefaultProduceTopic("test"),
		kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelInfo, func() string {
			return "[input producer] "
		})),
	)
	if err != nil {
		die("unable to create input producer: %v", err)
	}

	ctx := context.Background()

	e := kgo.AbortingFirstErrPromise(cl)
	rec := kgo.StringRecord("a message")
	rec.Key = []byte("thekey")
	cl.Produce(ctx, rec, e.Promise())
}

func eosConsumer() {
	sess, err := kgo.NewGroupTransactSession(
		kgo.SeedBrokers(strings.Split(*seedBrokers, ",")...),
		kgo.ClientID(uuid.NewString()),
		kgo.RequiredAcks(kgo.AllISRAcks()),
		kgo.AllowAutoTopicCreation(),
		kgo.TransactionalID(uuid.NewString()),
		kgo.DefaultProduceTopic("test"),
		kgo.TransactionalID(*consumeTxnID),
		kgo.FetchIsolationLevel(kgo.ReadCommitted()),
		kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelInfo, func() string {
			return "[eos consumer] "
		})),
		kgo.ConsumerGroup(*group),
		kgo.ConsumeTopics("test"),
		kgo.RequireStableFetchOffsets(),
		kgo.MaxConcurrentFetches(1),
		kgo.SessionTimeout(25*time.Second),
		kgo.UnknownTopicRetries(len(*seedBrokers)),
		kgo.ProducerBatchCompression(kgo.ZstdCompression(), kgo.SnappyCompression(), kgo.NoCompression()),
	)
	if err != nil {
		die("unable to create eos consumer/producer: %v", err)
	}
	defer sess.Close()

	ctx := context.Background()

	for {
		fetches := sess.PollFetches(ctx)

		if fetchErrs := fetches.Errors(); len(fetchErrs) > 0 {
			for _, fetchErr := range fetchErrs {
				fmt.Printf("error consuming from topic: topic=%s, partition=%d, err=%v",
					fetchErr.Topic, fetchErr.Partition, fetchErr.Err)
			}

			// The errors may be fatal for the partition (auth
			// problems), but we can still process any records if
			// there are any.
		}

		if err := sess.Begin(); err != nil {
			// Similar to above, we only encounter errors here if
			// we are not transactional or are already in a
			// transaction. We should not hit this error.
			die("unable to start transaction: %v", err)
		}

		e := kgo.AbortingFirstErrPromise(sess.Client())
		fetches.EachRecord(func(r *kgo.Record) {
			fmt.Printf("read message with key %s", string(r.Key))
			if string(r.Key) == "thekey" {
				rec := kgo.StringRecord("a message")
				rec.Key = []byte("thekey2")
				sess.Produce(ctx, rec, e.Promise())
			}
		})

		committed, err := sess.End(ctx, e.Err() == nil)

		if committed {
			fmt.Println("eos commit successful!")
		} else {
			// A failed End always means an error occurred, because
			// End retries as appropriate.
			die("unable to eos commit: %v", err)
		}
	}
}
``` 

**Expected result**:

Given I'm using a transaction and producing only two records I expect the result of the program execution to read the initially created message and produce a single message onto the same topic, committed when the transaction is finished. I also expect the consumer group to have the Log end Offset and Group offset be the same.

**Actual result**:

Once the transaction is committed the topic shows a message count of 4 on the redpanda console (but only two messages on the list). Also the Log end Offset and Group offset of the consumer group do not match.

**Comment by twmb** [comment]
Transactions send a control record to every partition in the transaction when committing or aborting. The control record is never exposed to consumers, so you can't really commit past it.

You said you're producing two records but I only see one -- did you run this twice?

You can see control records in rpk with `rpk topic consume --print-control-records '%o  %a{control-bit;bool}\n'`

**Comment by nicodega** [comment]
It's producing one record in inputProducer() and another one on the consumer.

Thanks for clarifying the control record, that would explain why the topic shows a total of 4 messages when only two are produced. 

What's weird is that the consumer group offsets consider those records and they are not read, leading to a non existent lag.

**Comment by twmb** [comment]
Control records contribute to offsets, but they are not visible to the client. The client can't commit past them without extra effort because they aren't exposed to the client. The client can't know that the final offset that it isn't reading is a control record, vs. a 1-record batch. The only way a client can commit past a control record is if the record were visible and consumable by the client -- but applications wouldn't know how to handle control records and would need to check if they're a control record before doing anything with them. You can manually opt into this behavior with the KeepControlRecord option and checking yourself (r.IsControl()), but it's more effort for little gain.

**Comment by nicodega** [comment]
I see, that means that unless I manually read those control messages and ignore them using IsControl my consumer groups will always show lag, right?

Again, I'm sorry if these are newbie questions :(

**Comment by twmb** [comment]
Yes, correct

**Comment by nicodega** [comment]
Thanks a lot, that clarifies the issue.
