### ISSUE TITLE
OnPartitionsLost is not waiting for partition consumers to quit

### ISSUE THREAD

**Issue by AlexandrosKyriakakis** [twmb/franz-go#518]
In some rare cases `OnPartitionsLost` happens at the very begging before fetches reach this point.
https://github.com/twmb/franz-go/blob/c1bb2becc3d2749773bf604f0d83506753ba8f5e/examples/goroutine_per_partition_consuming/autocommit_marks/main.go#L164-L172

So in those cases I get a nil pointer dereference at line 172. Because `OnPartitionsLost` killed the consumers (same as `OnPartitionsRevoked`)

Maybe it should be done sequentially as described in the comments similar to `OnPartitionsRevoked`

Can be reproduced by restarting this example many times. 
Usually it happens at the very beginning!

Thanks a lot in advance!

**Comment by twmb** [comment]
I think a way to avoid this is to avoid calling onPartitionsLost in the client if the group was never joined -- right now, onPartitionsLost is _always_ called if join&sync has a failure.

**Comment by twmb** [comment]
OnPartitionsRevoked / OnPartitionsLost used to be one of the only ways to notify of fatal group errors like that -- the other being a hook that required some manual intervention

Now, these errors are also returned from Poll, so it _might_ be alright to avoid Lost on these hard group errors.

**Comment by twmb** [comment]
I think for the time being, I'll add a doc to revoked/lost that these can be called without a group session even starting _if_ there's a hard group bug -- and I'll fix the example.

**Comment by twmb** [comment]
Can you explain the steps you take to trigger the panic?

**Comment by AlexandrosKyriakakis** [comment]
Here is the trace in case it helps. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1056359]

goroutine 62 [running]:
github.com/.../kafka.(*splitConsume).poll.func1({{0x0, 0x0}, {0x0, {0x1534480, 0xc0004b4bb0}, 0x0, 0x0, 0x0, {0x0, 0x0, ...}}})
	/go/src/github.com/.../kafka/consumer.go:176 +0x59
github.com/twmb/franz-go/pkg/kgo.Fetches.EachPartition({0xc000651f50?, 0x2, 0xc0000500b0?}, 0xc000463d00)
	/go/src/github.com/.../vendor/github.com/twmb/franz-go/pkg/kgo/record_and_fetch.go:520 +0x178
github.com/.../kafka.(*splitConsume).poll(0xc000012088, 0xc0000c5000)
```

I'll try to replicate it using the example and I'll come back with instructions.
Thanks a lot!

**Comment by AlexandrosKyriakakis** [comment]
Let me go over the events happening 
- I get `OnPartitionsAssigned` triggered 
- Then I start polling. 
- I get `OnPartitionsLost` triggered and I lose my consumer channels 
- So I get a panic on line 172

Should the polling wait for the next `OnPartitionsAssigned`?
Will another `OnPartitionsAssigned` happen? Or should I create another client in this case?

**Comment by twmb** [comment]
I can't get the third bullet to trigger without the first, and I can't see how a panic can occur if all partitions have been assigned -- OnPartitionsAssigned should be giving all partitions that possibly can be lost. So, there sounds like a bug somewhere, I need to know some exact steps to reproduce it.

**Comment by twmb** [comment]
I'm going to close this in favor of tracking this same issue in #527
