### ISSUE TITLE
Azure Event Hubs: ProduceSync stuck waiting for WaitGroup

### ISSUE THREAD

**Issue by stampy88** [twmb/franz-go#520]
Hi,

Ran into an issue over the past few days that is hard to reproduce, but the outcome is that code is sitting [here](https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L250) even after I cancel the context. I am calling `ProduceSync` from a partition consumer. I have two `kgo.Clients`: one consumer and one producer and am running 1.14.1. Here are the relevant stack traces:
```
goroutine profile: total 68
16 @ 0x43baf6 0x406f9d 0x406a98 0xdef686 0x46f4e1
#	0xdef685	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).handlePartitionsLost.func1+0x65	/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:144

16 @ 0x43baf6 0x44ce6f 0x44ce46 0x46b307 0x47b8cb 0xcf4d59 0xdf5bd6 0xdf1d39 0xe84ded 0xe85386 0xe847fb 0xe844e5 0xe8408f 0xe83b3c 0xdf291d 0xdf5f05 0xdf0a6f 0xdeee99 0x46f4e1
#	0x46b306	sync.runtime_Semacquire+0x26											/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/sema.go:62
#	0x47b8ca	sync.(*WaitGroup).Wait+0x4a											/opt/hostedtoolcache/go/1.20.1/x64/src/sync/waitgroup.go:116
#	0xcf4d58	github.com/twmb/franz-go/pkg/kgo.(*Client).ProduceSync+0x158							/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/producer.go:250
#	0xdf5bd5	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.producer.Send+0x55					/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/producer.go:74
#	0xdf1d38	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.instrumentedProducer.Send+0x158			/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/instrumenting.go:37
#	0xe84dec	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.publisher.SendEvent+0x14c			/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/publisher.go:48
#	0xe85385	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.instrumentedPublisher.SendEvent+0x185		/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/publisher.go:100
#	0xe847fa	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.(*EventProcessor).doPublish+0x13a		/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/processor.go:131
#	0xe844e4	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.(*EventProcessor).processEvent+0x304		/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/processor.go:116
#	0xe8408e	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.(*EventProcessor).processEvents+0x12e		/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/processor.go:86
#	0xe83b3b	github.com/XXXXXX/XXXXXX/internal/pkg/dataformatter.(*EventProcessor).OnRecords+0x15b		/runner/_work/XXXXXX/XXXXXX/internal/pkg/dataformatter/processor.go:53
#	0xdf291c	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.instrumentedRecordListener.OnRecords+0x3bc		/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/instrumenting.go:77
#	0xdf5f04	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.tracingRecordListener.OnRecords+0x164		/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/tracing.go:30
#	0xdf0a6e	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*worker).run+0x1ee				/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:309
#	0xdeee98	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).handlePartitionsAssigned.func1+0x58	/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:88

2 @ 0x43baf6 0x44bd7e 0xc896ae 0x46f4e1
#	0xc896ad	github.com/twmb/franz-go/pkg/kgo.(*Client).reapConnectionsLoop+0x16d	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:557

2 @ 0x43baf6 0x44bd7e 0xced338 0x46f4e1
#	0xced337	github.com/twmb/franz-go/pkg/kgo.(*Client).updateMetadataLoop+0x1f7	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/metadata.go:173

1 @ 0x43baf6 0x406f9d 0x406a98 0xd087ce 0x46f4e1
#	0xd087cd	github.com/twmb/franz-go/pkg/kgo.(*sink).handleSeqResps+0x2d	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/sink.go:410

1 @ 0x43baf6 0x4343b7 0x4699e9 0x4e2b32 0x4e3f19 0x4e3f07 0x56c569 0x57de05 0x71f7fd 0x50f2d8 0x71f9e5 0x71ced6 0x722dcf 0x722dd0 0x49cd3a 0xc8f297 0xc8f260 0x46f4e1
#	0x4699e8	internal/poll.runtime_pollWait+0x88					/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/netpoll.go:306
#	0x4e2b31	internal/poll.(*pollDesc).wait+0x31					/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_poll_runtime.go:84
#	0x4e3f18	internal/poll.(*pollDesc).waitRead+0x298				/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_poll_runtime.go:89
#	0x4e3f06	internal/poll.(*FD).Read+0x286						/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_unix.go:167
#	0x56c568	net.(*netFD).Read+0x28							/opt/hostedtoolcache/go/1.20.1/x64/src/net/fd_posix.go:55
#	0x57de04	net.(*conn).Read+0x44							/opt/hostedtoolcache/go/1.20.1/x64/src/net/net.go:183
#	0x71f7fc	crypto/tls.(*atLeastReader).Read+0x3c					/opt/hostedtoolcache/go/1.20.1/x64/src/crypto/tls/conn.go:788
#	0x50f2d7	bytes.(*Buffer).ReadFrom+0x97						/opt/hostedtoolcache/go/1.20.1/x64/src/bytes/buffer.go:202
#	0x71f9e4	crypto/tls.(*Conn).readFromUntil+0xe4					/opt/hostedtoolcache/go/1.20.1/x64/src/crypto/tls/conn.go:810
#	0x71ced5	crypto/tls.(*Conn).readRecordOrCCS+0x115				/opt/hostedtoolcache/go/1.20.1/x64/src/crypto/tls/conn.go:617
#	0x722dce	crypto/tls.(*Conn).readRecord+0x16e					/opt/hostedtoolcache/go/1.20.1/x64/src/crypto/tls/conn.go:583
#	0x722dcf	crypto/tls.(*Conn).Read+0x16f						/opt/hostedtoolcache/go/1.20.1/x64/src/crypto/tls/conn.go:1316
#	0x49cd39	io.ReadAtLeast+0x99							/opt/hostedtoolcache/go/1.20.1/x64/src/io/io.go:332
#	0xc8f296	io.ReadFull+0x1d6							/opt/hostedtoolcache/go/1.20.1/x64/src/io/io.go:351
#	0xc8f25f	github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).readConn.func2+0x19f	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:1126

1 @ 0x43baf6 0x44bd7e 0xc8ed4d 0xc8fc46 0xc91b6d 0xc91918 0x46f4e1
#	0xc8ed4c	github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).readConn+0x40c	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:1142
#	0xc8fc45	github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).readResponse+0x85	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:1217
#	0xc91b6c	github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).handleResp+0xec	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:1448
#	0xc91917	github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).handleResps+0x77	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/broker.go:1438

1 @ 0x43baf6 0x44bd7e 0xcc1ceb 0xdef7a5 0xdef79f 0xdf033c 0xdefcd0 0xdee205 0xdee194 0x46f4e1
#	0xcc1cea	github.com/twmb/franz-go/pkg/kgo.(*Client).PollRecords+0x2ca						/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer.go:511
#	0xdef7a4	github.com/twmb/franz-go/pkg/kgo.(*Client).PollFetches+0x24						/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer.go:374
#	0xdef79e	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.clientPollerAdaptor.PollFetches+0x1e	/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:182
#	0xdf033b	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).pollFetches+0x15b		/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:246
#	0xdefccf	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).doRun+0x8f			/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:212
#	0xdee204	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).run+0xa4			/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:207
#	0xdee193	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*consumer2).Start.func1.1+0x33		/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/consumer2.go:136

1 @ 0x43baf6 0x44bd7e 0xcc9434 0x46f4e1
#	0xcc9433	github.com/twmb/franz-go/pkg/kgo.(*consumerSession).manageFetchConcurrency+0x153	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer.go:1465

1 @ 0x43baf6 0x44bd7e 0xd076c9 0x46f4e1
#	0xd076c8	github.com/twmb/franz-go/pkg/kgo.(*sink).drain+0xe8	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/sink.go:239

1 @ 0x43baf6 0x44ce6f 0x44ce46 0x46b307 0x47b8cb 0xdef23b 0xdef007 0xcd30c4 0xcd34e3 0x46f4e1
#	0x46b306	sync.runtime_Semacquire+0x26										/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/sema.go:62
#	0x47b8ca	sync.(*WaitGroup).Wait+0x4a										/opt/hostedtoolcache/go/1.20.1/x64/src/sync/waitgroup.go:116
#	0xdef23a	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).handlePartitionsLost+0x15a	/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:153
#	0xdef006	github.com/XXXXXX/XXXXXX/internal/pkg/kafka/franz.(*coordinator).onPartitionsLost+0xe6	/runner/_work/XXXXXX/XXXXXX/internal/pkg/kafka/franz/coordinator.go:123
#	0xcd30c3	github.com/twmb/franz-go/pkg/kgo.(*consumer).initGroup.func2+0x3c3					/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer_group.go:266
#	0xcd34e2	github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).manage+0x3e2						/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer_group.go:350

1 @ 0x43baf6 0x46b6cc 0x46b6ac 0x477f6c 0xcc2230 0x46f4e1
#	0x46b6ab	sync.runtime_notifyListWait+0x12b					/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/sema.go:527
#	0x477f6b	sync.(*Cond).Wait+0x8b							/opt/hostedtoolcache/go/1.20.1/x64/src/sync/cond.go:70
#	0xcc222f	github.com/twmb/franz-go/pkg/kgo.(*Client).PollRecords.func2+0xcf	/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/consumer.go:500
```

I am still looking at it from my end, but wanted to see if anything in these stacks stood out to you.

**Comment by twmb** [comment]
The client forbids failing a batch if there is an unresolved response, but I would expect responses to be resolved. If you're open to it, you can try disabling idempotency. I see in the stack trace that sink.go is handling a produce response, so something is happening. Also, do you have logs from the producer? And maybe consider making them debug logs -- though it'll be very verbose.

**Comment by twmb** [comment]
I think this is something to do with an implementation detail for how I implemented idempotent production... the client will refuse to abort a batch even if you cancel the context or even if it hits the retry limit _if_ doing so will result in your future produce requests to fail.

The client produces records with sequence numbers. If a client produces the sequence number out of order, the client receives OutOfOrderSequenceNumber -- usually this implies data loss. The only way to safely prevent OOOSN is to prevent sequence number resets.

If the client never receives a response for a produce call, then the client cannot know if a batch was received by the broker (and the sequence number is higher) or if the batch was not received by the broker. So, the client retries sending the same batch over and over again (which will be deduplicated due to the sequence numbers) until the client receives a response -- and the client ignores any end-user context cancellation or retry limit.

You can use [UnsafeAbortBufferedRecords](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.UnsafeAbortBufferedRecords) to forcefully cut anything in flight, but this may result in you experiencing a "fatal" error (data loss).

Another option to test if this is the case is to use [DisableIdempotentWrite](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#DisableIdempotentWrite), though your throughput will be lower because the client bounds producing to one request in flight per broker at a time (rather than 5 with idempotent production).

i/o timeouts are a sign of a bigger problem, though. Do you know what this could be from? Are you hitting quotas?

Also, the client needs to open at least one connection per broker -- looks like you have a lot of brokers.

**Comment by stampy88** [comment]
I am talking with MS support to get details on what is going on with Azure Event Hubs, as clearly something is odd. I was thinking quota as well, but based on our tier, that _shouldn't_ be the case. 

Also, it _seems_ like Azure is returning different flavors of the `Host` in the `MetadataResponseBroker`.  I am seeing _19_ different flavors of `addr` (in the short period of time I had logging enabled) in the log statements only differing by case. Wasn't sure if that would cause the library any issues, but wanted to mention it:
```
CENTRalus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
centralus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
Centralus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-PROD-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-PROD-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-Prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-PROD-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-PROd-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-PRod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUS-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRALUs-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTRAlus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENTralus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CENtralus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
CEntralus-prod-xxxxxxxxxx-ns.servicebus.windows.net:9093
```
Need to think about what you said about idempotency. Curious if you know how the confluent library handles something like that. The reason I had canceled the context, was because a rebalance was happening, so the context is canceled after giving the producer a configurable amount of time to finish what it was doing.

Will get back to you when I have more info, thanks.

**Comment by stampy88** [comment]
re: seed_0 - ok, figured it was something like that.

so it looks like they name each node a little differently. Seems really strange considering they resolve to the same IP. Does the kafka protocol use this name, or is it purely the number, e.g. broker `0`, `1`, etc. when communicating? 
```
Metadata for all topics (from broker 0: XXXX://centralus-prod-mqXXX.servicebus.windows.net:9093/0):
16 brokers:
  broker 0 at centralus-prod-mqXXX.servicebus.windows.net:9093 (controller)
  broker 1 at Centralus-prod-mqXXX.servicebus.windows.net:9093
  broker 2 at CEntralus-prod-mqXXX.servicebus.windows.net:9093
  broker 3 at CENtralus-prod-mqXXX.servicebus.windows.net:9093
  broker 4 at CENTralus-prod-mqXXX.servicebus.windows.net:9093
  broker 5 at CENTRalus-prod-mqXXX.servicebus.windows.net:9093
  broker 6 at CENTRAlus-prod-mqXXX.servicebus.windows.net:9093
  broker 7 at CENTRALus-prod-mqXXX.servicebus.windows.net:9093
  broker 8 at CENTRALUs-prod-mqXXX.servicebus.windows.net:9093
  broker 9 at CENTRALUS-prod-mqXXX.servicebus.windows.net:9093
  broker 10 at CENTRALUS-Prod-mqXXX.servicebus.windows.net:9093
  broker 11 at CENTRALUS-PRod-mqXXX.servicebus.windows.net:9093
  broker 12 at CENTRALUS-PROd-mqXXX.servicebus.windows.net:9093
  broker 13 at CENTRALUS-PROD-mqXXX.servicebus.windows.net:9093
  broker 14 at CENTRALUS-PROD-MqXXX.servicebus.windows.net:9093
  broker 15 at CENTRALUS-PROD-MQXXX.servicebus.windows.net:9093
``` 

Thanks for the input on the producing. I look into that more and get back to you with any Azure information I get. Thanks!

**Comment by twmb** [comment]
The name is not used -- it's the number.

**Comment by twmb** [comment]
I could also optionally add an AllowUnsafeFailedBatches (need to workshop the name here maybe) as a workaround for you trying to fail unresolved records -- this would need to wait for 1.15 and well, this is currently the only idea that would be in 1.15 and 1.14 just released.

**Comment by stampy88** [comment]
Hi @twmb, MS support has come back and said that they were upgrading OSes on the Event Hub Service during this time and any errors should have been transient. I am trying to get more details on why your retries didn't resolve the problem.

**Comment by stampy88** [comment]
MS support is claiming that the error is probably caused by a misconfigured client. Here are their producer config recommendation: https://learn.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations#producer-configurations-only
I'll try finding the knobs for all of these and ensure they are within their guidelines and report back.

**Comment by stampy88** [comment]
I think this how your library matches up with the recommended settings. I need to make a few adjustments

| propery                 | recommended                                | Franz setting(s)         | Franz default | App override |
|-------------------------|--------------------------------------------|--------------------------|---------------|--------------|
| metadata.max.age.ms     | 180000 (3 min)                             | MetadataMaxAge           | 5 minutes     |              |
| connections.max.idle.ms | 180000 (3 min)                             | ConnIdleTimeout          | 20 seconds    |              |
|                         |                                            |                          |               |              |
| Producer specific       |                                            |                          |               |              |
| max.request.size        | 1000000                                    | ProducerBatchMaxBytes    | 1000012       |              |
| retries                 | > 0                                        | RecordRetries            | unlimited     |              |
| request.timeout.ms      | 60000 (1 min)                              | ProduceRequestTimeout    | 10 seconds    |              |
|                         |                                            | RequestTimeoutOverhead   | 10 seconds    |              |
| metadata.max.idle.ms    |  180000 (3 min)                            | NONE                     |               |              |
| linger.ms               | > 0                                        | ProducerLinger           | not set       |              |
| delivery.timeout.ms     | (request.timeout.ms + linger.ms) * retries | RecordDeliveryTimeout    | not set       |              |
| compression.type        | none                                       | ProducerBatchCompression | snappy, none  | none         |
|                         |                                            |                          |               |              |
| Consumer specific       |                                            |                          |               |              |
| heartbeat.interval.ms   | 3000 (3 seconds)                           | HeartbeatInterval        | 3 seconds     |              |
| session.timeout.ms      | 30000                                      | SessionTimeout           | 45 seconds    |              |
| max.poll.interval.ms    | > session.timeout.ms                       | NONE                     |               |              |

**Comment by twmb** [comment]
Just note that having a limited amount of retries may eventually run into the idempotent problem.
Internally, the code just warns loudly, fails everything buffered, resets sequence numbers, and then continues.

**Comment by stampy88** [comment]
@twmb not a big surprise, but those settings had no effect. Unfortunately Event Hub has been upgraded at this point too, so this problem is not occurring. Besides the broker metadata via the Metadata Response, is there anything else you use to when publishing? It almost looks like, to make analogy, that we are publishing to something like nginx, but one of the upstream nginx is talking to is unavailable, so we just get read timeouts waiting for a response.

**Comment by twmb** [comment]
I haven't ever talked to a broker that's completely unresponsive -- the only time I've ever seen this is when I was throttled from Azure years ago when testing. Do debug logs show anything about quotas being hit? Can you increase the connection timeouts and req timeout overhead significantly to see if a reply is _ever_ received?

**Comment by stampy88** [comment]
Oh, another tidbit: it _never_ recovered, only after a restart would it make progress.

**Comment by twmb** [comment]
The connection or the client? And, what if you call UnsafeAbortBufferedRecords?

**Comment by stampy88** [comment]
I mean the produce never recovered. You could see it timing out and retrying, but only after a restart of the client did it work for some period of time. I could probably grab logs from last week that show what it was doing if you are interested. If this happens again, I'll try `UnsafeAbortBufferedRecords`.

**Comment by twmb** [comment]
I don't understand why Azure would permanently forbid connections -- that part makes no sense to me (and does sound somewhat potentially similar to throttling).

**Comment by stampy88** [comment]
I completely agree, but unfortunately I am not getting enough details out of them to be able to understand why the connection never succeeded. They are just going through their normal checklist of "you have to use recommended settings". They wouldn't give me more details until that was in place. I am asking for an maintenance schedule for EventHubs so that I can hopefully see this problem again. Once their maintenance window was over, the problem went away after the app was restarted, so everything is fine at this point.

**Comment by twmb** [comment]
Non-connecting brokers could also imply that the IP is cached even though the IP behind the scenes changed.

**Comment by stampy88** [comment]
Yeah, I thought the same thing, but it _appears_ that the IP never changed. I am re-asking that question.

**Comment by twmb** [comment]
I don't think there's anything that can be done for this issue, I'm going to close this for now until Azure gets back to you, if this persists.

**Comment by stampy88** [comment]
@twmb, I had an issue with Azure over the weekend where it again shows producers blocked. Stacks are very similar. On the Azure side there is a "Server Busy" error logged, while on my side all I see are timeouts, e.g.
```
kafka.loggingHooks.OnBrokerE2E - read tcp 10.83.2.40:47474->20.98.147.1:9093: i/o timeout
```

I am trying to recreate this as it appears from their [documentation](https://learn.microsoft.com/en-us/azure/event-hubs/apache-kafka-troubleshooting-guide#server-busy-exception) that the AMQP version you will get the "server busy exception", while for Kafka #

> In Kafka, messages are delayed before being completed. The delay length is returned in milliseconds as throttle_time_ms in the produce/fetch response. In most cases, these delayed requests aren't logged as server busy exceptions on Event Hubs dashboards. Instead, the response's throttle_time_ms value should be used as an indicator that throughput has exceeded the provisioned quota.

There is another part of that documentation that seems like incorrect behavior to me, but wanted to verify with you:

> If the traffic is excessive, the service has the following behavior:
>>If produce request's delay exceeds request time-out(request.timeout.ms), Event Hubs returns **Policy Violation error code**.
If fetch request's delay exceeds request time out, Event Hubs logs the request as throttled and responds with empty set of records and no error code.

When trying to recreate this, I am able to see that `Policy Violation` error and it is a non-retryable error. Here is a snippet from my logs:
```
DEBU[0037] read Produce v7                               Function=kafka.loggerAdaptor.Log Source="logger.go:61" broker=0 bytes_read=62 err="<nil>" read_wait="68.747µs" time_to_read=18.993445551s
INFO[0037] broker is throttling us in response           Function=kafka.loggerAdaptor.Log Source="logger.go:55" broker=0 req=Produce throttle_millis=6000 throttles_after_resp=true
WARN[0037] Client is being throttled                     Function=kafka.loggingHooks.OnBrokerThrottle Source="logging.go:51" node_id=0 throttle_interval=6s throttled_after_response=true
INFO[0037] batch in a produce request failed             Function=kafka.loggerAdaptor.Log Source="logger.go:55" broker=0 err="POLICY_VIOLATION: Request parameters do not satisfy the configured policy." err_is_retryable=false max_retries_reached=false partition=5 topic=test-topic
DEBU[0037] produced                                      Function=kafka.loggerAdaptor.Log Source="logger.go:61" broker=0 to="test-topic[5{err@0,1(POLICY_VIOLATION: Request parameters do not satisfy the configured policy.)}]"
WARN[0037] Producer 16 failed to send message: POLICY_VIOLATION: Request parameters do not satisfy the configured policy.  Function=main.runProducer Source="main.go:178"
```

Is Azure sending a policy violation the correct way that should be handled? I am still trying to replicate the exact error that occurred, but wanted to bring this to your attention in case this was unexpected.

**Comment by twmb** [comment]
https://github.com/twmb/franz-go/blob/fc65dcf31405fdf13ee1c2b35a1a3d96559c3d2e/generate/definitions/00_produce#L153

Azure is handling this incorrectly.

https://github.com/twmb/franz-go/blob/fc65dcf31405fdf13ee1c2b35a1a3d96559c3d2e/pkg/kversion/requests.go#L356

The DSL is a bit jank and hard to understand, but v6 of the produce request switched from throttling before a response is sent to throttling after a response is sent. In fact, the scenario you're describing is literally the scenario in the Motivation section of the KIP proposing the change:

https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74685726#KIP219Improvequotacommunication-Motivation

Azure is replying to a v7 request, so it should throttle _after_ the response. The client wont send a request, there will be no problem. If the client does send a request before throttling elapses, the server can then do whatever it wants (throttle until disconnect).

Even if this were v5 and before, Azure would be handling this wrong: Azure is choosing to send an error for throttling, but that is not documented behavior for clients, and clients are not programmed to handle policy violation on produce. It's a non-retryable request and triggers records to be failed.

They also aren't handling fetch correctly: they should still return data even while throttling. It sounds like they've implemented fetch throttling with pre-KIP-219 behavior, albeit without returning data. That's less of a problem since clients can handle no data being returned.

**Comment by stampy88** [comment]
Thanks for confirming. I'll open a ticket and continue trying to reproduce the original issue.

**Comment by stampy88** [comment]
Hi @twmb, any thoughts on the above?

**Comment by twmb** [comment]
> Is that accurate?

Accurate

> Do you know where I can find that?

Sure. Since every company seems reticent to do any work for any question that doesn't directly contain evidence from the Java client,

https://github.com/apache/kafka/blob/8c71ab03b59324249b59139f105ebd023e385e66/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java#L816

Feel free to send them that line. There is nowhere in the Java client codebase that handles RequestTimedOut as a signal to reset sequence numbers. There are some minor caveats but they wouldn't apply for what Microsoft is doing there.

**Comment by stampy88** [comment]
I have an update on this, @twmb. MS specifically changed what error they return on the OOSN scenario because of a problem with how libkafka was handling it. [This](https://github.com/confluentinc/librdkafka/issues/3584) kinda looks like it may be what they were referring to, but they do have a non-public config that can be changed to return the correct error. When they changed this, the producer no longer has issues. They are going to have a fix for this shortly:

> we are working on a change on our side to automate the error code change (as oppose to a manual config change) based on information from client SDKs (client SDK after certain version, does pass SDK info to broker).
> that work is schedule to complete and deploy by beginning of September.
 
Also, for the api version problem, they are going to fix that too:

> apiversion investigation - we repro this one using a version of Franz-go that does not have the work around and we plan to fix that part by September.

They are still investigating the issue where they aren't handling throttling correctly:

> throttling (for produce) investigation - we are in the process of debugging this one, I don't have a conclusion on that one yet but this is being investigated and if any fix is required, we will fix is as a hotfix on our side as well.

**Comment by twmb** [comment]
That comcast link is private, I can't open it logged in nor in a private window.

I'm really curious what librdkafka wasn't handling properly... or maybe it's me?

Good(ish) news on the other bits, though odd. ApiVersions is more tolerant on my side now fwiw, it turns out I was handling it incorrectly originally, but I'm handling it correctly now.

**Comment by stampy88** [comment]
doh! fixed the link

**Comment by stampy88** [comment]
@twmb in case you didn't see I fixed that link

**Comment by twmb** [comment]
@stampy88 finally took a look at the proper link and, unsurprisingly, understanding the code change requires wayyyy more effort than I'm going to put in. But, interesting!

I wonder if they have any updates for the fixes; looks like opentelemetry is running into the v4 problem as well in #1102, and I wonder if the throttle problem has been fixed.
