### ISSUE TITLE
How to connect to secure Kafka using tls?

### ISSUE THREAD

**Issue by kant777** [twmb/franz-go#521]
I current have values set for the following fields to connect to secure kafka in the kafka client config and pass it on to console consumer. How can I achieve the same using this library? Specifically I did not see a way to pass the `ssl.truststore.password` and `ssl.key.password` in tls.Config. so I am not sure how to pass them?

```
ssl.truststore.location
ssl.truststore.password
ssl.keystore.location
ssl.keystore.password
ssl.key.password
security.protocol=SSL
```

**Comment by twmb** [comment]
Truststores are a Java concept -- you'll need to convert the truststore to a PEM or some other key format that can be parsed into a tls.Config. Password encrypted certs are also rare and require an external (community) library -- there is no password protected cert package within the Go stdlib.
