### ISSUE TITLE
Weird issue with TLS config

### ISSUE THREAD

**Issue by xgalaxy** [twmb/franz-go#522]
On v1.13.0

I was trying to configure the Kafka client with TLS via the option `kgo.DialTSLConfig(new(tls.Config))`.  Looking at the code, it configures the dialer with a server name extracted from the broker in `client.go` if the tls config `ServerName` is empty.

However, when it attempts to connect I get the error:
```unable to dial: tls: failed to verify certificate: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs```

But if I create my own TLS config like so:
```
tlsConfig := &tls.Config{
   ServerName: "<same_host_as_broker>",
}
```
And pass it into the `kgo.DialTLSConfig` then it successfully authenticates the certificate and I'm able to connect to the broker.

`<same_host_as_broker>` is the same `hostname:port` that I pass to the seed brokers. And this is the same hostname:port that lands into `client.go` when its setting the `ServerName` automatically if it is not set.

So I don't understand why me manually passing the `tls.Config` fixes the issue.

**Comment by twmb** [comment]
What broker hostnames are returned from a metadata response?

**Comment by xgalaxy** [comment]
An ip address is returned instead of a hostname. Is this a broker config issue?

**Comment by xgalaxy** [comment]
It was definately the `advertised.listeners` setting on the broker.
Sorry for troubling you.
