### ISSUE TITLE
Question: support for per-partition maxPollRecords

### ISSUE THREAD

**Issue by alistairking** [twmb/franz-go#525]
Hey again.

I have some clients that consume from a bunch of somewhat unevenly populated partitions, and the per-message consumption is rate limited (downstream of the consumer) roughly on a per-partition basis.
From what I can tell, my consumers throughput currently is not much higher than the rate limit for 1-2 partitions. I assume this is because each PollRecords call is getting a chunk of messages from only a couple of the ~50 partitions assigned to each consumer (i.e., it prefers to satisfy the limit by draining a couple of partitions rather than taking 1/N messages from each partition).

I think -- though maybe I'm not thinking clearly -- it would help throughput if I could configure the client to treat  `maxPollRecords` as a per-partition maximum.

Does this make sense? 
I took a quick look at the code and it seems like it would be possible, but perhaps not trivial, to allow this.

**Comment by twmb** [comment]
What happens if you bump FetchMaxPartitionBytes?

**Comment by alistairking** [comment]
Wouldn't that make the problem worse? Each partition would have more data fetched and it would be more likely that the entirety of the maxPollRecords budget would be consumed by a single partition?

**Comment by twmb** [comment]
Sorry, lowering then.

Also, are you saying that all the data is buffered within the client but you're trying to only consume a subset of every buffered partition?

**Comment by alistairking** [comment]
Yeah, that could work. I'll take a look at it.

I think so, yeah.

Currently a client might have 100 partitions assigned, and let's say that consumption of each partition is rate-limited (downstream) by 1k msgs/sec. I'm trying to figure out the best way to consume from those 100 partitions such that each partition is being consumed at 1k msgs/sec (max). 
Right now I'm configuring maxPollRecords to ~`partitions*1000`, so I'm seeing polls for 100,000 messages that take ~60s to consume. My inference here is that those 100k messages are coming from only a couple of partitions, whereas if I was able to get 100k messages from 100 partitions the throughput would increase significantly.

**Comment by twmb** [comment]
The only knob the client has when fetching is the per-partition fetch bytes. Adding an option to poll by partition may just result in your application being slower -- if A and B have 10k records buffered, but C, D, and E have only 15, if you try to poll 100 records per partition, then A and B will take a really long time to drain.

**Comment by alistairking** [comment]
Yeah, that's a fair point. 
It's a real pity that Kafka doesn't have a knob for the max number of messages fetched per partition. A bytes based limit is hard to reason about in these situations.

One last try: what if PollRecords consumed buffered fetches more evenly? So rather than eagerly consume from the first partition, it would stripe consumption across all partitions.

**Comment by twmb** [comment]
Much more inefficient implementation wise. I'm open to adding it as a feature, `StripePollRecords() ConsumerOpt`or something. That said, in the end, what's the benefit? Internally, another fetch does _not_ get issued until the prior fetch is completely drained. You'll stripe-drain the low-record partitions evenly, and then once they're empty, you'll hit the same big-batch-partition behavior you're hitting right now. I _think_ that'd be the same problem you're running into today, but reversed?

**Comment by alistairking** [comment]
I see what you're saying. We'd get blocked toward the end of draining the fetch while the big partitions are drained. 

I guess it would only be beneficial if the problem is less about partition imbalance and more about per-partition throughput.
If the partitions are roughly balanced, then I'd see the poor throughput I'm seeing now, but striped polls would help because I'd be able to keep my per-partition consumers busier.

Given that this isn't going to perform well and we're not sure it'll even help, I think I'm best to play with FetchMaxBytes and see if I can make that do what I want.

**Comment by twmb** [comment]
(also FetchMaxPartitionBytes -- very important that this one controls the per partition aspect)

**Comment by twmb** [comment]
Worth closing this then?
