### ISSUE TITLE
ipv6 addr not supported

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#53]
```
if colon := strings.IndexByte(addr, ':'); colon > 0 {
			port64, err := strconv.ParseInt(addr[colon+1:], 10, 64)
			if err != nil {
				return nil, fmt.Errorf("unable to parse addr:port in %q", seedBroker)
			}
			addr = addr[:colon]
			port = int32(port64)
		}
```
you need to use net.SplitHostPort func

**Comment by vtolstov** [comment]
may be fix for this issue in https://github.com/twmb/franz-go/pull/56

**Comment by twmb** [comment]
Hey there! I commented on that PR, if you'd like to address the comments I can merge it and close this?

**Comment by vtolstov** [comment]
thank, yes i'm plan to finish it

**Comment by twmb** [comment]
I've modified your existing commit and cherry-picked it to the main branch, thanks! This will be tagged in the next release (this week, probably later in the week).

**Comment by vtolstov** [comment]
Thanks, sorry for delay, very busy at work.
