### ISSUE TITLE
MaxConcurrentFetches and number of brokers/partitions

### ISSUE THREAD

**Issue by vmihailenco** [twmb/franz-go#532]
Let's say I have:

- 3 brokers
- 1 topic with 3 partitions
- 3 consumers

Each consumers consumes a single topic partition. How many concurrent fetches a consumer can have?

The documentation implies that each consumer will have 3 concurrent fetches, because I have 3 brokers.

Could you help me understand how there can be 3 concurrent fetches to a single partition? Would not that break the order in which records are processed? Or each fetch returns the same data?

Also I don't quite understand how `FetchMaxBytes` and `FetchMaxPartitionBytes` play together. If I am consuming a single partition, then a fetch request can't be larger than `1 * FetchMaxPartitionBytes`, but it does not seem to be the case...

**Comment by vmihailenco** [comment]
>MaxConcurrentFetches is the upper bound per client. If MaxConcurrentFetches == 3:

I don't understand why I will have 3 concurrent fetches if a client is consuming a single partition. The first fetch is obvious, but why other 2 are needed? Do they retrieve data in advance? Or they are simply duplicates?

>I don't know what you mean by "it does not seem to be the case"?

I am consuming a single partition so I expect that I only need to configure `FetchMaxPartitionBytes`. But reality check shows that I also need to configure `FetchMaxBytes` or the client consumes a lot more RAM than expected.

By your explanation it also looks like I need to configure `MaxConcurrentFetches`, but I did not touch it. To reduce memory consumption, I had to configure `FetchMaxBytes` even if a single/node client is consuming a single partition.

It works, but I have no idea why.

**Comment by twmb** [comment]
If a client is consuming a single partition, you'll have one fetch. The configuration setting is a limit, not a must-be-this requirement. Max doesn't mean ExactlyAlways.

Also yes -- please confirm the number of topics and partitions you're consuming.

**Comment by vmihailenco** [comment]
>Also yes -- please confirm the number of topics and partitions you're consuming.

I have:

- 4 servers/consumers/clients
- 4 kafka brokers
- 2 topics
- 1 topic with 8 partitions; each consumer consumes 2 partitions
- 1 topic with 4 partitions; each consumers 1 partition

I had to lower `FetchMaxBytes` from the default 50mb to 4mb and observed a reduction in memory consumption ~512mb. I am using ZSTD and the data is highly compressible.

`FetchMaxPartitionBytes` is the default 1mb. `MaxConcurrentFetches` is not configured.

I am using https://github.com/twmb/franz-go/tree/master/examples/group_consuming with manual committing.

>If a client is consuming a single partition, you'll have one fetch. The configuration setting is a limit, not a must-be-this requirement. Max doesn't mean ExactlyAlways.

Okay, sounds like I don't need to touch it.

**Comment by twmb** [comment]
The max bytes applies as the data is written on the wire. If your data is highly compressible, then it makes sense that lowering the max bytes by 46M results in a reduction in memory consumption by 512M -- the data is is decompressed _after_ being read, so it is possible that your 46M decompressed to 512M.

I don't think there's anything to do here so I'll close this for now.
