### ISSUE TITLE
Consumer Group support for Kafka 0.8.x?

### ISSUE THREAD

**Issue by abrahamajayk** [twmb/franz-go#533]
How does this library support Consumer Groups for legacy versions of Kafka older than 0.9.

Before the introduction of consumer offset tracking in 0.9, consumer groups used ZooKeeper for offset tracking. Is this supported in the library.

**Comment by twmb** [comment]
This library does not natively work with Zookeeper. You'll have to manage the offsets yourself.
I don't think any Go-based Kafka library natively talks to ZK and handles groups that don't use CG APIs.
