### ISSUE TITLE
Question on EOS

### ISSUE THREAD

**Issue by madshov** [twmb/franz-go#534]
Hi all,
I'm trying to understand the concept of Kafka and EOS and I came across this library which should have full support as far as I understand. I looked at the examples provided with this repo, especially this one: https://github.com/twmb/franz-go/blob/master/examples/transactions/eos/main.go
I'm clearly missing some basic understanding and I guess I have many questions, but to begin with, does EOS require beginning and committing a transaction like in the provided example?

**Comment by ssorren** [comment]
Probably not a question for this library, EOS is provided through transactions...so yes. The idea is that you when you consume a record, and during the processing you produce records on another topic, the 'commit' of the incoming records is in the same transaction as the records you produce on other topics....

So, anyone consuming the records you produce, will not see them until the transaction is complete (assuming your other consumer is configured correctly)...

If you error out before the transaction is complete, both the commit and produced records would be discarded.

Once you commit an offset, you will never read that offset again, so you will never produce any records for that offset again.
Hence Exactly Once 

There is a bit of a misnomer here, as if you fail in the middle of a transaction, you will consumer the incoming record more than once.

Hope that helps
