### ISSUE TITLE
Suggestions on how to most accurately create a span for a batch of records?

### ISSUE THREAD

**Issue by sgtsquiggs** [twmb/franz-go#539]
We process data as in batches - we primarily want to see the span linking consuming from kafka and writing to postgres. We've got to pass a context down but there may be thousands of individual record spans in our batch.

Suggestions? Anyone else already tackling this?

(this is with otel/kotel)

**Comment by twmb** [comment]
Let me know if you have a proposal and I'll reopen -- closing for now.

**Comment by sgtsquiggs** [comment]
I’m thinking of a parent span for the individual records, but i don’t have an elegant way to expose it yet
