### ISSUE TITLE
Stop consuming topic without affecting production

### ISSUE THREAD

**Issue by jalaziz** [twmb/franz-go#543]
Admittedly, I believe this could be solved by using multiple clients.

However, it would be nice to be able to stop consuming a topic (and trigger a rebalance), but not affect production.

While it's possible to add topics to consume with `AddConsumeTopics`, the closest method for stopping consumption I've found is `PurgeTopicsFromClient`. However, `PurgeTopicsFromClient` has implications for production which is not ideal. Another option would be `PauseFetchTopics`, but that doesn't seem to trigger a rebalance.

Is the best practice to separate production and consumption with different clients in this case?

**Comment by twmb** [comment]
You're producing to and consuming from the same topic with the same client?

**Comment by jalaziz** [comment]
> You're producing to and consuming from the same topic with the same client?

Well, I was following the example from the README which uses the same client for production and consumption.

**Comment by twmb** [comment]
Oh yes, it's perfectly valid to do so -- just not the most common. I think PurgeTopicsFromProducing and PurgeTopicsFromConsuming are valid to add. This is the first new feature request that would trigger v1.15 and is a bit lower priority -- and I'm going to be out of town for a bit. I think an interim option is to use two clients, is that alright?

**Comment by jalaziz** [comment]
> Oh yes, it's perfectly valid to do so -- just not the most common. I think PurgeTopicsFromProducing and PurgeTopicsFromConsuming are valid to add. This is the first new feature request that would trigger v1.15 and is a bit lower priority -- and I'm going to be out of town for a bit. I think an interim option is to use two clients, is that alright?

Yup. Two clients is not an issue for the time being. Thanks for the info!
