### ISSUE TITLE
Feature request: add MaxBufferedBytes in addition to MaxBufferedRecords

### ISSUE THREAD

**Issue by vmihailenco** [twmb/franz-go#544]
`MaxBufferedRecords` option works well if all Kafka messages have similar size, but that is not always the case. For example, we have messages that can differ by an order of magnitude: 1KB, 10KB, and 100KB.

What do you think about adding `MaxBufferedBytes(number_of_bytes)` option? The client would need to track the total size of all messages (size of `Record.Value` field) in the buffer and `TryProduce` would refuse to add more messages if the limit is reached.

**Comment by twmb** [comment]
Yes, possible. Adding for v1.15, might come in a month (depending).

**Comment by vmihailenco** [comment]
Thank you!
