### ISSUE TITLE
Out-of-band kadm.CommitOffsets() hit panic SIGSEGV inside kgo.(*cursor).setOffset(...) function

### ISSUE THREAD

**Issue by ns-gzhang** [twmb/franz-go#545]
Actually we are not sure if that's from `kadm.CommitOffsets()` as log didn't show the caller in our app code, but the panic is next to a log for the kadm call. I did a quick search in the issue history, didn't seem to be a known issue.

Here are the details:
Golang 1.20.6
kadm v1.8.1
Some log output:
```
{"l":"INFO","ts":"2023-08-25T20:47:31.905Z","n":"dem_page","c":"input/reader.go:231","msg":"committing offsets","partition":13,"offset":{"Topic":"ch_event_page","Partition":13,"At":40226111988,"LeaderEpoch":17,"Metadata":""}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xfc1d2d]

goroutine 773130 [running]:
github.com/twmb/franz-go/pkg/kgo.(*cursor).setOffset(...)
	/go/pkg/mod/github.com/twmb/franz-go@v1.13.5/pkg/kgo/source.go:203
github.com/twmb/franz-go/pkg/kgo.(*consumerSession).handleListOrEpochResults.func2()
	/go/pkg/mod/github.com/twmb/franz-go@v1.13.5/pkg/kgo/consumer.go:1679 +0xed
github.com/twmb/franz-go/pkg/kgo.(*consumerSession).handleListOrEpochResults(0xc001e8c7e0, {0x80000000, {0xc0044d7490, 0x1, 0x1}, 0x0})
	/go/pkg/mod/github.com/twmb/franz-go@v1.13.5/pkg/kgo/consumer.go:1694 +0x6d9
github.com/twmb/franz-go/pkg/kgo.(*consumerSession).listOrEpoch(0xc001e8c7e0, {0xc0000333e0?, 0x0?}, 0xd0?, {0x1421e8c?, 0xc01740e768?})
	/go/pkg/mod/github.com/twmb/franz-go@v1.13.5/pkg/kgo/consumer.go:1621 +0x98a
created by github.com/twmb/franz-go/pkg/kgo.listOrEpochLoads.loadWithSession
	/go/pkg/mod/github.com/twmb/franz-go@v1.13.5/pkg/kgo/consumer.go:1241 +0x115
```
Config for the reader - it's a single partition reader without a consumer group, and relevant code lines:
```
opts := []kgo.Opt{
		kgo.SeedBrokers(brokers...),
		kgo.ConsumePartitions(topicPartitionOffset),
		kgo.ConsumeResetOffset(kgo.NewOffset().AtStart()),
		kgo.FetchMaxBytes(maxPartBytes),
		kgo.FetchMaxPartitionBytes(maxPartBytes),
		kgo.FetchMaxWait(time.Second),
		kgo.FetchMinBytes(int32(r.MinBytes)),
		kgo.RetryTimeout(0), // no retry timeout (does not apply to fetch and produce)
		kgo.RetryBackoffFn(func(n int) time.Duration {
			return 1 << (n % 6) * time.Second // up to 32 seconds
		}),
	}
client, err := kgo.NewClient(opts...)
...
admClient := kadm.NewClient(client)
...
for {
        fetches := client.PollFetches(context)
        if errs := fetches.Errors(); len(errs) > 0 {
                continue
        }
        fetchesC <- &fetches
        offsets := kadm.OffsetsFromFetches(fetches)
        commitC <- offsets     <= sent over through a channel for commit
}
...
for commitOffsets := range commitC {
        offset := commitOffsets[Topic][Partition]
        log.Infow("committing offsets", "partition", Partition, "offset", offset)    <= this produced the log before the panic
        _, err := admClient.CommitOffsets(context.Background(), consumerGroup, commitOffsets) <= consumerGroup is just a string
}
```
The offsets is chosen every 30 seconds just for lag tracking use. There is no other delay from extracting offsets from fetches to `CommitOffsets()` other than the channel delay.
The panic happened occasionally after long run over 2 hours with very busy messages (full speed playing the messages).
@twmb not sure if you could help spot the usage issue quickly, or it's something inside kgo driver? Thanks!

**Comment by twmb** [comment]
Is this repeatable?

**Comment by ns-gzhang** [comment]
It's seen about 3 times in 2 days. There were no other errors from the log.

I added more details to the code snippet above. if `PollFetches` returns an error, the code will not get to the offset extraction. And this app is purely consuming, no producer involved at all.

Is it possible due to the async nature that when the code reaches the `CommitOffsets` call, things changed? BTW, the brokers are Kafka in this case.

If it's related to timing, we will just add `recover` to capture the panic, which is a better practice anyway. We just didn't expect that. Thanks!

**Comment by twmb** [comment]
It’s unrelated, there’s definitely a problem, you should not need to recover

**Comment by twmb** [comment]
Then given that^^, this should be even more unrelated.

Is it possible to enable debug logs on the consumer client (the one that is panicking) for long enough to capture what's happening before this panic? I'm staring at a bunch of the source and am not seeing how the field can be nil there.

I'm not sure debug logs will help much but it may give me a lead to look into.

**Comment by ns-gzhang** [comment]
I'm afraid we couldn't enable the debug log. We are skipping the out-of-band commits for now as we can calculate lag based on fetches alone. It was for Google PSL topics.

Is it possible that a pod OOM could result in a nil pointer returned?

**Comment by twmb** [comment]
> Is it possible that a pod OOM could result in a nil pointer returned?

I have no clue about this -- perhaps possible, but I'd expect the pod to crash, rather than continue with a bad alloc?

**Comment by ns-gzhang** [comment]
My team member observed that the panic seemed to correlate with OOM crashes, although some panics were able to be logged before OOM crashes, and some probably not. We have increased the memory limit, but also disabled the out-of-band commits as they are optional for the moment. It seems to be quiet now. Thanks.

**Comment by twmb** [comment]
Interesting ... if you re-enable the out-of-band commits and the panics do not come back, I think we have a pretty good signal as to the panic being from the OOM. Should we close this for now?

**Comment by ns-gzhang** [comment]
Yes. Thanks.
