### ISSUE TITLE
schema caching

### ISSUE THREAD

**Issue by dhtong** [twmb/franz-go#547]
hi, we followed the example [here](https://github.com/twmb/franz-go/blob/master/examples/schema_registry/schema_registry.go) to register serde. and only initialize it once when a new partition is assigned. in our datadog metrics, we are seeing high schema registry request count. it roughly equals to the message count. is there anything we need to do to cache schema? or is this a data/metric export issue with datadog?

**Comment by twmb** [comment]
Hey there, do you have a sample of your own code?

In the example, `rcl` is the only variable that talks to the schema registry. The `serde` variable does not -- it only serializes and deserializes.

**Comment by dhtong** [comment]
yep.
```
func (c *Consumer) Setup(ctx context.Context) error {
	logging.Infof(ctx, "setting up consumer...")
	// load all schemas version and register with des
	traceSchemas, err := c.registryClient.Schemas(ctx, c.traceTopic+"-value", sr.HideDeleted)
	if err != nil {
		return errors.Wrap(err, "failed to get schema")
	}
	for _, traceSchema := range traceSchemas {
		traceDes, err := compiler.CompileSchemaBytes([]byte(traceSchema.Schema.Schema), []byte(avrorecords.NewUnionNullTraces().Schema()))
		if err != nil {
			return err
		}
		c.traceSerde.Register(
			traceSchema.ID,
			avrorecords.NewUnionNullTraces(),
			sr.DecodeFn(func(b []byte, v interface{}) error {
				l, ok := v.(*avrorecords.UnionNullTraces)
				if !ok {
					return errors.New("wrong dest type")
				}
				r := bytes.NewReader(b)
				return vm.Eval(r, traceDes, l)
			}),
		)
	}

	decodedTraceSchema, err := c.registryClient.SchemaByVersion(ctx, c.decodedTraceTopic+"-value", -1, sr.HideDeleted)
	if err != nil {
		return errors.Wrap(err, "failed to get latest sink schema")
	}
	c.decodedTraceSerde.Register(
		decodedTraceSchema.ID,
		avrorecords.NewUnionNullDecoded_traces(),
		sr.EncodeFn(func(v interface{}) ([]byte, error) {
			dl, ok := v.(*avrorecords.UnionNullDecoded_traces)
			if !ok {
				return nil, errors.New("cannot serialize for type")
			}
			var buf bytes.Buffer
			e := dl.Serialize(&buf)
			if e != nil {
				return nil, errors.Wrap(e, "failed to serialize")
			}
			return buf.Bytes(), nil
		}),
	)
	return nil
}
```
forgot to mention, our kafka provider is redpanda.

**Comment by twmb** [comment]
That looks good -- what's the produce or consume func look like? Is Setup called every time something is produced?

**Comment by dhtong** [comment]
only `OnPartitionsAssigned`. i checked the log on `setting up consumer...`. setup should be called correctly and very few times. this is also the only place `sr.Client` is used

**Comment by twmb** [comment]
Well, that's odd -- that sounds correct. OnPartitionsAssigned will be called on every rebalance, but that should be very few times.

**Comment by dhtong** [comment]
maybe it's a data export issue. i will ping redpanda. thank you!

**Comment by dhtong** [comment]
just a fyi. i've bisected the code and `kgo.Client.Produce()` caused the schema registry request count (a count on `redpanda_schema_registry_request_latency_seconds`) to go up.
