### ISSUE TITLE
Consuming from a topic that requires ssl verification using both ca and user certificates

### ISSUE THREAD

**Issue by user8189** [twmb/franz-go#549]
Hello, 

I am currently working on a project where I am consuming from a kafka broker that is outside of my organization, I have been provided with the user and cluster certificate files and converted them from `.p12` to `.pem` formats with a key and certificate and just certificate files respectively. I was able to consume messages from a local topic, but am wondering if you can provide specific guidance for how to do this with the additional ssl verification. I am trying to use the `crypto/tls` and `crypto/x509` packages, but am not currently seeing any messages coming through.

**Comment by twmb** [comment]
It might be worth taking a look at github.com/twmb/tlscfg, to easily load a tls cert and then use that the franz-go DialTLSConfig option?
