### ISSUE TITLE
[question] reset offset for group

### ISSUE THREAD

**Issue by igor9292** [twmb/franz-go#555]
Thanks for the great library!
I had a question, how can I reset the offsets at the end for an already existing group, 
how is it done here:
`kafka-consumer-groups --bootstrap-server <kafkahost:port> --group <group_id> --topic <topic_name> --reset-offsets --to-latest`

I found only similar functionality:
kgo.CosumeResetOffset(kgo.NewOffset().AtEnd())
But she does not throw off offsets at the end, for an already existing group. In my architecture, there is no way to create a new group each time (((

**Comment by twmb** [comment]
Have you seen https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.CommitOffsets ?
You can use it with Offsets set to -1, which is a special internal value meaning "the end".
You can also use ListEndOffsets() to help.
See https://github.com/redpanda-data/redpanda/blob/257a4dfce8a1a078c7101bfc4cbd1c8db0686d46/src/go/rpk/pkg/cli/group/seek.go#L252-L256
