### ISSUE TITLE
More Hooks to have prom metrics around commit rate etc.

### ISSUE THREAD

**Issue by anuraj381** [twmb/franz-go#557]
Hi @twmb , currently we have hooks missing for various events like commit request completed (success, failure), rebalance happening , heartbeats etc. We get observability around these events in Java clients and I was working on prometheus metrics with franz-go and I found these hooks are missing. 
Can we add these hooks ? 
Are these hooks considered in past also and not taken up because of some challenge ?
I can share a list of events we should add more for better observability, however first wanted to check with you on the feasibility.

**Comment by twmb** [comment]
They were not considered, I'm open to them. What are your proposals? I don't think anything would make these infeasible.

**Comment by anuraj381** [comment]
I guess these events/hooks should be added - 

**Producer**
- Producer error rate
- Producer retry rate

**Consumer**
- Consumer Heartbeat Rate OR Last heartbeat (seconds ago)
- Heartbeat latency/response-time
- Consumer Poll rate (I guess this can be done currently also with OnFetchBatchRead hook) OR Last Consumer Poll (seconds ago)
- Poll request latency/response-time
- Last Rebalance Time (seconds ago)
- rebalance time (if possible somehow), sync-rate
- Consumer group join/leave rate
- Commit rate
- Commit latency
- Assigned partitions count

**general**
- Authentication attempts (success/failed)

Please review these.

**Comment by twmb** [comment]
Can't most of those be implemented in terms of the current hooks, particularly HookBrokerE2E? Because the hook gives you the request key that was issued, it can tell you heartbeat rate, heartbeat latency, polling and poll latency, sync time, join/leave rate, produce retry rate, commit rate and latency.

Also assigned partitions count can also be hooked into with an OnPartitionsAssigned/Revoked/etc callback.

I think the main thing missing is auth attempts?

**Comment by twmb** [comment]
Closing, lmk if you have a narrow proposal of hooks to add to address gaps (vs. what mostly can be addressed today with what exists)

**Comment by anuraj381** [comment]
sure @twmb , will checkout `HookBrokerE2E` and will try to implement the required meters with this hook. Assuming I can get the request key (int16) from here - https://github.com/twmb/franz-go/tree/master/generate/definitions

**Comment by twmb** [comment]
Yes, or you can do
```go
switch kmsg.Key(key) {
case kmsg.Produce:
...
```
