### ISSUE TITLE
Consuming up to N records or M seconds

### ISSUE THREAD

**Issue by victoraugustolls** [twmb/franz-go#558]
Sorry if I missed something, but is there a way to consume up to N records or M seconds? For example, I want to consume 5k records or whatever is available (up to a limit of 5k) in a 10 seconds poll window. I thought of using a context for this, but it looks like this would result in an error when using `PollRecords`. 

In my scenario, I'm using the `GroupTransactSession`.

Thanks in advance, and for your work in this awesome library :).

**Comment by victoraugustolls** [comment]
The other option is [configuring](https://github.com/twmb/franz-go/blob/01651affd204d4a3577a341e748c5d09b52587f8/pkg/kgo/config.go#L1134) the `waitTime` in the client, but wanted to make sure this would be the correct way!!

**Comment by twmb** [comment]
I think a context is the right solution for the M seconds aspect of this, and then counting the records you've received is a solution for the N records. You can check for context.DeadlineExceeded and if the poll error is that, know that you've elapsed M seconds. Note that if any records are available, PollRecords returns, so if you see context.DeadlineExceeded, you're not missing out on any error.

I do something similar here in the tests, actually, though you might want to use Err0: https://github.com/twmb/franz-go/blob/01651affd204d4a3577a341e748c5d09b52587f8/pkg/kgo/group_test.go#L185

**Comment by twmb** [comment]
(closing preemptively hoping this answered but please ping if it did not)

**Comment by victoraugustolls** [comment]
Thanks for the answer @twmb! I thought of that but, in this case, wouldn't the Poll return 0 records? If I have an error of context.DeadlineExceeded, it looks like I would have no records returned, right?

**Comment by twmb** [comment]
Yes but, isn't that what's desired? You have no records in the requested time allowance?

**Comment by victoraugustolls** [comment]
Actually what I meant was:

Let's suppose that I want at most 5000 records in a 10 seconds window, and I call PollRecords with a value of 5000. If, after 10 seconds, I only have 3200 records available, return those records immediately!

Does that make sense?

**Comment by twmb** [comment]
Can you do something like,
```go
ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
var fs []kgo.Fetch
out:
for fs.NumRecords() != 5000 {
    poll := cl.PollRecords(ctx, 5000-fs.NumRecords())
    switch err := poll.Err0(); err {
    case context.Canceled:
        break out
    default:
        // handle
    }
    fs = append(fs, poll...)
}
```

**Comment by victoraugustolls** [comment]
That's actually what we are doing today over here (almost at least)! I was just wondering if I was missing something, or some config, to achieve this behavior.

Thanks for the help!!
