### ISSUE TITLE
Advice on health checks and CD

### ISSUE THREAD

**Issue by doron-cohen** [twmb/franz-go#565]
Hey, first of all, thanks for this library. I have learnt a lot on Kafka through it and it is a much saner option than `sarama` IMO.

I implemented a consumer using this library with the default balancer strategy (cooperative). It works great but I noticed it takes a long time to start consuming when we deploy a new version. Since I wanted to avoid a consumer lag peak when a new version is deployed I added a health check to test two things: connectivity to the cluster and whether partitions are assigned. This is the code I am using currently:

```go
func (e *BatchConsumer) HealthCheck(ctx context.Context) error {
	err := e.client.Ping(ctx)
	if err != nil {
		return fmt.Errorf("failed to ping kafka: %w", err)
	}

	if !e.assignedPartitions.Load() {
		return errors.New("no assigned partitions")
	}

	return nil
}
```

I use these options to update the `assignedPartitions` (of type `atomic.Bool`):
```go
		kgo.OnPartitionsAssigned(func(ctx context.Context, c *kgo.Client, m map[string][]int32) {
			assignedPartitions.Store(true)
		}),
		kgo.OnPartitionsLost(func(ctx context.Context, c *kgo.Client, m map[string][]int32) {
			assignedPartitions.Store(false)
		}),
```

I wired this code to our health check endpoint and it works great. I can now see that the older deployment pods keep consuming until the newer are up.

The problem is that I see now the new pods are getting restarted multiple times probably since the readiness probes time out. I think what happens is that the older pods and the newer ones are "fighting" for the consuming spots (or the newer ones between themselves?). Here are the logs for one of the pods:

```
Sep 18 16:02:47.719 | assigning partitions
Sep 18 16:02:47.718 | beginning heartbeat loop
Sep 18 16:02:47.717 | new group session begun
Sep 18 16:02:47.717 | synced
Sep 18 16:02:47.710 | syncing
Sep 18 16:02:47.710 | joined
Sep 18 16:02:47.673 | joining group
Sep 18 16:02:47.636 | immediate metadata update triggered
Sep 18 16:02:47.636 | cooperative consumer calling onRevoke at the end of a session even though no partitions were lost
Sep 18 16:02:47.636 | heartbeat errored (The group is rebalancing, so a rejoin is needed.)
Sep 18 16:01:59.632 | beginning heartbeat loop
Sep 18 16:01:59.632 | new group session begun
Sep 18 16:01:59.632 | synced
Sep 18 16:01:59.628 | syncing
Sep 18 16:01:59.628 | joined
Sep 18 16:01:14.626 | sync failed with RebalanceInProgress, rejoining
Sep 18 16:00:57.805 | syncing
Sep 18 16:00:57.805 | joined
Sep 18 16:00:12.802 | sync failed with RebalanceInProgress, rejoining
Sep 18 15:59:57.591 | syncing
Sep 18 15:59:57.590 | joined
Sep 18 15:59:12.589 | sync failed with RebalanceInProgress, rejoining
Sep 18 15:59:09.810 | syncing
Sep 18 15:59:09.810 | joined
Sep 18 15:58:25.354 | joining group
Sep 18 15:58:25.314 | cooperative consumer calling onRevoke at the end of a session even though no partitions were lost
Sep 18 15:58:25.314 | heartbeat errored
Sep 18 15:58:24.836 | assigning partitions
Sep 18 15:58:24.812 | beginning heartbeat loop
Sep 18 15:58:24.811 | new group session begun
Sep 18 15:58:24.811 | synced
Sep 18 15:58:24.806 | syncing
Sep 18 15:58:24.806 | joined
Sep 18 15:58:22.108 | join returned MemberIDRequired, rejoining with response's MemberID
Sep 18 15:58:22.040 | joining group
Sep 18 15:58:22.040 | beginning to manage the group lifecycle
```

So I got a few questions here:
1. Is my health check approach any good? I like the guarantee around continuous consumption but I might miss something.
2. Is there a way to make the new pods take over quickly and have smoother deployments? I would like to avoid increasing the probe timeouts (which will make deployments longer).

BTW, we lately learned that the balancing logic in Kafka should be implemented by the client which totally blew our mind (I think it's madness...).

**Comment by twmb** [comment]
* Lost is accurate, but I think you might want revoked as well?
* Assigned will be called multiple times without lost being called -- lost is a bit more fatal. Assigned is called every rebalance, and there will be a corresponding revoked
* Revoked may be called with no partitions (cooperative consuming) -- it's just called at the end of every group lifecycle

I'd at least change assignedPartitions to be an atomic.Int64, and then add the number of partitions assigned and subtract the number revoked or lost. Particularly, don't _just_ use the lost callback. Also -- it's not _unhealthy_ to have no partitions if you have more consumers than you do partitions.

Also make sure you properly LeaveGroup when closing the client. If you don't, then the group member is abandoned and you'll cause lag and then an eventual group session cycle once the session timeout is hit.

**Comment by twmb** [comment]
Closing, let me know if the prior answer doesn't answer everything

**Comment by doron-cohen** [comment]
Thanks for the quick response @twmb.

1. I am not sure about revoke. I wouldn't want to report an unhealthy pod on temporary errors or anything like that. When will it be called exactly? I see this log on deployments: `cooperative consumer calling onRevoke at the end of a session even though no partitions were lost` which makes me wonder about how to handle this correctly.
2. About counting partitions, I wouldn't know how many partitions should a pod consume in the service to my understanding. We shouldn't create more pods then partitions. But, theoretically it might happen I guess. I will try to think of a better approach though.
3. So Kubernetes will only send a signal to kill the old pods once the new pods are up so I don't have any way of knowing in the old pods that new ones with the same consumer group are trying to replace them do I? I will take a look at `LeaveGroup` for a cleaner close though.

**Comment by twmb** [comment]
I see... I think with the way you have it setup, you only need a boolean, yes, that should be fine. I was thinking to accurately count the number of partitions. But, you just want to know you were in a group OR you lost the group fatally. So, yes I think your original idea is fine actually :+1:.

**Comment by twmb** [comment]
Also the latest release added LeaveGroupContext for more control over the leave.
