### ISSUE TITLE
broker selection not actually random?

### ISSUE THREAD

**Issue by dparker18** [twmb/franz-go#579]
With thousands of clients connecting to our cluster, I'm seeing very imbalanced connections across our nodes causing scale issues. With an initial cl.Ping() or a NewPtrMetadataRequest, connections are almost always hitting our first node.

I noticed the comment here notes "broker returns a random broker from all brokers ever known". But it seems like it's not random, and in fact will always initially return the first broker sorted by node ID:
https://github.com/twmb/franz-go/blob/c9d2351dbcf7f027bca30127269eedaa2904579b/pkg/kgo/client.go#L736C1-L765C1

Am I reading that behavior correctly? If it's not random, are there any workarounds from the app layer? And/or would you be open to a PR with randomization? Thank you for a great library!

**Comment by dparker18** [comment]
Looks like the "random" behavior changed with https://github.com/twmb/franz-go/commit/1e5c11d1cd62e3df4f1dc307c8a849c830da4d04

**Comment by twmb** [comment]
I'm open to randomization being added back in

**Comment by dparker18** [comment]
Thanks, will have a PR next week
