### ISSUE TITLE
Support for compression optional in kfake

### ISSUE THREAD

**Issue by kalbhor** [twmb/franz-go#582]
Hey @twmb, firstly thanks for such a solid Go library for kafka.

I was wondering if it maybe possible to add support for compression in `kfake`. We use `kfake` extensively in tests in our custom internal abstraction that is on top of your lib. I noticed that `kfake` ignores the `kgo.ProducerBatchCompression()` optional that can be passed to a producer. Currently to test the compression/decompression on messages we are having to spawn an actual cluster locally and test. Having this in `kfake` will be a great help. If I can help in adding this, you can guide me briefly and I'll be more than happy to contribute :)

**Comment by twmb** [comment]
ProducerBatchCompression is a client side option -- compression is driven from the client. This is also the case in Kafka / Redpanda / etc. The only time the broker manages compression is when you change the broker's compression.type away from `producer`. In kgo, the client obeys ProducerBatchCompression _but_ if compression actually expands a batch size, the client ignores compression and sends the batch uncompressed (this is more efficient for the broker and for the eventual consumer).

How are you trying to test compression / what are you expecting to see in kfake?

**Comment by twmb** [comment]
Yes, change the log line:
```
 t.Logf("msg value : %s\noffset : %d, compression type %d", string(r.Value), r.Offset, r.Attrs.CompressionType())
```
Records are decompressed by the client when consuming. You don't see compression as a user of the client.

**Comment by twmb** [comment]
Lmk if that did not answer your question, closing for now.

**Comment by kalbhor** [comment]
Apologies for the delayed response. I checked the `r.Attrs.CompressionType()` and you are right, records are decompressed by the client itself. We can keep this issue closed
