### ISSUE TITLE
Coordinate backoff/retries between Client.PollRecords and "inner topic errors"

### ISSUE THREAD

**Issue by genzgd** [twmb/franz-go#586]
In our Client.PollRecords loop, we're trying to gracefully handle the case where the underlying topic is deleted.  At the moment we track errors generated during the loop and alert/stop the process above a certain threshold.  We originally used our own back off/retry logic until we realized most errors used the internal retry logic using the client RetryBackoffFn option, and we were actually doubling the time for retries by adding our own wait.

The issue we're having is after a certain point in time after the topic is deleted, there's no longer a retry wait and Client.PollRecords returns immediately, creating a tight loop that spams our logs and our alerting system.  Originally the RetryBackoffFn is invoked at a lower level with the message "fetch had inner topic errors", and waits as expected, but then this function stops be called on subsequent calls to Client.PollRecords.

The upshot is even though we get back an kerr.UnknownTopicOrPartitionError that is marked as "retriable", it isn't getting retried with a delay in the client.  I don't think this really qualifies as a bug, but we're looking for a way to essentially "reset" the number of retries in subsequent calls to PollRecords to avoid the tight loop.

**Comment by twmb** [comment]
Have you seen the [`UnknownTopicRetries`](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#UnknownTopicRetries) option / does it help / provide a way to answer your question?

Also -- when you say tight loop, are you not checking the fetches.Errors(), or not backing off a little bit if it contains UnknownTopicOrPartition?

Also, what do debug logs look like? I'm curious why there's a tight loop.

**Comment by genzgd** [comment]
Thanks for looking!  I hadn't noticed the UnknownTopicRetries option but the default of 4 does help explain why the initial delay before the error was reported (it takes approximately 6 minutes) was longer than we expected.

We are checking fetches.Errors(), but as I noted in the issue, we actually removed our backoff/retry logic since it was duplicative of the functionality internal to the kgo.Client.  From this behavior it seems like we have to treat the UnknownTopicOrPartitionError differently, which is not a problem, I just want to confirm that's the right thing to do.

Debug logs attached, the tight loop starts at 01:57:44.723, where PollRecords starts returning immediately.  The debug logs are very noisy until then.

[franzretry.txt](https://github.com/twmb/franz-go/files/12854378/franzretry.txt)

**Comment by twmb** [comment]
The tight loop is because the connection to your broker is really fast, and you're doing nothing with the error that is being returned from PollFetches.

The UnknownTopicID error is stripped 5 times because Kafka has some metadata cluster broadcasting problems, see here:
https://github.com/twmb/franz-go/blob/ae169a1f35c2ee6b130c4e520632b33e6c491e0b/pkg/kgo/source.go#L925-L946

But, after 5x (per partition), the error is being bubbled up to you. Once that happens, you can see in your logs that you poll, print the error, and immediately poll again. The connection to your broker is fast enough such that this looks like a spin loop - the client is actually requesting the broker and returning the error very fast.
```
2161 2023-10-10 01:57:44.857 ERR kafka fetch failed after retries error="UNKNOWN_TOPIC_ID: This server does not host this topic ID." pipe_id=test_pipe_id retriable=true                      
2162 2023-10-10 01:57:44.857 DBG wrote Fetch v15 broker=42 bytes_written=62 err=null pipe_id=test_pipe_id time_to_write=0.03925 write_wait=0.051041
2163 2023-10-10 01:57:44.889 DBG read Fetch v15 broker=16 bytes_read=76 err=null pipe_id=test_pipe_id read_wait=0.054042 time_to_read=61.768375
2164 2023-10-10 01:57:44.889 DBG updated uncommitted group=geoff_mac_717 pipe_id=test_pipe_id to=large_trips[]
2165 2023-10-10 01:57:44.889 ERR kafka fetch failed after retries error="UNKNOWN_TOPIC_ID: This server does not host this topic ID." pipe_id=test_pipe_id retriable=true
2166 2023-10-10 01:57:44.889 DBG wrote Fetch v15 broker=16 bytes_written=62 err=null pipe_id=test_pipe_id time_to_write=0.079 write_wait=0.055333
2167 2023-10-10 01:57:44.908 DBG read Fetch v15 broker=54 bytes_read=76 err=null pipe_id=test_pipe_id read_wait=0.045041 time_to_read=72.789042
2168 2023-10-10 01:57:44.908 DBG updated uncommitted group=geoff_mac_717 pipe_id=test_pipe_id to=large_trips[]
2169 2023-10-10 01:57:44.908 ERR kafka fetch failed after retries error="UNKNOWN_TOPIC_ID: This server does not host this topic ID." pipe_id=test_pipe_id retriable=true
2170 2023-10-10 01:57:44.908 DBG wrote Fetch v15 broker=54 bytes_written=62 err=null pipe_id=test_pipe_id time_to_write=0.0865 write_wait=0.034917
2171 2023-10-10 01:57:44.921 DBG read Fetch v15 broker=42 bytes_read=76 err=null pipe_id=test_pipe_id read_wait=0.063667 time_to_read=63.454208
2172 2023-10-10 01:57:44.921 DBG updated uncommitted group=geoff_mac_717 pipe_id=test_pipe_id to=large_trips[]
2173 2023-10-10 01:57:44.921 ERR kafka fetch failed after retries error="UNKNOWN_TOPIC_ID: This server does not host 
```

You can use [PurgeTopicsFromConsuming](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.PurgeTopicsFromConsuming) if you actually expect the topic to not exist anymore.

**Comment by genzgd** [comment]
Thanks for the explanation!  It seems clear that in this particular instance we'll need to add an additional backoff/retry loop rather than relying on the Client.  Do you know offhand any other types of errors we should look for that would cause similar behavior?

**Comment by twmb** [comment]
I don't know what you mean by retry -- this error is not recoverable, if you deleted the topic. You need to handle it otherwise you will always receive this error. Same thing for if you received UnknownTopicOrPartition.

**Comment by genzgd** [comment]
Ah, I didn't realize that the error was not recoverable even if the topic was recreated.  Our application runs as a service and the coordination between the user who deleted the topic and the user who is responsible for monitoring the service for errors could take quite some time, so we were thinking that the user could "fix" the situation by recreating the topic.  I'm guessing we would have to create a new client/consumer group/etc. in that case.  Again thanks for the insight!

**Comment by twmb** [comment]
Topic IDs are globally unique forever, even if you recreate a topic with the same name. The client remembers the ID and forever uses it. You'll have to purge the topic and then re-add it to forget the old ID -- but you can do this without recreating the client.
