### ISSUE TITLE
Is SASL Missing? issue

### ISSUE THREAD

**Issue by UjjwalByjus** [twmb/franz-go#588]
I am getting these error messages 

> "re-updating metadata due to err: broker closed the connection immediately after a request was issued, which happens when SASL is required but not provided: is SASL missing?"
>"read from broker errored, killing connection after 0 successful responses (is SASL missing?)"

I am trying to add authentication.
My code for that is:
```
auth := scram.Auth{
		User: "kafka_user",
		Pass: "kafka_pass",
	}
	
	cl, err := kgo.NewClient(
		kgo.SeedBrokers(seeds...),
		kgo.DialTLSConfig(tlsConfig),
		kgo.SASL(auth.AsSha512Mechanism()),
		kgo.ConsumerGroup(consumerGroupId),
		kgo.ConsumeTopics(topics...),
		kgo.WithLogger(kzap.New(logger.GetLogger())),
	)
```
	
The requirements for the authentication were:
 - SSL: false
 - security protocol: SASL_PLAINTEXT
 - SASL mechanism: SCRAM-SHA-512
 - Username: <<username>>
 - Password: <<password>>

**Comment by twmb** [comment]
What do you mean by "SSL: false" but then also using DialTLSConfig as a kgo option (which opts into TLS)?

**Comment by UjjwalByjus** [comment]
@twmb In order to make the SSL: false I am adding below code.

```
tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
	}
```

**Comment by twmb** [comment]
I thought SSL: false on the broker disables TLS entirely, so if you're using a TLS configuration, the broker will reject the request (since the broker is expecting non-TLS)?

**Comment by UjjwalByjus** [comment]
Without adding any TLS config the same error persists.

**Comment by twmb** [comment]
Interesting. Do you have any broker logs for this? The broker has to close the connection if sasl fails or tls fails, and the broker tells the client nothing about the reason it is closing connections. Also, what do franz-go debug logs look like?

**Comment by UjjwalByjus** [comment]
I do not have access to the broker logs. That broker is being used company-wide and only I am using franz-go pkg and only I am getting this error.

**Comment by twmb** [comment]
What about franz-go debug logs?

**Comment by UjjwalByjus** [comment]
How to check that? Can you guide me?

**Comment by twmb** [comment]
Add
```go
kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelDebug, nil))
```
as an option, and post the stderr output to this issue (or, at least some of the output -- around connections)

**Comment by twmb** [comment]
Closing for now but if you're able to capture logs, please let me know and we can reopen if this is a franz-go issue.
