### ISSUE TITLE
How consume again uncommitted message from kafka partition in same connection

### ISSUE THREAD

**Issue by kukwuka** [twmb/franz-go#590]
I am using client library [franz-go ](https://github.com/twmb/franz-go)for kafka . I'm trying to consume the same message for the second time in the same connection .

First of all I produce some message to topic, then I consume this message but don't commit them.

I want to consume again this message without reconecting (when I reconnect, I can consume this message again)

Is there any way to get this message again? Case with reconnect works correctly and I get the same message second time

```go
package main

import (
	"context"
	"github.com/twmb/franz-go/pkg/kgo"
)

func main() {
	cl, err := kgo.NewClient(
		kgo.SeedBrokers("localhost:9092"),
		kgo.ConsumerGroup("some_consumer_group"),
		kgo.ConsumeTopics("topic"),
		kgo.DefaultProduceTopic("topic"),
		kgo.DisableAutoCommit(),
	)
	if err != nil {
		panic(err)
	}
	record := &kgo.Record{
		Key:   []byte("some_key"),
		Value: []byte("some value"),
	}

	ctx := context.Background()
	produceResult := cl.ProduceSync(ctx, record)
	if produceResult.FirstErr() != nil {
		panic(err)
	}

	fetches := cl.PollFetches(ctx)
	if fetches.Err() != nil {
		panic(err)
	}
	//I don't commit
	doSomething(fetches)

	//after that I want to get same message again and handle again
	//but here I'm faced with endless waiting
	fetches = cl.PollFetches(ctx)
	if fetches.Err() != nil {
		panic(err)
	}
	//I don't commit
	doSomething(fetches)
	err = cl.CommitRecords(ctx, fetches.Records()...)
	if err != nil {
		panic(err)
	}

}

func doSomething(result kgo.Fetches) {
	// I do something with kafka messages
	// and something went wrong and
}

```

**Comment by stampy88** [comment]
Hi @kukwuka, so is the problem that your `doSomething` function runs into a problem and you would like to reprocess the messages? If so, I suggest that you bake that into your `doSomething` (or another) function. That is the typical pattern when trying to reprocess messages. Franz will not redeliver those messages, as you pointed out, using that same connection.

**Comment by kukwuka** [comment]
Hi @stampy88, for example:  doSomething is writing to db, but db not avalaible now, I want to wait some time and then try again to write message into db
In classic case I need to write this into topic with failed messages
But I want only reread this message and try again

**Comment by twmb** [comment]
Good answer. Also, as one measure of last resort, you can use SetOffsets which is a bit of a low-level way to set exactly where you want partitions to consume from. I don't recommend it, and I recommend the answer @stampy88 gave above.
