### ISSUE TITLE
Producer config, MaxBufferedBytes, MaxBufferedRecords

### ISSUE THREAD

**Issue by madshov** [twmb/franz-go#591]
Hi all,
I was looking at some of the producer configuration, and I'm trying to understand each of them. Are these following assumptions correct?
`MaxBufferedBytes`: The maximum number of bytes to be batched before the buffer is flushed and records are written to the broker. Default 0/unlimited bytes?
`MaxBufferedRecords`: The maximum number of records to be batched before the buffer is flushed and records are written to the broker. Default 10000 records.

So the record buffer will be flushed whenever at least one of the above is fulfilled? Is there a timeout where the buffer is flushed anyway, in case they are none of them are fulfilled?

Thanks

**Comment by twmb** [comment]
Those are maximums, for buffering only -- i.e. when records are being flushed / can't keep up with flushing. By default the client flushes as fast as possible. You can change this with the linger setting -- in which case, records will be flushed either once the linger is hit _or_ once a batch is "full". Batch fullness is determined by ProducerBatchMaxBytes

**Comment by twmb** [comment]
There are a lot of options so it is a bit confusing, I don't really have a great solution (naming is hard, and this is now a "stable" API)

**Comment by madshov** [comment]
Ok. Thanks @twmb for clarifying this to me.
