### ISSUE TITLE
INVALID_TXN_STATE while producing in transaction from new version of library

### ISSUE THREAD

**Issue by iClaus21** [twmb/franz-go#609]
Hi there,
I have a problem with a new (v1.15+) version of library in conjunction with 3.6.0 version of Kafka.

If I try to produce record in a transaction I receive these messages in go library log:
```
INFO kafka-client: batch in a produce request failed broker=202 err=INVALID_TXN_STATE: The producer attempted a transactional operation in an invalid state. err_is_retryable=false max_retries_reached=false partition=0 topic={topic}
DEBUG kafka-client: produced broker=202 to={topic}[0{err@-1,1(INVALID_TXN_STATE: The producer attempted a transactional operation in an invalid state.)}]
INFO kafka-client: producer state set to aborting; continuing to wait via flushing
......
ERROR kafka: Transaction rollback error: INVALID_TXN_STATE: The producer attempted a transactional operation in an invalid state.
```

And this log in Kafka service:
```
INFO Principal = User:Producer@Local is Denied operation = DESCRIBE from host = 127.0.0.1 on resource = TransactionalId:LITERAL:{transactional_id} for request = FindCoordinator with resourceRefCount = 1 based on rule DefaultDeny (kafka.authorizer.logger)
...
INFO Principal = User:Producer@Local is Denied operation = CLUSTER_ACTION from host = 127.0.0.1 on resource = Cluster:LITERAL:{transactional_id} for request = AddPartitionsToTxn with resourceRefCount = 1 based on rule DefaultDeny (kafka.authorizer.logger)
```

The list of kafka-acls:
```
Current ACLs for resource `ResourcePattern(resourceType=CLUSTER, name=kafka-cluster, patternType=LITERAL)`: 
   (principal=User:Producer@Local, host=*, operation=IDEMPOTENT_WRITE, permissionType=ALLOW)

Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name={topic}, patternType=LITERAL)`: 
   (principal=User:Producer@Local, host=*, operation=WRITE, permissionType=ALLOW)
  (principal=User:Producer@Local, host=*, operation=CREATE, permissionType=ALLOW)
  (principal=User:Producer@Local, host=*, operation=DESCRIBE, permissionType=ALLOW)

Current ACLs for resource `ResourcePattern(resourceType=TRANSACTIONAL_ID, name={transactional_id}-, patternType=PREFIXED)`: 
  (principal=User:Producer@Local, host=*, operation=WRITE, permissionType=ALLOW)
  (principal=User:Producer@Local, host=*, operation=DESCRIBE, permissionType=ALLOW)
```

Important node, If I rollback to the previous version of go library (v1.14.4) all produce commands completed successfully without any errors.

Also I tried to fix this problem via assigning more permissions to CLUSTER resourceType.
```
kafka-acls.sh --add --allow-principal User:Producer@Local --cluster --operation Describe
kafka-acls.sh --add --allow-principal User:Producer@Local --cluster --operation ClusterAction
```

Giving such permissions to the CLUSTER operations fixing the problem.
But won't such changes lead to a reducing the kafka cluster security?

Is my permission grant the only way to fix this problem? This is designed behavior or not?

**Comment by twmb** [comment]
I think you're running into [KAFKA-15653](https://issues.apache.org/jira/browse/KAFKA-15653), however I would expect you to still run into this with v1.14.4.

Can you set transaction.partition.verification.enable=false on your broker and see if this resolves the issue?

**Comment by twmb** [comment]
Actually, re-reading, the manifestation of this issue for you is different than I what I saw. I'll take a closer look at the ACL lines.

**Comment by twmb** [comment]
KIP-890 has been updated since I implemented the code to document that clients should continue to send v3, not v4 of the request. I'll need to issue a patch for this. Since an immediate workaround exists (kgo.MaxVersions(kversions.V3_5_0()), I recommend using that and I'll see about getting a patch out this week (there's another issue I'm looking into on Discord).

**Comment by iClaus21** [comment]
@twmb, thank you for such an immediate response.
I tried your temporary solution ```kgo.MaxVersions(kversion.V3_5_0())``` and it helps me. Thanks you a lot.
I will wait for this problem to be fixed.
