### ISSUE TITLE
Question: best practice when consuming from multiple topics

### ISSUE THREAD

**Issue by benjamonnguyen** [twmb/franz-go#616]
I'm assuming there is a non-trivial overhead with each new client, so is it best practice to create one client that consumes from multiple topics?

This is what I'm imagining:
```go
fetches.EachTopic(func(t kgo.FetchTopic) {
    switch t.Topic {
    case "messages":
        t.EachRecord(handleMessages)
    case "events":
        t.EachRecord(handleEvents)
    }
})
```

Wanted to check if there was a better way since this seems to be in conflict with open-close principle of OOP.

**Comment by twmb** [comment]
Each client has to have a connection per broker, so it is recommended to use one client.
Not sure how that violates open/close but Go isn't the most OO, and this is Kafka semantics here.

**Comment by benjamonnguyen** [comment]
Thank you for the response! I took a look at the goroutine_per_partion_consuming example and added a map of topic to recordHandler function to the splitConsume struct for additional topics.
