### ISSUE TITLE
Kotel consumer not setting trace id correctly.

### ISSUE THREAD

**Issue by JamesArthurHolland** [twmb/franz-go#624]
I'm using the kotel tracing plugin, and viewing in jaeger.

The consumer isn't setting the trace ID of the created span to be the trace ID created by the publisher. This means the trace is being shown as 2 separate traces in jaeger, with no way of linking the 2.

I'm passing the instrument context to the publisher as per the example.

**Comment by twmb** [comment]
Tagging @brunsgaard

**Comment by brunsgaard** [comment]
Hi, thanks for the ping. Unfortunately do not have enough time on my hands right now to investigate this. @JamesArthurHolland, I think it would be helpful if you could provide an running example snippet of what you are experiencing. You are taking the context from `record.Context` in your consumer and using that context in your further execution flow?

**Comment by JamesArthurHolland** [comment]
@brunsgaard  Hi, I followed the execution in Goland debugger. 

On the publisher side, the kgo.Record is getting the context set correctly.

On the consumer side, the context is not being retrieved from the record.

There are some header values set, such as "traceparent" which is correct. But the kotel plugin doesn't use this and tries to read it from the record's context.

versions used:
```
	github.com/twmb/franz-go v1.15.2
	github.com/twmb/franz-go/plugin/kotel v1.4.0
	go.opentelemetry.io/otel v1.18.0
	go.opentelemetry.io/otel/trace v1.18.0
```
