### ISSUE TITLE
"default commit failed" logs contain no error

### ISSUE THREAD

**Issue by doron-cohen** [twmb/franz-go#625]
Hey, we found some errors from services using kgo about committing offsets:
```json
{
	"content": {
		"timestamp": "2023-11-30T09:21:12.731Z",
		"message": "default commit failed",
		"attributes": {
			"level": "error",
			"fields": {
				"group": "events.forwarding.sender.small"
			},
			"timestamp": "2023-11-30T09:21:12.731792199Z"
		}
	}
}
```

Some questions:
1. What error could have cause it? We see these errors come and go in bursts.
2. I suppose the commit will be retried. Assuming it is, is there any side effect we should be aware of? (like possible re processing of the event)
3. I don't see the `err` tag which I see exists in the code. I added some tests to the logger which implements `kgo.Logger` and it seems to work fine. Is there anything else I should check? The code does seem to add the mentioned tag: https://github.com/twmb/franz-go/blame/a6d10d4ad93528f7c2e8ed735a40bb1bd8a03c8a/pkg/kgo/consumer_group.go#L2092

**Comment by doron-cohen** [comment]
1. Which wrapper? The logger wrapper or the consumer wrapper?
2. Got it.
3. Attaching code here:

```go
func NewKgoLogger(l logging.Logger) *KgoLogger {
	return &KgoLogger{
		l: l.WithTag(tags.LoggerName, "kgo"),
	}
}

type KgoLogger struct {
	l logging.Logger
}

func (l *KgoLogger) Log(level kgo.LogLevel, msg string, keyVals ...interface{}) {
	t := tagsFromKeyVals(keyVals...)

	switch level {
	case kgo.LogLevelDebug:
		l.l.WithTags(t).Debug(msg)
	case kgo.LogLevelInfo:
		l.l.WithTags(t).Info(msg)
	case kgo.LogLevelWarn:
		l.l.WithTags(t).Warn(msg)
	case kgo.LogLevelError:
		l.l.WithTags(t).Error(msg)
	default:
		t["level"] = level.String()
		l.l.WithTags(t).Debug(msg)
	}
}

func (l *KgoLogger) Level() kgo.LogLevel {
	return kgo.LogLevelInfo
}

func tagsFromKeyVals(keyVals ...interface{}) tags.Tags {
	l := len(keyVals)
	if l%2 != 0 {
		l--
	}

	t := make(map[string]interface{}, len(keyVals)/2)
	for i := 0; i < l; i += 2 {
		k, ok := keyVals[i].(string)
		if !ok {
			continue
		}

		if k == "err" {
			k = "error"
		}

		v := keyVals[i+1]
		t[k] = v
	}

	return t
}
```

This part was added since I wanted to align with our logging practices of putting the error in the appropriate key but it didn't change anything:

```go
		if k == "err" {
			k = "error"
		}
```

**Comment by twmb** [comment]
Yeah I'm not really sure what to do with the missing fields in logs. The last issue where something similar happened, something was wrong on the person's log ingestion pipeline.

**Comment by twmb** [comment]
Need details before continuing, missing error looks like something in the ingestion system. Closing for now.
