### ISSUE TITLE
Custom number of acks

### ISSUE THREAD

**Issue by Neal** [twmb/franz-go#626]
I noticed the exported methods to set the Acks only allow 0, 1 an -1 to be set - is there any reason to not allow custom values for when say I'd like 2 acks?

https://github.com/twmb/franz-go/blob/3e9dc14/pkg/kgo/config.go#L862-L890

**Comment by twmb** [comment]
Looked in the source,
https://issues.apache.org/jira/browse/KAFKA-1697
Acks != -1, 0, or 1 was removed in 0.9.
See this commit:
https://github.com/apache/kafka/commit/eab4f4c9f43
Specifically this function:
```scala
  private def isValidRequiredAcks(requiredAcks: Short): Boolean = {
    requiredAcks == -1 || requiredAcks == 1 || requiredAcks == 0
  }
```
