### ISSUE TITLE
how to gracefully stop consuming

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#63]
in sarama or segmentio packages i can do unsubscribe from topic before closing connection.
How to deal with this in franz-go ?
my use case - ability to unsubscribe from topic gracefully, commit all pending offsets and close the connection

**Comment by twmb** [comment]
What's the equivalent API in sarama? I wonder if sarama still has buffered fetches under the hood :thinking: 

It's totally fine to not consume everything with the poll functions, and just commit & close. Buffered fetches don't do anything to a consumer group, it's only the commits. What's the need to drop anything buffered / stop fetching & drain everything buffered? Is it not sufficient to stop polling & commit & close?

**Comment by twmb** [comment]
Let me know if the prior suggestion doesn't work -- i.e., stop calling poll functions, and then commit everything and close the client. Anything internally buffered is dropped on close and doesn't adversely affect the client / the group. I'll close this in a day unless I hear otherwise.

**Comment by vtolstov** [comment]
yeah looks fine
