### ISSUE TITLE
How to handle TLS certificate renewals from client

### ISSUE THREAD

**Issue by erikgb** [twmb/franz-go#630]
Assuming my application has to use relatively short-lived TLS certificates. Is it possible to avoid a full restart of the application when the TLS certificate is renewed? I browsed the code for some kind of file-watcher but was unable to find any. Something similar as described in https://cwiki.apache.org/confluence/display/KAFKA/KIP-687%3A+Automatic+Reloading+of+Security+Store would be nice.

**Comment by twmb** [comment]
This doesn't automatically exist, but the possibility is there by providing your own kgo.Dialer -- I thought I knew of an existing public example but I can't find one (only a private one).

The gist is to cache the tls config in dial, periodically update the cache, and handle the handshake in the dial function.

**Comment by twmb** [comment]
Closing for now but if this can't work for you, let me know.
