### ISSUE TITLE
Struggling to catch retryable errors despite KeepRetryableFetchErrors() option

### ISSUE THREAD

**Issue by jadamscn** [twmb/franz-go#648]
Hi,

We have a problem with misconfiguring topic names, and I'd like to catch and fatal on this error. Reading the docs, my understanding is KeepRetryableFetchErrors() should do this, and then I can examine each error to decide whether or not I want to fatal. However, I'm having no luck with 0.15.3 on Go 1.21.4.  I know kgo is definitely seeing the error, because the log says as much, but doesn't seem to be passing it to my fetches.Errors.

Quick example:

```
func main() {
	var opts = []kgo.Opt{
		kgo.SeedBrokers(host),
		kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelInfo, nil)),
		kgo.ConsumerGroup(`test`),
		kgo.SASL(plain.Auth{User: user, Pass: pass}.AsMechanism()),
		kgo.FetchMaxWait(10 * time.Millisecond),
		kgo.KeepRetryableFetchErrors(),
		kgo.ConsumeTopics("test_nonexistent_topic"),
		kgo.Dialer((&tls.Dialer{NetDialer: &net.Dialer{Timeout: 10 * time.Second}}).DialContext),
	}

	cl, err := kgo.NewClient(opts...)
	if err != nil {
		fmt.Printf("ERROR: %s\n", err)
		os.Exit(1)
	}

	for {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()

		fetches := cl.PollFetches(ctx)
		if fetches.Err() != nil {
			for _, err := range fetches.Errors() {
				fmt.Printf("ERROR: %s\n", err.Err)
			}
			break
		}

		for _, r := range fetches.Records() {
			spew.Dump(r)
		}
	}
}
```

Output:
```
[INFO] beginning autocommit loop; group: test
[INFO] immediate metadata update triggered; why: querying metadata for consumer initialization
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
[INFO] metadata update triggered; why: re-updating due to inner errors: UNKNOWN_TOPIC_OR_PARTITION{test_nonexistent}
ERROR: context deadline exceeded
```

**Comment by twmb** [comment]
This is failing before a fetch is even issued. Currently, KeepRetryableFetchErrors only applies to errors that are returned from an actual FetchResponse (not MetadataResponse). I don't see a way in the client to hook into that right now. I'm not sure where this would necessarily fit... I wouldn't want to trigger a fetch error whenver there's a metadata load error, but there's also no real way to hook into metadata errors while consuming at the moment (unless I'm forgetting something)...

**Comment by jadamscn** [comment]
Thanks for your response.

Would something like a OnMetadataResponsError callback option be a workable pattern?

**Comment by twmb** [comment]
I think that'd work, and I also wonder if franz-go should bubble errors from metadata updates as well (i.e. inject a fake fetch)

**Comment by jadamscn** [comment]
I'm facing the same issue for dialer errors too. I am not sure if this is the same root cause; if it is not I'm happy to open a different issue.

If I set my seedbrokers to an address that results in a connection unreachable, connection refused, resolution failure, etc, it warns about the error but continues to try indefinitely to connect. I understand all these errors could be temporary and retryable, but it retries even if I give it an invalid address that will never work - e.g. 10.0.0.257. The dialer error in this case is no such host. 

I understand NewClient has lazy initialization so it returns a nil error before the network error has occurred, but I'm not sure of a workaround at this stage. Maybe client.Ping() ?

**Comment by twmb** [comment]
client.Ping will help that use case, yes

**Comment by twmb** [comment]
Metadata topic or partition failures now inject fake fetches; retryable topic or partition errors now inject fake fetches if KeepRetryableFetchErrors is used. This is in https://github.com/twmb/franz-go/commit/a2340ebb21a42fbd01d695aa2df109854050670e

**Comment by twmb** [comment]
I did not go the route of adding a new callback -- I think injecting a fake fetch is better here.
