### ISSUE TITLE
Question about fetching timestamp offset

### ISSUE THREAD

**Issue by ut0mt8** [twmb/franz-go#654]
First of all thank you for your great lib. I almost switch from sarama my kafka lag prom exporter. So far it's a great experience and performance are really better (ok I was maybe not using sarama the good way making many many multiple request where big one seems more efficient).

Anyway the last part I need to migrate is my calculation of the timestamp of the oldest offset and the lag calculated in time.

One function I wrote with Sarama is something like

````
func GetTimestamp(broker *sarama.Broker, topic string, partition int32, offset int64) (time.Time, error) {
	request := &sarama.FetchRequest{Version: 4}
	request.AddBlock(topic, partition, offset, 1)

	fr, err := broker.Fetch(request)
	// error handling

        block := fr.GetBlock(topic, partition)
        // error handling
	
	return block.Records.RecordBatch.MaxTimestamp, nil
}
````

I struggle to find the equivalent in franz-go. Any pointer appreciated.

**Comment by twmb** [comment]
That looks like the equivalent with running ConsumePartitions with a given offset, fetching once, and then returning the timestamp on the record. Is it not?

If possible, though, I'd recommend checking out [kadm.Lag](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.Lag), although this is specifically for groups.

**Comment by ut0mt8** [comment]
Yes what I want is "fetching" one or many records at given offsets.

something like 

````
los, err = cadmin.ListStartOffsets(context.Background())

cli, err := kgo.NewClient(kgo.SeedBrokers("127.0.0.1:9092"), kgo.ConsumePartitions(los.KOffsets()))

fetches := cli.PollRecords(context.Background(), 1)

    for _, fetch := range fetches {
        for _, ft := range fetch.Topics {
            for _, fp := range ft.Partitions {
                for _, rec := range fp.Records {
                    fmt.Printf("   %s %d %s \n", rec.Topic, rec.Partition, rec.Timestamp.Format(time.RFC850))
                }
            }
        }
    }
````
give me one timestamp for one partition ok. So I can play with PollRecord to fetch record by record.
but actually I wanted something more low level, don't want to poll. Either the record exist at the given offset either not.
and possibly fetching many record at once.

don't know if I'm clear?

**Comment by ut0mt8** [comment]
OK so I've read a bit further the kafka protocol. So what I need is surely to craft a fetchRequest(). Actually I played a bit with kmsg ; succeed making one request and having a correct response. But struggle to 1) set the correct version of the protocol (don't want dealing with topic-id ; working but add complexity), and 2) don't succeed to have multiple records in the response when adding more partitions/topics to the request ?!
what I want to avoid is making one request foreach timestamp I want to retrieve. From what I read from the protocol it should be doable but no luck for now.

**Comment by twmb** [comment]
So you basically want to:
* 10: Get offsets at timestamp
* 20: SetOffsets
* 30: PollRecords
* 40: goto 10

Is that right?

re: setting correct protocol version -- usually you shouldn't need to worry about it, but also the client isn't setup today to handle manually created fetch requests (this is so rare and unexpected that well, I just don't expect anybody to ever do it). 

(2), they should succeed when having multiple records in a request.

ListOffsets only supports a single topic/partition _once_. You cannot duplicate the input topic partition, the request will unfortunately fail, this is coded on the broker. If you want to request the same partition with two timestamps / etc, it will fail.

**Comment by ut0mt8** [comment]
> So you basically want to:
> 
> * 10: Get offsets at timestamp
> * 20: SetOffsets
> * 30: PollRecords
> * 40: goto 10
> 
> Is that right?
> 
> re: setting correct protocol version -- usually you shouldn't need to worry about it, but also the client isn't setup today to handle manually created fetch requests (this is so rare and unexpected that well, I just don't expect anybody to ever do it).
> 
> (2), they should succeed when having multiple records in a request.
> 
> ListOffsets only supports a single topic/partition _once_. You cannot duplicate the input topic partition, the request will unfortunately fail, this is coded on the broker. If you want to request the same partition with two timestamps / etc, it will fail.

Hmm no.
What I want is to get timestamp of records at specific offeset.
Particularly get the timestamps of oldest offsets of each partition.
The timestamps of newest one. And timestamps of particular offsets (those were consumer group are) to calculate LAG but in time.

**Comment by twmb** [comment]
kadm.ListStartOffsets to get the start,
kadm.ListEndOffsets to get the end,
and then for all commits, kgo.NewClient(kgo.ConsumePartitions(...)) to specify the offset to consume at, consume a single record, and close the client.
