### ISSUE TITLE
Panic when calling `client.OptValue(kgo.WithLogger)` when logger was not set.

### ISSUE THREAD

**Issue by sgtsquiggs** [twmb/franz-go#656]
Came across this while writing unit tests to assert I was configuring a client properly.

Wrong assumption made at [pkg/kgo/client.go#L239-L243](https://github.com/twmb/franz-go/blob/master/pkg/kgo/client.go#L239-L243):

```go
case namefn(WithLogger):
	if cfg.logger != nil {
		return []any{cfg.logger.(*wrappedLogger).inner}
	}
	return []any{nil}
```

The default logger is type `*nopLogger` [pkg/kgo/config.go#L447](https://github.com/twmb/franz-go/blob/master/pkg/kgo/config.go#L447)

**Comment by twmb** [comment]
Good find, the fix should be easy. Since this is a bit minor, I'll probably wait until he next release -- unless there's another bug that necessitates an earlier patch.
