### ISSUE TITLE
gssapi

### ISSUE THREAD

**Issue by lchaxian** [twmb/franz-go#657]
how can i use gssapi keytab ，Can you give a sample code

**Comment by twmb** [comment]
Unfortunately I cannot give specific example code I've written, I've never used Kerberos. I am interested, though.

I do know a few usages of gssapi, though:
Clickhouse sinker: https://github.com/housepower/clickhouse_sinker/blob/f64cea3712bbc84a2e99f12a0f92c7ca9d9c42c6/input/kafka_franz.go#L143-L163
Redpanda's Console: https://github.com/redpanda-data/console/blob/ce9e157f1585a8bfc8e2293f4928a0b4349cdd51/backend/pkg/kafka/config_helper.go#L111-L145

I think this should be a decent enough base.
