### ISSUE TITLE
Partition assignment to consumer in consumer-group is duplicated after consumer restart

### ISSUE THREAD

**Issue by iClaus21** [twmb/franz-go#658]
Hi there,
I have an issue that the same partitions assign to consumer 2 times in a row.

```
<133>1 2024-01-09T01:00:00.077418+00:00 microservice - - main: Start version=0.0.0 commit=...
<135>1 2024-01-09T01:00:00.098722+00:00 microservice - - kafka: Partition assigned topic=topic_name partition=0
<135>1 2024-01-09T01:00:00.098741+00:00 microservice - - kafka: Partition assigned topic=topic_name partition=1
<135>1 2024-01-09T01:00:00.486519+00:00 microservice - - kafka: Partition assigned topic=topic_name partition=0
<135>1 2024-01-09T01:00:00.487011+00:00 microservice - - kafka: Partition assigned topic=topic_name partition=1
```

This happened if reboot one consumer, and after ~5 minutes reboot the another one from one consumer-group.
Can you take a look, please? Can I collect more information for you if needed?

Franz-go v1.15.4, Kafka v3.6.1

**Comment by twmb** [comment]
What's your code that is logging that line? Do you have an OnRevoked or OnLost?

**Comment by iClaus21** [comment]
Sure, of course we have OnAssigned, OnRevoked and OnLost.
``` go
func (v *Kafka) onPartitionsAssigned(_ context.Context, _ *kgo.Client, assigned map[string][]int32) {
	for topic, partitions := range assigned 
		for _, partition := range partitions 
			v.Log().Debug("Partition assigned")
}
func (v *Kafka) onPartitionsLost(_ context.Context, _ *kgo.Client, lost map[string][]int32) {
	...
	v.Log().Debug("Partition lost")
}
func (v *Kafka) onPartitionsRevoked(_ context.Context, _ *kgo.Client, revoked map[string][]int32) {
	...
	v.Log().Debug("Partition revoked")
}
...
opts = append(opts, kgo.OnPartitionsAssigned(v.onPartitionsAssigned))
opts = append(opts, kgo.OnPartitionsLost(v.onPartitionsLost))
opts = append(opts, kgo.OnPartitionsRevoked(v.onPartitionsRevoked))
```

Also, during the settings up the kafka client I set these settings:

1. kgo.DisableAutoCommit()
2. kgo.BlockRebalanceOnPoll()
3. kgo.RequireStableFetchOffsets()
4. kgo.FetchIsolationLevel(kgo.ReadCommitted())
5. kgo.RebalanceTimeout(...)
6. kgo.ConsumeResetOffset(kgo.NewOffset().AtEnd())


How to reproduce the issue:

1. Create topic with 4 partitions
2. Run 2 consumers in consumer_group for created topic: 'consumer1', 'consumer2'. 
3. Waiting until partitions 0, 1 will assign to 'consumer1', partitions 2, 3 will assign to 'consumer2'
4. Restart 'consumer2'
5. Wait until partitions 2, 3 will assign to 'consumer2'
6. Restart 'consumer1'
7. See the logs

**Comment by twmb** [comment]
I don't have the time right now to really write the code to recreate the scenario right now. What you have looks correct. Is it possible to create a small snippet that repro's this that I can run locally? That'd allow me to dive straight into the logs and either answer or find a bug.

**Comment by iClaus21** [comment]
Okay, I'll make a small program to reproduce the error.

**Comment by iClaus21** [comment]
@twmb https://github.com/iClaus21/twmb-iss658
You need to specify TLS keys if enabled, or comment the code part.
And specify the topic name.
I reproduced the issue in this repo.

**Comment by twmb** [comment]
I've ran it a few times and I'm not seeing it.

<img width="555" alt="Screenshot 2024-01-29 at 9 08 12 PM" src="https://github.com/twmb/franz-go/assets/1283109/ae10978c-74c7-4ebd-90cd-6ec9ffa6bbe3">

**Comment by twmb** [comment]
Closing for now, please let me know if there's something further to go on. Apologies I haven't been able to make progress but, you're describing something I haven't seen nor am able to reproduce.

**Comment by twmb** [comment]
I wonder if you're running into what #705 ran into; if so, I have a fix in the next release.
