### ISSUE TITLE
ConsumeResetOffset AtEnd causes `LEADER_NOT_AVAILABLE` error

### ISSUE THREAD

**Issue by MarcinGinszt** [twmb/franz-go#659]
In my integration tests, I'm pushing some messages to Kafka topic `kafka-test-topic` and then I'm consuming them them.
I'm using franz-go version `v1.15.4`.

If I am using one of the the offsets
`kgo.ConsumeResetOffset(kgo.NewOffset().AfterMilli(time.Now().Unix())),` 
or
`kgo.ConsumeResetOffset(kgo.NewOffset().AtStart()),`
or not specifying offset at all, then there is not error and I'm successfully retrieving the event.

If the client- consumer has set option `kgo.ConsumeResetOffset(kgo.NewOffset().AtEnd())`, I can't retrieve the messaeg and I'm getting the error-
```
INF assigning partitions why="newly fetched offsets for group my-group" how="assigning everything new, keeping current assignment" input="kafka-test-topic[0{-1 e-1 ce0}]"
INF metadata update triggered why="loading offsets in new session from assign"
INF metadata update triggered why="fetch had inner topic errors from broker 1001: UNKNOWN_TOPIC_OR_PARTITION{kafka-test-topic[0]}"
INF metadata update triggered why="re-updating due to inner errors: LEADER_NOT_AVAILABLE{kafka-test-topic}"
```

Is that expected behaviour?

**Comment by twmb** [comment]
What is your cloud provider? I wouldn't expect to see UnknownTopicOrPartition if the partition exists -- which it does, clearly, by the next error. I would expect to see LeaderNotAvailable occasionally: this implies the broker is rebalancing partitions, and the partition you're asking for is currently leaderless. Both of these errors are retryable, and fetching will resume eventually once the broker recovers.

**Comment by MarcinGinszt** [comment]
> What is your cloud provider?

This was done locally, against the Kafka container. I tried both the confluent container and redpanda testcontainers. 

> I would expect to see LeaderNotAvailable occasionally: this implies the broker is rebalancing partitions, and the partition you're asking for is currently leaderless. Both of these errors are retryable, and fetching will resume eventually once the broker recovers.

As mentioned, this error happens consistently with this particular setting.

It there any more information I could provide?

**Comment by twmb** [comment]
Is it possible to provide a tiny docker compose and repro I can run?

**Comment by twmb** [comment]
Closing for now, let me know if you have more details. For some context, this library is used extensively in Redpanda tests and I haven't seen a similar issue there. A quick way to confirm is to run something like, `rpk topic consume ${topic} -oend`
