### ISSUE TITLE
no revoked message when rebalance

### ISSUE THREAD

**Issue by dhtong** [twmb/franz-go#660]
is a revoke or lost message guaranteed? I have noticed that my consumer didn't seem to have received one when it got kicked out of the group. if it should be guaranteed, Is this more likely a server issue or could be something on the client side?

in the case i was looking at, the consumer got kicked out was the leader. almost as soon as partitions were assigned to the consumer, it got a ```heartbeat errored``` with ```REBALANCE_IN_PROGRESS: The group is rebalancing, so a rejoin is needed.``` however there was no revoke or lost.
the message i got indicating it was kicked out was ```in default commit: unable to commit offsets for topic partition` and the err was `UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.```

**Comment by twmb** [comment]
Can you paste more info level logs around this event?

**Comment by twmb** [comment]
Let me know if you're able to add details, closing for now.
