### ISSUE TITLE
Getting Rate Limiting Statistics

### ISSUE THREAD

**Issue by hendoxc** [twmb/franz-go#667]
As part of librdkafka, a `throttle` object is available from the statistics messages returned. this allows clients to detect when they are being rate limited by the client.

Is there a way to achieve this in, `kgo`? While the metrics are good, I would like to log when the client is receiving non zero throttle response times from the broker, to make it easier to quickly identify the issue is rate limiting.

**Comment by twmb** [comment]
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#HookBrokerThrottle
You can use this hook
