### ISSUE TITLE
Rename the SaramaHasher or un-deprecate because it's needed for compatibility with other language libraries

### ISSUE THREAD

**Issue by jgeiger-trane** [twmb/franz-go#669]
I know this might be an odd request since this was just added, but the change the the hasher will break apps for people co-partitioning Kafka topics when publishing from other languages using crc32.

I previously commented on an [issue in the IBM/sarama package](https://github.com/IBM/sarama/issues/1213) discussing this partitioning problem. The fix there was to modify the Sarama balancer plan into a custom version for Ruby compatibility. 

The newly deprecated `kgo.SaramaHasher` was compatible with the Ruby code and librdkafka when calculating partitions so it does serve a purpose, even if it may have been incorrectly named?

Below is an example which tests both the old and new hashers and a snippet to show how it works in Ruby.

```go
newH := kgo.SaramaCompatHasher(crc32.ChecksumIEEE)
oldH := kgo.SaramaHasher(crc32.ChecksumIEEE) // nolint:staticcheck

newP := newH([]byte("test"), 840)
oldP := oldH([]byte("test"), 840)

println("SaramaCompatHasher:", newP)
println("SaramaHasher:", oldP)

"SaramaCompatHasher":180
"SaramaHasher":76
```

```ruby
irb(main):002:0> Zlib.crc32("test") % 840
=> 76
```

**Comment by twmb** [comment]
I see. I don't think this was compatible with librdkafka unless librdkafka has a way to specify custom partition strategies (I'm not looking that deep) -- what I see in librdkafka is https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_msg.c#L1031-L1131, which offers murmur2, fnv1a, and uniform random distribution.

However, my guess is that the Ruby library copied Sarama, vise versa.

I can remove the `Deprecation` bit, reword the comment (i.e. it does not match Sarama identically), and note that the SaramaHasher is identical to the Zendesk Ruby hasher. Do you know any others that should be mentioned in the comment?

**Comment by jgeiger-trane** [comment]
One of the defaults `consistent` is the crc32 partitioner in librdkafka
https://github.com/confluentinc/librdkafka/blob/2dff2ebce9dc7e75c0138504b386902384d70eb9/src/rdkafka_msg.c#L1044C1-L1051C2

If you use the github to search for `rd_crc32` in that repository, you get the function that partitioner calls. It looks like it might even be using zlib as well which matches with how the ruby-kafka library does its strategy.
https://github.com/confluentinc/librdkafka/blob/2dff2ebce9dc7e75c0138504b386902384d70eb9/src/rdcrc32.h#L36

Really for me removing the deprecation warning is probably enough since golangci-lint flags it as bad due to staticcheck.

I was more trying to point out that it's actually a valid hasher beyond just Sarama, which I actually believe did its own thing outside of Ruby or librdkafka for some reason.

I'm not sure what a better name for the function would be though.

Thank you.

**Comment by twmb** [comment]
Too late to rename, and I don't know a good name anyway (it's very specific mod behavior), so imo better to just undeprecate and call out in the docs a few potential other-library compatibilities.
