### ISSUE TITLE
Guidance on Manual Commit error with group consumer

### ISSUE THREAD

**Issue by hugokitano** [twmb/franz-go#671]
I'm a bit confused by the Manual Commit example. Even though the example includes a groupID, I cannot figure out how to set it upon manual commit. 

```golang 
        \\ initial options
	var opts []kgo.Opt
        opts = append(opts, kgo.DisableAutoCommit())
	opts = append(opts, kgo.DialTLSConfig(&tls.Config{InsecureSkipVerify: true}))
	opts = append(opts, kgo.FetchMaxWait(1000 * 60 * 20*time.Millisecond)) // 20 minutes
	opts = append(opts, kgo.RequestTimeoutOverhead(time.Duration(inputs.RequestTimeoutMs) *time.Millisecond))
	opts = append(opts, kgo.RequiredAcks(kgo.AllISRAcks()))
	opts = append(opts, kgo.ProducerBatchCompression(kgo.Lz4Compression()))
	opts = append(opts, kgo.RecordRetries(5))

	initialOpts := opts
	initialOpts = append(initialOpts, kgo.ConsumeTopics(topic))
	initialOpts = append(initialOpts, kgo.ConsumerGroup(groupID))

        cl, err := kgo.NewClient(initialOpts...)
	if err != nil {
		return nil, errors.Wrap(err, "Could not create Kafka client")
	}
	adm := kadm.NewClient(cl)

	//Necessary for manual commits? I hadn't added this originally
	os, err := adm.FetchOffsetsForTopics(ctx, groupID, topic)
	if err != nil {
		return nil, errors.Wrapf(err, "Could not fetch offsets for groupID %s and topic %s", groupID, topic)
	}
	opts = append(opts, kgo.ConsumePartitions(os.KOffsets()))
	cl, err = kgo.NewClient(opts...)
	if err != nil {
		return nil, errors.Wrap(err, "Could not create Kafka client with offsets")
	}
```
This raises an error `invalid autocommit options specified when a group was not specified` at the very last error check.  My goal is to call `adm.CommitAllOffsets(ctx, GroupID, kadm.OffsetsFromFetches(fetches))` after a `fetches := cl.PollRecords(ctx, batchSize)` call.

**Comment by twmb** [comment]
You can't do external admin committing while a group is active,
but in your example you're also not committing with a group.
You don't need kgo.ConsumerGroup in the kadm call. kgo.ConsumerGroup is used for fetching.

Do you mean for the client to join the group, or not?
If you want to do manual committing from a client that is actively in a group, you have to use kgo APIs. Notably, any of these:
[func (cl *Client) CommitOffsets(ctx context.Context, uncommitted map[string]map[int32]EpochOffset, ...)](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.CommitOffsets)
[func (cl *Client) CommitOffsetsSync(ctx context.Context, uncommitted map[string]map[int32]EpochOffset, ...)](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.CommitOffsetsSync)
[func (cl *Client) CommitRecords(ctx context.Context, rs ...*Record) error](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.CommitRecords)
[func (cl *Client) CommitUncommittedOffsets(ctx context.Context) error](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.CommitUncommittedOffsets)

Which, given your goal, I would recommend CommitUncommittedOffsets.

The admin client is meant for usages _outside_ the context of a standard producer/consumer -- it's meant for admin stuffs. You can't commit to an active group; commiting via an admin client is meant to adjust offsets for a stopped group.
