### ISSUE TITLE
wait for reconnect with backoff

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#68]
i'm simulate kafka server down via adding lag/packet drops or disconnect.
you package works fine and try to reconnect but
```
{"addr":"127.0.0.1:29091","broker":"seed 1","caller":"kgo/broker.go:558","level":"debug","msg":"opening connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.1:29091","broker":"seed 1","caller":"kgo/broker.go:568","err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"127.0.0.1","Port":29091,"Zone":""},"Err":{"Syscall":"connect","Err":61}},"level":"warn","msg":"unable to open connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.2:29092","broker":"seed 2","caller":"kgo/broker.go:558","level":"debug","msg":"opening connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.2:29092","broker":"seed 2","caller":"kgo/broker.go:568","err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"127.0.0.2","Port":29092,"Zone":""},"Err":{"Syscall":"connect","Err":61}},"level":"warn","msg":"unable to open connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.1:29091","broker":"1001","caller":"kgo/broker.go:558","level":"debug","msg":"opening connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.1:29091","broker":"1001","caller":"kgo/broker.go:568","err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"127.0.0.1","Port":29091,"Zone":""},"Err":{"Syscall":"connect","Err":61}},"level":"warn","msg":"unable to open connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.3:29093","broker":"seed 0","caller":"kgo/broker.go:558","level":"debug","msg":"opening connection to broker","timestamp":"2021-08-23 23:12:59"}
{"addr":"127.0.0.3:29093","broker":"seed 0","caller":"kgo/broker.go:568","err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"127.0.0.3","Port":29093,"Zone":""},"Err":{"Syscall":"connect","Err":61}},"level":"warn","msg":"unable to open connection to broker","timestamp":"2021-08-23 23:12:59"}
```
as you see - it tries to connect without waiting, so it try to ddos kafka server if it have low resources and also spam in logs.
what you think about adding some func that can add backoff for reconnecting ?

**Comment by twmb** [comment]
There is a function, `RetryBackoffFn`. The default strategy is to start at 100ms and exponentially backoff with jitter to 1s (this mirrors the behavior described in [KIP-144](https://cwiki.apache.org/confluence/display/KAFKA/KIP-144%3A+Exponential+backoff+for+broker+reconnect+attempts)).

I think the timestamp resolution in your logs may not be fine grained enough -- try adding milliseconds with `.999` if this is from time.Format.

I'd be opening to changing the default backoff to 250ms rather than 100, and bumping the max backoff to 2.5s or 5s, though. Let me know if upping the time format resolution shows some backoff?

**Comment by twmb** [comment]
Is this for producing, or general admin requests?

Producing already has unlimited retries by default, with acks == -1.
Admin requests have a 1min timeout. I recommend keeping that, but there does exist a RetryTimeout option.

**Comment by vtolstov** [comment]
this question for consuming. so i'm run client.PollFetches and want it connection is dies - auto reconnect to kafka brokers and continue fetching.

**Comment by twmb** [comment]
That's the default behavior already, and I think that's the behavior for any client. Any kafka client should continue to reconnect for fetching (with some backoff)

**Comment by vtolstov** [comment]
ok fine, now experimenting with backoff, thanks

**Comment by twmb** [comment]
:+1: sounds good! Plrease reopen the issue if this isn't worked, I think this is closed.
