### ISSUE TITLE
Inconsistent partitioning strategy 

### ISSUE THREAD

**Issue by akshatraika-moment** [twmb/franz-go#680]
Does kgo have special partitioning logic if we are opting for default key based partitioning? I have 2 services that both write to the same kafka topic. One uses kgo and one uses confluent-kafka-go and the messages are ending up in different partitions.

**Comment by twmb** [comment]
Ah, I would've figured confluent-kafka-go mirrored the Java codebase. ty @yianni.

If that's the case -- SaramaHasher with crc32 I _think_ mirrors librdkafka, per #669

**Comment by akshatraika-moment** [comment]
I see, I'll try that. Appreciate the quick response!

**Comment by twmb** [comment]
Let me know this isn't resolved, closing now

**Comment by akshatraika-moment** [comment]
I was able to resolve this by switching the hash fn. thanks!
