### ISSUE TITLE
topic creation configs

### ISSUE THREAD

**Issue by yakirSalt** [twmb/franz-go#688]
Hi,

I'm trying to create a topic with specific configs such as `cleanup.policy`, but get the error `INVALID_CONFIG: Configuration is invalid.`
what am I doing wrong?
this is a code example:
```
client, err := kgo.NewClient(kgo.SeedBrokers("localhost:9092"))
if err != nil {
  panic(err)
}
admClient := kadm.NewClient(client)
m := map[string]*string{
  "cleanup.policy":  pointy("delete"),
  "retention.bytes": pointy("1000000000"),
  "retention.ms":    pointy("1000000"),
}
res, err := admClient.CreateTopic(ctx, -1, -1, m, topicName)
```
thanks for the help

**Comment by twmb** [comment]
Are you talking to Kafka, or something else (Redpanda, AWS MSK, ...)?
Is there some policy clamp on the broker side of things?
Do you have access to broker logs and, if so, do they indicate the problem?

That _looks_ fine so it should work imo.

**Comment by yakirSalt** [comment]
nvm, found the issue. it works now.
I accidentally passed the wrong values due to pointer issues in Go
