### ISSUE TITLE
Minimum Go version required is now Go 1.16

### ISSUE THREAD

**Issue by Neal** [twmb/franz-go#69]
With 4fb0de2, minimum Go version required for franz-go is Go 1.16 as `net.ErrClosed` only got introduced in 1.16 so [`go.mod`](https://github.com/twmb/franz-go/blob/master/go.mod#L3) should be updated accordingly.

**Comment by twmb** [comment]
@Neal great notice, I think I can replace this with a separate `+build go1.13` file containing `strings.Contains(err.Error(), ...)`.

**Comment by twmb** [comment]
I think this is the only potential problem, but I'm not 100% sure. I do see the klauspost/compress dependency has a go.mod containing go1.15.

I've just downloaded go1.13.15, there were a few other additions that have made this package incompatible with go1.13. What do you think about this targeting 1.15?

**Comment by twmb** [comment]
I've bumped the min version to go1.15 and tested the new commit https://github.com/twmb/franz-go/commit/d5e80b38ca2be44853b776286c6f3c1c4704c403 on go1.15.15, go1.16.4, and go1.17.

I'll leave this untagged momentarily unless another report comes in -- ideally I'll release this with 1.0 shortly (barring other tough to fix bug reports before that).

**Comment by Neal** [comment]
Sounds good, thanks! Just wanted to point out as it broke our build after updating but I just updated to go1.16 so personally don't have any issues with dropping go1.13. And anyways as you mention, go1.15 requirement is good enough as go1.17 is out now.
