### ISSUE TITLE
Any way to assign only commited offsets on rebalance?

### ISSUE THREAD

**Issue by topofstack** [twmb/franz-go#702]
Hi, I'm new to franz and trying to implement the following behavior (looks like it's the default behavior of Sarama lib):

Once group rebalance has finished, assign only commited offsets, even if no partitions have been revoked from this particular consumer.
I'm using `AutoCommitMarks` option.

**Comment by twmb** [comment]
What difference are you seeing in this library?

**Comment by topofstack** [comment]
Sorry, the problem was on my side.
