### ISSUE TITLE
TXN: error beginning transaction: invalid attempt to begin a transaction while already in a transaction

### ISSUE THREAD

**Issue by bentcoder** [twmb/franz-go#748]
Hi,

I have a requirement where a single HTTP request will produce batch messages before returning. For instance, example below loops 9 times for each HTTP request and each iteration produces 10 messages (9*10 = 90). How do we work with transactions for such cases please? Surely we will need a unique txn id but calling `NewClient` for each request wouldn't be ideal.

Thanks

This is for you to reproduce if you wish by calling `k6 run k6.js` . [Install](https://k6.io/docs/get-started/installation/) k6.

NOTE: I am planning to switch from Sarama which has a similar issue but comes with data race instead ;)

```bash
// k6.js

import http from "k6/http";
import { check } from "k6";

export let options = {
    vus: 99,
    duration: "10s"
};

export default function() {
    let response = http.get("http://localhost:8888/");

    check(response, {
        "200 OK": (r) => r.status === 200,
        "response < 100 ms": (r) => r.timings.duration < 100
    });
}
```

Example HTTP API. Copied the producer code from the [doc](https://github.com/twmb/franz-go/blob/master/examples/transactions/produce_and_consume/transactional_producer.go).

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"

	"github.com/twmb/franz-go/pkg/kerr"
	"github.com/twmb/franz-go/pkg/kgo"
)

func main() {
	producerId := strconv.FormatInt(int64(os.Getpid()), 10)
	client, err := kgo.NewClient(
		kgo.SeedBrokers([]string{":9093"}...),
		kgo.TransactionalID(producerId),
		kgo.DefaultProduceTopic("warnings-topic"),
	)
	if err != nil {
		fmt.Printf("error initializing Kafka producer client: %v\n", err)
		return
	}
	defer client.Close()

	api := api{client: client}

	rtr := http.NewServeMux()
	rtr.HandleFunc("GET /", api.handle)

	log.Println(http.ListenAndServe(":8888", rtr))
}

type api struct {
	client *kgo.Client
}

func (a api) handle(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	batch := 0
	for {
		if err := a.client.BeginTransaction(); err != nil {
			fmt.Printf("error beginning transaction: %v\n", err)
			break
		}

		// Write some messages in the transaction.
		if err := produceRecords(ctx, a.client, batch); err != nil {
			fmt.Printf("error producing message: %v\n", err)
			rollback(ctx, a.client)
			continue
		}

		// Flush all of the buffered messages.
		//
		// Flush only returns an error if the context was canceled, and
		// it is highly not recommended to cancel the context.
		if err := a.client.Flush(ctx); err != nil {
			fmt.Printf("flush was killed due to context cancelation\n")
			break // nothing to do here, since error means context was canceled
		}

		// Attempt to commit the transaction and explicitly abort if the
		// commit was not attempted.
		switch err := a.client.EndTransaction(ctx, kgo.TryCommit); err {
		case nil:
		case kerr.OperationNotAttempted:
			rollback(ctx, a.client)
		default:
			fmt.Printf("error committing transaction: %v\n", err)
		}

		batch += 1

		if batch == 9 {
			break
		}
	}

	fmt.Println("producer exited")
}

func produceRecords(ctx context.Context, client *kgo.Client, batch int) error {
	for i := 0; i < 10; i++ {
		message := fmt.Sprintf("batch %d record %d\n", batch, i)
		if err := client.ProduceSync(ctx, kgo.StringRecord(message)).FirstErr(); err != nil {
			return err
		}
	}
	return nil
}

func rollback(ctx context.Context, client *kgo.Client) {
	if err := client.AbortBufferedRecords(ctx); err != nil {
		fmt.Printf("error aborting buffered records: %v\n", err) // this only happens if ctx is canceled
		return
	}
	if err := client.EndTransaction(ctx, kgo.TryAbort); err != nil {
		fmt.Printf("error rolling back transaction: %v\n", err)
		return
	}
	fmt.Println("transaction rolled back")
}

```

**Comment by twmb** [comment]
My guess is that you're occasionally hitting an error before `EndTransaction` is called -- likely due to the client going away, so the request's Context being canceled. Does it work if you add a `defer client.EndTransaction(notTheRequestContext, kgo.TryAbort)`?

**Comment by bentcoder** [comment]
The client is initialised in `main.go` only once and passed to the HTTP handler where this client is used for every new requests. As far as I understand, the transaction id is hardly coupled to the client at initialisation and we won't be able to dynamically change it for each HTTP request. Due to the fact, it always produces `error beginning transaction: invalid attempt to begin a transaction while already in a transaction` error (still happening even if I use `ctx := context.Background()`).

I think if there was something like `client.BeginTransaction(new-transaction-id-per-request)` it would solve the issue.

**Comment by twmb** [comment]
Right yeah that's not really a thing in clients. While _technically_ you can use multiple transactions per client, doing so would make the guts of a client much more difficult to implement and no client that I'm aware of supports this.

Internally, a client issues InitProducerID request with the transactional ID before the txnal ID can ever be used. The string txnalID is mapped to a producer ID and epoch, and these are used per batch internally when producing. _Technically_ you could go through a lot of effort to support multiple txnal IDs for the end user at the API level, but the effort is quite large. The client would also have to be very careful to protect you against accidentally leaving a transaction open for one ID when you intend to begin a transaction for a separate ID.

Worse, transactional IDs _are_ tightly coupled throughout the client when group consuming. _Technically_ you can design a client that allows different groups within the same client, but this gets even more crazy and I don't even know what those APIs would look like.

Anyway, now that I understand more -- you definitely can't use a transactional ID per request, nor really a different transactional ID per client. I see you're thinking of pooling in #750, which answers half of the problem. I'll close this issue.
