### ISSUE TITLE
Clarify producer batch config, once again

### ISSUE THREAD

**Issue by kirilldd2** [twmb/franz-go#749]
Hello,
Sorry for yet another issue about franz-go config, but I had a hard time putting it all together by myself. My main question is about `ProducerLinger` and how it's combined with other producer settings. My assumptions are:

- `ProducerLinger`: flush when the linger for partition is hit or ...
- `ProducerBatchMaxBytes`: if a record's size exceeds this value it can't be produced and error is returned with callback
- `ProducerBatchMaxBytes` + `ProducerLinger`: according to @twmb 's [statement](https://github.com/twmb/franz-go/issues/591#issuecomment-1758117829) if batch hits this value it is flushed even if the linger wasn't hit (really surprising to me, learnt about it just yesterday, while browsing through issues)
- `MaxBuffered[Records|Bytes]`: if producer buffer's size hits this value, then produce blocks until there is space in the buffer
- [prior to v1.17.0] `MaxBuffered[Records|Bytes]` + `ProducerLinger`: if producer buffer's size hits this value, then produce blocks and the buffer is flushed only when the linger is hit
- [since v1.17.0] `MaxBuffered[Records|Bytes]` + `ProducerLinger`: if producer buffer's size hits this value, then the buffer is flushed. Once the buffer is not full, it is flushed when the the linger is hit

Is all above correct or am I missing something?

Thanks.

**Comment by twmb** [comment]
Accurate.

Note that lingering is per partition. This is why in pt3, if a partition has a batch that's full, that individual partition triggers a flush to the broker. When creating a request to the broker, any other partition that has data that can be sent (even if it is actively lingering and does not have a full batch). I'm wondering why this is surprising?

I'm open to some documentation improvements too. There are a lot of knobs to fine tune exactly what you want, but unfortunately that makes things a bit confusing if you actually look into customizing any of the knobs. Is the client missing some behavior you'd prefer?

**Comment by kirilldd2** [comment]
Well, maybe it's just me :D. The name `ProducerBatchMaxBytes` is really self-explanatory, but what happens when a batch hits that limit if lingering is enabled? It could either block like `MaxBuffered...` did before v1.17.0 or flush like it actually is. I kinda see it now in the docs, but it's quite vague to be honest.

I didn't get much trouble configuring the client aside from that, so after v1.17.0 I'm happy with what we have.

One thing that I would really like is an interface for the client. What I mean is in functions like `kgo.AbortingFirstErrPromise`, `kadm.NewClient` and maybe some others accept interface instead of `*kgo.Client`. It would be great for extensibility of `*kgo.Client` and custom wrappers.

Thank you for clarifying!

**Comment by twmb** [comment]
Interface, not planning on it due to the reasons given here: https://github.com/twmb/franz-go/issues/58#issuecomment-896368502


For vagueness, yeah I'm not really sure what to do -- if you have an idea to improve the docs I'm definitely willing to merge PRs -- I tend to touch up API docs whenever I revisit the APIs, but in this case right now I don't have a better idea.
