### ISSUE TITLE
Support for polling records with a timeout

### ISSUE THREAD

**Issue by nchinmay** [twmb/franz-go#75]
Is there a plan to support the functionality to poll for records with a timeout duration?
https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#poll(java.time.Duration)

**Comment by nchinmay** [comment]
The pause resume functionality would also be very helpful

**Comment by twmb** [comment]
Polling with a timeout is already supported by using `context.WithTimeout` on the input timeout.

I didn't know about the pause / unpause -- what is the use case? That'd be a pretty large undertaking to wire the feature into the client.

**Comment by nchinmay** [comment]
> Polling with a timeout is already supported by using `context.WithTimeout` on the input timeout.
> 
> I didn't know about the pause / unpause -- what is the use case? That'd be a pretty large undertaking to wire the feature into the client.

It's good to know that polling with timeout is supported. Is there an example by any change? I am also hoping that setting `context.WithTimeout` on the context will not affect anything other than the pollRecords()

For Pause/Resume, my use case is -> I am reading data from multiple topics. Each topic has a priority associated with it. When a high priority topic is being consumed, I want to pause consumption of lower priority topics. Right now I am implementing this by creating a kgo.Client (consumer) per topic and basing my decision on whether `Consumer.pollRecords` returned data for a high priority topic or not to decide whether I should call `pollRecords` on low priority topic consumers.

**Comment by twmb** [comment]
There is no example, but the idiom is pretty common. I'd welcome an additional example though. The context only affects the polling function, it does not get wired down further into the client to affect anything else.

I took a look at how the Java client implements pausing and unpausing. After the point of pausing, it avoids returning any partitions it currently has buffered if they are paused. When it goes to determine whether to fetch, it excludes paused partitions, even if they are buffered internally.

I think I can implement this, but I'd like to make a simplification: pausing will mean that no further _fetches_ can happen for paused partitions, but any _currently buffered_ data for the paused partitions can still be returned. In the end this will be the same result: after a poll or two, you'll no longer get data for what is paused, but it does mean there is a draining stage that doesn't exist in the Java client.

This would make implementation a lot easier and it'll be easier to reason about correctness. What do you think of this?

**Comment by nchinmay** [comment]
> I took a look at how the Java client implements pausing and unpausing. After the point of pausing, it avoids returning any partitions it currently has buffered if they are paused. When it goes to determine whether to fetch, it excludes paused partitions, even if they are buffered internally.
> 
> I think I can implement this, but I'd like to make a simplification: pausing will mean that no further _fetches_ can happen for paused partitions, but any _currently buffered_ data for the paused partitions can still be returned. In the end this will be the same result: after a poll or two, you'll no longer get data for what is paused, but it does mean there is a draining stage that doesn't exist in the Java client.
> 
> This would make implementation a lot easier and it'll be easier to reason about correctness. What do you think of this?

I think that behavior where you allow for draining of already-received messages would be desirable to me instead of having messages buffered inside the kafka layer. Thank you.

**Comment by twmb** [comment]
This was relatively small to support, if you could try https://github.com/twmb/franz-go/commit/33635e2d56d99b90207a0f5da4256db8b463476b let me know if it works. I plan to tag it in the 1.0 release either tomorrow or Monday (and I don't think this API needs to be revised before then).

**Comment by twmb** [comment]
This has been tagged in v0.11.1, let me know how it works for you!

**Comment by nchinmay** [comment]
Thank you. I'll test it and report back if I see any issues!
