### ISSUE TITLE
Confluent: Unable to create a topic due to policy violation

### ISSUE THREAD

**Issue by Amogh-Bharadwaj** [twmb/franz-go#751]
This issue is related to an attempt to create a topic (using the kadm package) in a Confluent cluster.

### Implementation
Admin client is created with the following configurations:
```
		kgo.SeedBrokers(config.Servers...),
		kgo.AllowAutoTopicCreation(),
		kgo.WithLogger(kslog.New(slog.Default()))
```
and with `kadm.NewOptClient(aboveOptions...)`

The request is as follows:
```golang
// 5 partitions, replicationFactor of 1, no other configs
adminClient.CreateTopics(ctx, 5, 1, nil, "mytopic")
```
Both the .CreateTopic() and the.CreateTopics() methods fail with:
```golang
POLICY_VIOLATION: Request parameters do not satisfy the configured policy.
```

I am aware that the issue could be something related to Confluent technicalities, but just wanted to know if there is something configurable from the franz-go side to get through this. Does kadm have support for Confluent Cloud?

**Comment by twmb** [comment]
kgo works with Confluent cloud -- it's all client protocol stuff, and you can make this client look like any other by changing the client ID. Do you have any broker logs? It sounds like you have too many topics or partitions in the cluster already?

**Comment by Amogh-Bharadwaj** [comment]
Turns out Confluent has a policy which mandatorily required replication factor be equal to 3. This error message was revealed when I tried the same thing using confluent-kafka-go, then switched back to franz-go and it's working now :)

**Comment by twmb** [comment]
Where did you see the error? The same information should be visible from kadm... I think the problem is that kadm doesn't include a CreateTopicsResponse.ErrorMessage field right now, which it should. I'm going to reopen this to track adding that field as an enhancement, and potentially audit other result structs at the same time.
