### ISSUE TITLE
Question: Why does kgo.StopProducerOnDataLossDetected() exist?

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#763]
Under what conditions can data loss happen? And which of those does this detect?

**Comment by twmb** [comment]
If you have the majority of replicas crash unrecoverably, you may lose data. If you're producing during this crash and leadership transfers to a broker that is not caught up with the nodes that crashed, it notifies the client that it does not recognize the offset being produced to. At this point, the client notices that the broker lost data.

**Comment by asg0451** [comment]
Gotcha, thanks!
