### ISSUE TITLE
Feature request: expose metadata to the user

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#765]
I have a use case where I need to iterate over all the known partitions for each topic. With the current API I must construct a kmsg.MetadataRequest, send it myself via Client.Request(), and cache the response. Can we add a client method to return at least some subset of the already cached metadata?

**Comment by twmb** [comment]
Have you seen the kadm package, particularly https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.Metadata or https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.ListTopics ?

How frequently are you requesting metadata such that you need to use a cached version? The client itself bypasses the cache for requests, and if you need the response cached -- couldn't you cache the response?

**Comment by asg0451** [comment]
I didn't think to look at this other package, using those methods and caching myself is a fine solution. Thanks!
