### ISSUE TITLE
Documentation request / question

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#768]
I've been struggling to understand exactly how franz does batching/buffering of records. If I'm sending in record after record for a given topic-partition, how large will franz's batches be? And is there a way to configure it. What is the procedure it uses? Reading the code and available options did not enlighten me.

**Comment by twmb** [comment]
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#ProducerBatchMaxBytes
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#ProducerLinger

* Is any data available, and is the client ready to create a batch? If yes, cut batch and send it. This can happen immediately after you Produce one record. If you have high record throughput, eventually you'll reach backpressure while enough produce requests are in flight that you'll send larger batches.
* If the client cannot send a new batch at the moment (maybe max in flight has been reached, maybe linger is configured), has the maximum amount for a single batch been buffered? If yes, cut batch, begin buffering new batch internally.
