### ISSUE TITLE
Unable to specify LZ4 compression level

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#778]
CompressionCoded.WithLevel casts its argument to byte and maxes out at 127. - https://github.com/twmb/franz-go/blob/a5f2b710830e32fc3f90374be47ec59849807342/pkg/kgo/compression.go#L71

However, LZ4 compression levels are much larger than that - https://github.com/pierrec/lz4/blob/v4/options.go#L155 - they are defined as 0, 512, 1024, ... , 131072.

Specifying LZ4 compression level in franz-go therefore will always result in the default.

**Comment by twmb** [comment]
I think this should be a relatively small fix by converting that internally to an int

**Comment by asg0451** [comment]
i agree. i can take a stab at this today.

**Comment by asg0451** [comment]
https://github.com/twmb/franz-go/pull/781
