### ISSUE TITLE
List partition reassignments by topic

### ISSUE THREAD

**Issue by peter-evans** [twmb/franz-go#78]
Hi,

I've bumped into an issue that has completely stumped me. I'm trying to request reassignments in progress for a specific topic and it doesn't seem to work. I can get the code to return all topics by commenting out the part where it appends to `req.Topics`, but if I specify a topic that I know has ongoing reassignments it doesn't return it.

I've been working to try and get to the bottom of the problem by switching out my implementation for bits of your implementation [here](https://github.com/twmb/kcl/blob/master/commands/admin/partas/partition_assignments.go#L118-L133). This is a snippet of what I'm currently trying.
```go
	topic := "my_test_topic"

	req := &kmsg.ListPartitionReassignmentsRequest{
		TimeoutMillis: cl.TimeoutMs(),
	}

        // Copied from kcl for debugging purposes
	tps := make(map[string][]int32)
	if len(topic) > 0 {
		tps[topic] = nil
		// Tried this too, but no luck
		// tps[topic] = []int32{}
	}

        // If I comment out this section then it successfully returns all topics that have reassignments in progress
	for topic, partitions := range tps {
		req.Topics = append(req.Topics, kmsg.ListPartitionReassignmentsRequestTopic{
			Topic:      topic,
			Partitions: partitions,
		})
	}

	kresp, err := cl.Client().Request(context.Background(), req)
	if err != nil {
		return nil, err
	}
	resp := kresp.(*kmsg.ListPartitionReassignmentsResponse)

	if err := kerr.ErrorForCode(resp.ErrorCode); err != nil {
		return nil, fmt.Errorf(*resp.ErrorMessage)
	}

	for _, topic := range resp.Topics {
		for _, p := range topic.Partitions {
			fmt.Printf("Topic: %s Partition %s: +%d -%d\n", topic.Topic, fmt.Sprint(p.Partition), len(p.AddingReplicas), len(p.RemovingReplicas))
		}
	}
```
Any ideas what I'm doing wrong? Or is this perhaps a bug?

I'm using franz-go v0.11.0 and Kafka 2.8.0.

**Comment by twmb** [comment]
Are you specifying any partitions in these topics? If not, if you directly specify a topic at all, you also have to specify any partitions in that topic.

**Comment by peter-evans** [comment]
The kcl implementation seems to work without specifying partitions, though. [This part](https://github.com/twmb/kcl/blob/dad6a73ac64fbde24bc6a7774a57afb92fa46b3a/flagutil/flagutil.go#L17-L20) sets the partitions to `nil` if you only specify the topic name.

I've also tried this command and it works, which makes it all the more confusing why my code does not.
`kcl admin partas list my_test_topic `

**Comment by twmb** [comment]
I just had to double check that myself because that sure did look confusing, but after staring at this code a bit, are you using the `-t` flag?

`kcl admin partas list` requires a `-t` flag to set the topics / partiitons to list -- I actually should change that code to `cobra.ExactArgs(0)` or, even better, just drop the `-t` flag and use the input arguments. I'm not sure why I didn't, but currently right now `kcl` is silently ignoring your topic and instead defaulting to everything because the `-t` flag is not used.

**Comment by peter-evans** [comment]
Ah, it makes sense now! I wasn't using the `-t` flag so it was just defaulting to everything.
That probably means that the following command won't work, similar to my code.
`kcl admin partas list -t my_test_topic`

So just to clarify, the API requires all partitions to be specified? There is no way to say "give me all the partitions for this topic?"

**Comment by twmb** [comment]
Yeah, I checked the Kafka source earlier once I saw this issue (and mildly remember checking it for my same confusion when I first implemented this in kcl). If you want all partitions for a topic, you'll have to issue a metadata request beforehand. I do a similar thing now in `kcl misc list-offsets foo`: https://github.com/twmb/kcl/blob/dad6a73ac64fbde24bc6a7774a57afb92fa46b3a/commands/misc/misc.go#L616

**Comment by peter-evans** [comment]
Got it. Thank you for clearing this up! Really appreciate the quick response, too. ❤️ 

By the way I just tested this command and it silently doesn't work, similar to my code. It might be best to return an error [here](https://github.com/twmb/kcl/blob/dad6a73ac64fbde24bc6a7774a57afb92fa46b3a/flagutil/flagutil.go#L18) so the user knows that they must specify partitions with the topic name.
`kcl admin partas list -t my_test_topic`

**Comment by twmb** [comment]
I think I actually use the non-specified partitions in some handlers actually (notably that misc command, at least) ... but I should return an error when an empty partition list does nothing.
