### ISSUE TITLE
Error on kadm/UserSCRAMs calls with redpanda 

### ISSUE THREAD

**Issue by dmytzo** [twmb/franz-go#780]
When I call any `UserSCRAMs` related methods (AlterUserSCRAMs, DescribeUserSCRAMs), I get 

```
broker is too old; the broker has already indicated it will not know how to handle the request
```

https://github.com/twmb/franz-go/blob/a5f2b710830e32fc3f90374be47ec59849807342/pkg/kgo/broker.go#L325

```
pkg version: latest
redpanda versions: v24.1.9, v23.3.17
```

**Comment by twmb** [comment]
Please use this as a feature request against Redpanda, which does not yet support these requests.

**Comment by dmytzo** [comment]
@twmb thanks!

**Comment by twmb** [comment]
lmk when you create the issue, I'm interested in following it :)

**Comment by Jrc356** [comment]
@dmytzo did you make an issue by chance? Would also be interested in following! If not, would also be happy to open one up (_although need to track down some more info on what exactly to request_)

**Comment by Jrc356** [comment]
Ok so created a new issue since the other one is super stale and doesn't follow their issue format

https://github.com/redpanda-data/redpanda/issues/25138
