### ISSUE TITLE
Question: Is it safe to poll after receiving ErrGroupSession on poll when a broker node restarts in the cluster?

### ISSUE THREAD

**Issue by sbuliarca** [twmb/franz-go#784]
Hi!

We have the following situation, and I would really appreaciate your guidance and knowledge insides on it:
- we're consuming under a consumer group using the PollMaxRecords 
- when a broker restarts, some of the apps that were consuming from that broker, receive in the kgo.Fetches the error: `unable to join group session: unable to dial: dial tcp broker_ip:broker_port: connect: connection refused` which I identified being added [here in the code](https://github.com/twmb/franz-go/blob/master/pkg/kgo/consumer_group.go#L433)

The question is:  is it safe to still use the client and retry the Poll method in this case? Will the client retry to join the group session safely, since it seems it also triggered a metadata refresh from the code? Or do we need to close and recreate the client at this point?

Thank you so much

**Comment by twmb** [comment]
This is safe to recover from, although you may experience duplicate messages -- your group consumer died (potentially after processing some messages, and potentially before committing). The client will eventually rejoin the group.
