### ISSUE TITLE
How to delete offset when message got consumed?

### ISSUE THREAD

**Issue by puneetjindal1997** [twmb/franz-go#791]
Why I want this because there are multiple consumer as well consumer groups so when there will be any consumer group is initialised then it will get all the old messages that already processed I want to delete them using admin client.
 
Case want to achieve :- I want to delete the message from kafka when it get consumed using adminClient

Error :- map[] request key is unknown

Code

```
func consumeMessages(ctx context.Context, client *kgo.Client, adminClient *kadm.Client) {
    for {
        fetches := client.PollFetches(ctx)
        if errs := fetches.Errors(); len(errs) > 0 {
            panic(fmt.Sprint(errs))
        }
        fmt.Println("reached")

        // Iterate through a record iterator...
        iter := fetches.RecordIter()
        for !iter.Done() {
            record := iter.Next()
            fmt.Println(string(record.Value), "from an iterator!")

            partitionMap := map[int32]struct{}{record.Partition: {}}
            topicMap := map[string]map[int32]struct{}{record.Topic: partitionMap}

            // Delete offsets using the admin client.
            dresp, err := adminClient.DeleteOffsets(ctx, "my-group-identifier", topicMap)
            fmt.Println(dresp, err) // here is the error 
        }
    }
} 
```
Help will be appriciated

**Comment by twmb** [comment]
I'm not understanding this -- there may be some confusion here.

* You can not delete _specific_ records.
* You _can_ truncate _to_ an offset such that _nothing_ (no other client ever!) can read up to that offset -- this is the confusingly named `DeleteRecords` API.
* The `DeleteOffsets` API actually deletes any commits for the given topic/partitions. So, when you re-consume with a new consumer or consumer group, the consumer will actually restart consuming at the beginning or at the end, depending on your ConsumeResetOffset

Hope this helps, I think it answers the question.

**Comment by puneetjindal1997** [comment]
understand what I want to achieve is when there will be a new consumer group then it start from where other consumer group offset is. So that's why I want to use this `DeleteOffsets` api but while I'm calling this this gives me error of `map[] request key is unknown`. Please tell me here what I'm missing to pass in the request of what's wrong with this?

**Comment by twmb** [comment]
If you want to start where the other consumer group is, you need to first fetch the other group's offsets, and then commit them to the new group, and then start your consumer.

**Comment by puneetjindal1997** [comment]
Then DeleteOffset and DeleteRecord are same apis?
