### ISSUE TITLE
Want to delete the consumer group after processing records from kafka

### ISSUE THREAD

**Issue by puneetjindal1997** [twmb/franz-go#796]
I have a topic `T1`  and consumer group `test-consumer-group` now there is alot of data in the topic that need to be consumed. In topic I have 20 partitions. What I did is while scaling in the network then there will a new POD will be up when there is huge load. At that time the POD will gen a new consumer group and all the consumers will work accordingly. 

Now I just want to delete the consumer group when the POD goes down. I have done with the implementation but not working as expected. Below is the example code and the error that I'm getting

`Code`
```
for {
		fetches := client.PollFetches(ctx)
		if errs := fetches.Errors(); len(errs) > 0 {
			panic(fmt.Sprint(errs))
		}
		iter := fetches.RecordIter()
		for !iter.Done() {
			record := iter.Next()
                       // Print the fetched record value
			fmt.Println(string(record.Value), "from an iterator!")
                        // delete the record after reading
			resp, err := adminClient.DeleteRecords(ctx, kadm.OffsetsFromFetches(fetches))
			fmt.Println(resp, err)
                        // Delete group request
			respGroup, errGroup := adminClient.DeleteGroup(ctx, "new-consumerGroup-2")
			fmt.Println(respGroup, errGroup)
		}
	}

```

`Error` 
`{new-consumerGroup-2 NON_EMPTY_GROUP: The group is not empty.} NON_EMPTY_GROUP: The group is not empty.`

But the consumer group does not have any lag or any data that it is showing.

**Comment by twmb** [comment]
Consumer groups need to be empty before they can be deleted. All members need to leave -- you can't delete the group there because the consumer group is still active (you just fetched)
