### ISSUE TITLE
Connecting franz-go with a confluent kafka cloud cluster

### ISSUE THREAD

**Issue by sashithaf16** [twmb/franz-go#798]
Hi, just wondering if there is any documentation or help I can get on connecting this package with a cloud cluster managed service provided by confluent. The code I've tried is as follows. What confluent provides is an API key and API secret. The only documentation I could find was on using the code below and I tried with this but it didn't seem to work.
Any advice is greatly appreciated (or verification on if connecting to a cloud instance of kafka is supported by the package), thank you!

`seeds := []string{""} // cluster address provided

// SASL Plain credentials
user := ""
password := ""

opts := []kgo.Opt{
    kgo.SeedBrokers(seeds...),
    // SASL Options
    kgo.SASL(plain.Auth{
        User: user,
        Pass: password,
    }.AsMechanism()),
}
client, err := kgo.NewClient(opts...)`

**Comment by weeco** [comment]
I believe the API key and API secret are supposed to be used as username and password respectively. You are also missing the TLS option, see here: https://github.com/twmb/franz-go/blob/6b61d17383b1e0c766143118efa39f1f320a3b2b/examples/sasl/sasl_ssl_plain/sasl_ssl_plain.go#L38

**Comment by sashithaf16** [comment]
Thanks for the reply! This issue was resolved
