### ISSUE TITLE
Produce batching

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#80]
what you think about batching writing like MarkCommits in case of consumer acking?
Use-case - call Produce/ProduceSync with new option that specifies max timeout or max messages count exceeded - sent to kafka server?
So we effectively can batch multiple messages into single pice and sent to kafka.

**Comment by vtolstov** [comment]
mostly i mean some params like in https://pkg.go.dev/github.com/segmentio/kafka-go#WriterConfig
like BatchTimeout BatchSize, BatchBytes  for writer

**Comment by twmb** [comment]
That sounds like some combination of the following:
```go
func ProducerBatchMaxBytes(v int32) ProducerOpt
func ProducerLinger(linger time.Duration) ProducerOpt
func RecordDeliveryTimeout(timeout time.Duration) ProducerOpt
func RecordRetries(n int) ProducerOpt
```
with potentially ManualFlushing thrown in?

**Comment by vtolstov** [comment]
may be, but in case of manual flushing i need to do all timeout logic and other stuff in my code

**Comment by vtolstov** [comment]
also RecordDeliveryTimeout not suitable - this timeouts batch, but i need to max timeout for filling batch before it can be sent

**Comment by vtolstov** [comment]
also ProducerBatchMaxBytes means that if i add another message that not filled to this size - i get error, but i need to immediately send records to kafka and fill another batch

**Comment by vtolstov** [comment]
so i think that i can't do desired behavior with provided options, what you think ?

**Comment by twmb** [comment]
> max timeout for filling batch
That's what linger does?
> ProducerBatchMaxBytes
You won't get an error if you don't fill, nor if you go over, not sure what you mean?

Also, I'm not sure I fully understand the goal?

**Comment by vtolstov** [comment]
for Lingering i dont understand fully this
```
As mentioned, the linger is specific to topic partition. A high volume producer will likely be producing to many partitions; it is both unnecessary to linger in this case and inefficient because the client will have many timers running (and stopping and restarting) unnecessarily.
```

mostly i want to avoid many timers =))

for ProducerBatchMaxBytes ok, this is suitable for me.

so i need only last component - specify not only max bytes for batch and time to wait, but also message count.

And @twmb if i'm specify ProducerBatchMaxBytes and ProducerLinger and call Produce - for single message few times in 1 second, how much requests will be sent to kafka? (i need to have only one request with all messages that accumulated in batch). Also note that if all messages not filled in single batch, it must be spitted and sent in two batches, but order of delivery is mandatory

**Comment by twmb** [comment]
It's a timer per partition, which strongly encourages using a partitioner that pins to a partition until the batch is full. Still though, even with 10,000 partitions and round robining across all of them, timers are fine.

What is a reason to control message count per batch? There is no option in any client that I'm aware of that bounds the upper count of messages per batch.

Max bytes and linger combine as expected. As many record will be buffered as possible within max bytes, and within linger. There is nothing tricky going on to undo the documented behavior.

Order is guaranteed. All Kafka clients preserve order.

**Comment by twmb** [comment]
I think the above answers the question enough, let me know if not!
