### ISSUE TITLE
`GetConsumeTopics` returns all topics when consuming via regex, not just the topics that are being consumed

### ISSUE THREAD

**Issue by twmb** [twmb/franz-go#810]

**Comment by twmb** [comment]
Also maybe GetConsumeTopics does not return topics until after consuming has happened? This makes sense for regex but not for non-regex.

**Comment by mihaitodor** [comment]
When you say "consuming has happened", do you mean reading messages? It would be convenient to be able to just enumerate the matched topics up front when using `kgo.ConsumeRegex()`, but not sure if the protocol allows it.
