### ISSUE TITLE
Change error string for sr.ResponseError

### ISSUE THREAD

**Issue by weeco** [twmb/franz-go#819]
I'd like to suggest a minor change on how errors on sr.ResponseError should be stringified. In case the schema registry responds with an empty body we would not see any error string at all because we have neither `e.Message` nor `e.Raw` set. 

In that case we should could instead return the errorcode + a notice indicating that the body was empty.  Similarly we could do it if the body is too large (e.g. some HTML response from a reverse proxy).

https://github.com/twmb/franz-go/blob/b77dd13e2bfaee7f5181df27b40ee4a4f6a73b09/pkg/sr/client.go#L44-L49

**Comment by twmb** [comment]
+1, want to PR it?
