### ISSUE TITLE
how to get assignments without actual reading?

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#82]
does it possible to connect to kafka via consumer group, get assignments but start for each partition dedicated reader and process messages from it?
as i saw sometimes fetch get only 1-2 partition messages, so i don't fully utilize cpu cores because i can't pull another fetch as it can contains messages from the same (1-2) partitions and not other.
So i need equal distribution of records in fetch with all assigned partitions or some other mechanism to get better parallelism.
(in segmentio i can start reader for in kafka generation and read all partitions from kafka in parallel)
how to do that in you package?

**Comment by vtolstov** [comment]
I need to have method that get info about assignments in current kafka generation, so i can start reading of partitions before this generation ends and kafka sends rebalance.
Can you do that?

**Comment by vtolstov** [comment]
this is last part to get equal or bigger speed vs segmentio package

**Comment by twmb** [comment]
What does the segment code look like? It sounds like in the segment version, you're opening a new conn reader per partition. This allows you to process each partition purely concurrently, and may appear faster than the franz-go client if you are blocking per poll with this client. I'm guessing this is also prone to bugs.

I'm fairly sure that if you had `PollFetches` be a non-blocking loop that just sent all fetches received all of the time to a separate goroutine that did the processing, you'll see that this client is faster in all cases than the segment client. I recommend comparing the throughput of your program to my own [bench](https://github.com/twmb/franz-go/blob/master/examples/bench/main.go#L216-L227) program that does nothing but count the messages received and immediately goes to poll again. If you're unable to replicate the throughput, then any delay is application side.

I'm not sure what you mean by the processing containing messages for the same partitions. The client bumps the iteration start index every time it fetches.

Reading individual partitions yourself manually sounds prone to problems around rebalances or error handling. It sounds like a footgun to introduce any API that makes this easier. I'm not even sure what an API would look like where you'd be a group consumer but not actually consume with the group, instead consuming manually and bumping offsets yourself.

**Comment by vtolstov** [comment]
segmentio
https://pkg.go.dev/github.com/segmentio/kafka-go#ConsumerGroup.Next
https://pkg.go.dev/github.com/segmentio/kafka-go#Generation.Start
https://pkg.go.dev/github.com/segmentio/kafka-go#Generation.CommitOffsets

so with this functions i can start any goroutine with parent context, so i can create reader for partition and stop reading when parent context done and group is closed or rebalance happened

**Comment by vtolstov** [comment]
can you say me - if i don't commit offset for some messages that read (for example error on handling) on do next PollFetches - kafka returns not acked messages or not? or only when clients reconnects to consumer group?

**Comment by twmb** [comment]
Not sure what you mean by returning only acked messages or not. Acking is a producer side concern.

The group "generation" can be hooked into with OnAssigned / OnRevoked. You have to commit within these bounds. You can commit across generations, but this may lead to duplicates.

Are you using a segment Reader or segment Conn to read messages? Either way, reading _per partition_ is not really an efficient concept when talking to Kafka: within a single fetch request, a client asks for many partitions. 

I'm fairly certain that the problem lies in not divorcing your partition consuming from your polling. This is an example of what splitting the two would look like:
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"sync/atomic"
	"time"

	"github.com/twmb/franz-go/pkg/kgo"
)

var (
	topic = flag.String("t", "", "topic to consume")
	group = flag.String("g", "", "group to consume in")
)

var (
	globalRecs  int64
	globalBytes int64
)

type pconsumer struct {
	quit chan struct{}
	recs chan []*kgo.Record
}

func (pc *pconsumer) consume(topic string, partition int32) {
	fmt.Printf("starting, t %s p %d\n", topic, partition)
	defer fmt.Printf("killing, t %s p %d\n", topic, partition)
	var (
		nrecs  int
		nbytes int
		ticker = time.NewTicker(time.Second)
	)
	defer ticker.Stop()
	for {
		select {
		case <-pc.quit:
			return
		case recs := <-pc.recs:
			nrecs += len(recs)
			atomic.AddInt64(&globalRecs, int64(len(recs)))
			for _, rec := range recs {
				nbytes += len(rec.Value)
				atomic.AddInt64(&globalBytes, int64(len(rec.Value)))
			}

		case t := <-ticker.C:
			fmt.Printf("[%s] t %s p %d consumed %0.2f MiB/s, %0.2fk records/s\n",
				t.Format("15:04:05.999"),
				topic,
				partition,
				float64(nbytes)/(1024*1024),
				float64(nrecs)/1000,
			)
			nrecs, nbytes = 0, 0
		}
	}
}

type splitConsume struct {
	consumers map[string]map[int32]pconsumer
}

func (s *splitConsume) assigned(_ context.Context, cl *kgo.Client, assigned map[string][]int32) {
	for topic, partitions := range assigned {
		if s.consumers[topic] == nil {
			s.consumers[topic] = make(map[int32]pconsumer)
		}
		for _, partition := range partitions {
			pc := pconsumer{
				quit: make(chan struct{}),
				recs: make(chan []*kgo.Record, 10),
			}
			s.consumers[topic][partition] = pc
			go pc.consume(topic, partition)
		}
	}
}

func (s *splitConsume) lost(_ context.Context, cl *kgo.Client, lost map[string][]int32) {
	for topic, partitions := range lost {
		ptopics := s.consumers[topic]
		for _, partition := range partitions {
			pc := ptopics[partition]
			delete(ptopics, partition)
			if len(ptopics) == 0 {
				delete(s.consumers, topic)
			}
			close(pc.quit)
		}
	}
}

func main() {
	flag.Parse()

	go func() {
		for t := range time.Tick(time.Second) {
			fmt.Printf("[%s] globally consumed %0.2f MiB/s, %0.2fk records/s\n",
				t.Format("15:04:05.999"),
				float64(atomic.SwapInt64(&globalBytes, 0))/(1024*1024),
				float64(atomic.SwapInt64(&globalRecs, 0))/1000,
			)
		}
	}()

	s := &splitConsume{
		consumers: make(map[string]map[int32]pconsumer),
	}

	opts := []kgo.Opt{
		kgo.ConsumerGroup(*group),
		kgo.ConsumeTopics(*topic),
		kgo.OnPartitionsAssigned(s.assigned),
		kgo.OnPartitionsRevoked(s.lost),
		kgo.OnPartitionsLost(s.lost),
	}

	cl, err := kgo.NewClient(opts...)
	if err != nil {
		panic(err)
	}

	s.poll(cl)
}

func (s *splitConsume) poll(cl *kgo.Client) {
	for {
		fetches := cl.PollFetches(context.Background())
		if fetches.IsClientClosed() {
			return
		}
		fetches.EachError(func(_ string, _ int32, err error) {
			panic(err)
		})
		fetches.EachTopic(func(t kgo.FetchTopic) {
			tconsumers := s.consumers[t.Topic]
			if tconsumers == nil {
				return
			}
			t.EachPartition(func(p kgo.FetchPartition) {
				pc, ok := tconsumers[p.Partition]
				if !ok {
					return
				}
				select {
				case pc.recs <- p.Records:
				case <-pc.quit:
				}
			})
		})
	}
}
```

**Comment by vtolstov** [comment]
thanks for you example, for goroutine per partition will be faster if you workload contains database queries and other stuff =)

**Comment by twmb** [comment]
I'm going to turn the above into an example in the codebase, but for the purposes of this ticket, I think it's closed, please let me know if not, thanks!

**Comment by twmb** [comment]
https://github.com/twmb/franz-go/tree/master/examples/goroutine_per_partition_consuming

**Comment by vtolstov** [comment]
yeah , big thanks
