### ISSUE TITLE
Apparently invalid "connection refused" errors on Redpanda Cloud connection

### ISSUE THREAD

**Issue by genzgd** [twmb/franz-go#822]
We had several customer outages today where fetches and commits failed to Redpanda Cloud proxy servers due to "connection refused" errors.  Restarting the consumers seem to fix the problem.  Sample logs:

We don't have actual console logs, but this is the "error loop" we captured using our observability platform:

```
unable to open connection to broker 
  err:dial tcp 3.237.62.125:9092: connect: connection refused
injecting fake fetch with an error
  err: unable to join group session: unable to dial: dial tcp 3.237.62.125:9092: connect: connection refused
  why: notification of group management loop error
assigning partitions
  why: clearing assignment at end of group management session
join and sync loop errored:
  consecutive_errors: 24
  err: unable to dial: dial tcp 3.237.62.125:9092: connect: connection refused
  group:  <consumer group name>
```

This repeated for approximately an hour before we restarted the application.   We don't have enough data to know if the DNS entries for the RedPanda cloud proxy servers changed, but a couple of hours after the failures the addresses involved all seemed to be accepting connections on port 9092.  Is it somehow possible that the client was using "stale" connections or otherwise wasn't actually trying to connect on the Redpanda ports after the initial attempt?  Or could it be some weird AWS networking issue (our applications and Redpanda Cloud both are running in AWS).

**Comment by genzgd** [comment]
A possibly related oddity, when working on a integration test around this problem, we seem to get stuck in a permanent loop when attempting to update metadata:

```
2024-09-17 18:10:33.918 WRN unable to open connection to broker addr=localhost:19092 broker=seed_0 err="dial tcp [::1]:19092: connect: connection refused" 
2024-09-17 18:10:34.173 INF metadata update triggered  why="re-updating metadata due to err: unable to dial: dial tcp [::1]:19092: connect: connection refused"
2024-09-17 18:10:34.174 WRN unable to open connection to broker addr=localhost:19092 broker=seed_0 err="dial tcp [::1]:19092: connect: connection refused" 
2024-09-17 18:10:34.644 INF metadata update triggered why="re-updating metadata due to err: unable to dial: dial tcp [::1]:19092: connect: connection refused"
2024-09-17 18:10:34.645 WRN unable to open connection to broker addr=localhost:19092 broker=seed_0 err="dial tcp [::1]:19092: connect: connection refused" 
2024-09-17 18:10:35.752 INF metadata update triggered why="re-updating metadata due to err: unable to dial: dial tcp [::1]:19092: connect: connection refused"
2024-09-17 18:10:35.753 WRN unable to open connection to broker addr=localhost:19092 broker=seed_0 err="dial tcp [::1]:19092: connect: connection refused" 
```

In this case the `connection refused` error is valid, but the client `PollRecords` call never returned (with or without an error).  This seems like similar behavior to #816

**Comment by twmb** [comment]
What I can say is that nothing within the client caches addresses / DNS / anything. The client internally uses the standard net.Dialer or tls.Dialer.

For the latter point, metadata requests that outright fail to be issued are not bubbled up to you via polling right now. I'm not sure it _should_ be. The point of KeepRetryableFetchErrors is to all you to see errors encountered while fetching. There are  many errors handled internally throughout the client, which should be returned to you and which shouldn't be? Why return a metadata load error on the consuming path when there is no way to discover this same error while producing?

For the metadata error here, I _think_ it is discoverable with a BrokerE2E hook.

**Comment by genzgd** [comment]
I figured something address cached in the client was a long shot, but as you might imagine, we're looking for any explanation for this behavior.

I totally understand retrying certain errors in the client without the returning them to the Poll call every time.  I'm mostly looking for a way to distinguish "there's no new data on the topic" vs "we can't even connect to the broker" so we can alert/monitor/otherwise take action on latter situation.  Using a hook seems kind of clunky, although I'll take a look at that possibility.  Is there some best practice in using the client I'm missing that will let us know when things are broken at that level?

**Comment by twmb** [comment]
Hooks generally -- have you taken a look at any drop in hook implementations in the `plugin` subdirectory?

https://github.com/twmb/franz-go/blob/master/plugin/kprom/kprom.go -- for example, for prometheus.

I think hooks feel a bit clunky at first blush, but it's a way to ensure the client stays platform agnostic and allows people to pretty extensively customize what exactly they want to happen in many cases.

**Comment by genzgd** [comment]
I'm good with that.  I'll take a look at capturing `connection refused` and similar errors with a hook then.
