### ISSUE TITLE
Request Errors metric support

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#830]
I'm trying to implement support for a metric counting errors coming from kafka. kgo's metric hooks would let me count broker connect errors and network bytes read & write errors. However, I don't see a way to get a count of all errors occurring.

My motivation is I would like to be able to answer the question "is the kafka cluster I'm trying to produce to struggling/misconfigured/generally not behaving?" - and I don't believe that the currently exposed errors would do that justice. Am I correct in this thinking?

Proposal: maybe add another hook exposing RequestErrors, and call it [here](https://github.com/twmb/franz-go/blob/master/pkg/kgo/client.go#L1211)

**Comment by twmb** [comment]
To confirm: you'd like a way to inspect the `ErrorCode` field _within_ all responses?

**Comment by asg0451** [comment]
That would be great, yeah

**Comment by twmb** [comment]
What would this API look like? One option is to just give you the raw message, but then _you_ would need to know where the error fields are, _and_ sometimes error fields change locations as the API evolves in Kafka. As well, some messages have multiple error fields in different locations.

**Comment by asg0451** [comment]
I didn't know that, that's annoying. Glad you handle that complexity for us. If you provide a hook that only gets called on failed messages, that would fit this use case even though it's an inelegant solution. Here I just care about diagnosing whether poor conditions upstream of this are caused by instability in the kafka cluster.

**Comment by twmb** [comment]
Do you have a proposal for the hook? With failed messages, I'd think you could use the existing promise `error` field in the callback, so I'm not sure what a request here could be.

**Comment by twmb** [comment]
Closing for now -- willing to reopen with a proposal

**Comment by asg0451** [comment]
Thanks @twmb, I'll reopen with a proposal when I have one.

**Comment by StarpTech** [comment]
Hi, we're also interested in this capability. We want to track write / read errors with the generic hook approach. In addition to that, we would like to know the affected topic.

Right now, `OnBrokerWrite` error parameter is nil even when the record could not be written e.g. `UNKNOWN_TOPIC_OR_PARTITION: This server does not host this topic-partition.`

**Comment by StarpTech** [comment]
Should I open an issue for this @twmb ?

**Comment by twmb** [comment]
With proposal, perhaps yes
