### ISSUE TITLE
ping method analog

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#85]
database/sql has ping method to understand that driver connected to database instance
does it possible to force connect Client to broker and get some results ? Mostly for me this is needed to check that broker address properly set and broker available.

**Comment by twmb** [comment]
Issue an ApiVersions request. Pinging goes against the client internally _not_ connecting unless necessary.

**Comment by vtolstov** [comment]
thanks

**Comment by twmb** [comment]
As an example: https://github.com/cloudhut/kowl/blob/24b84448e87cb8fc8d16eebf405a0d1b694d27ff/backend/pkg/kafka/service.go#L132-L165

**Comment by vtolstov** [comment]
Wow, nice. Thank you

**Comment by twmb** [comment]
I'm thinking to add this, after a few more requests.

**Comment by weeco** [comment]
What would the ping method do? Just an ApiVersions request (which would also be valid without authentication) or also a metadata request for instance? Would that be part of the admin client or what's the idea?

**Comment by twmb** [comment]
I'm thinking:
```go
// Ping returns whether any broker is reachable, iterating over any discovered broker
// or seed broker until one returns a successful response to an ApiVersions request.
// Each request is retried up to 3 times depending on the how the request fails.
// If all requests fail, this returns final error.
func (cl *Client) Ping() error

type PingBrokerError struct {
        Broker BrokerMetadata
        Err    error
}
type PingBrokerErrors []PingBrokerError


// Any returns the first error, if any.
func (es PingBrokerErrors) Any() error

// PingAll iterates through all discovered brokers and issues an ApiVersions request
// to each to test broker connectivity. If there are currently no discovered brokers,
// this iterates through all seed brokers.
func (cl *Client) PingAll() PingBrokerErrors
```

I'm not yet settled on the API for `PingAll`: should always iterate over both seeds and non-seeds?

**Comment by vtolstov** [comment]
I'm prefer to have Ping(context.Context) error method.
So i can set deadline on context

**Comment by twmb** [comment]
I've added `Ping(context.Context) error`, good suggestion about deadlining. This has now been tagged in v1.3.0.
