### ISSUE TITLE
PauseFetchTopics/ResumeFetchTopics fetches old messages

### ISSUE THREAD

**Issue by hugosjoberg** [twmb/franz-go#853]
Hi,

I'm trying to temporarily pause the consuming from a topic, and then resume the consumption. Messages which are produced when the consumption is paused I would like to drop and then I resume the consumption I would like to only consume new messages.

I currently have the following options:
```
opts := []kgo.Opt{
	kgo.ConsumerGroup(cfg.ConsumerGroup()),
	kgo.ConsumeTopics(cfg.Kafka.Topics...),
	kgo.ConsumeResetOffset(kgo.NewOffset().AtEnd()), // Consume from latest
}
```

Currently if I produce two messages:
```
topics := []string{"mock-topic"}
cluster, err := kfake.NewCluster(
	kfake.Ports(19092, 19093, 19094),
	kfake.SeedTopics(-1, topics...),
)
...
c.PauseFetchTopics(topics...) // pause all clients
clients.clients[0].ProduceSync(context.TODO(), &kgo.Record{
	Value:     []byte("first message"),
	Topic:     cfg.Kafka.Topics[0],
	Timestamp: time.Now().Add(1 * time.Minute),
})
time.Sleep(1 * time.Second)
c.ResumeFetchTopics(topics...) // resume all clients

clients.clients[0].ProduceSync(context.TODO(), &kgo.Record{
	Value:     []byte("second message"),
	Topic:     cfg.Kafka.Topics[0],
	Timestamp: time.Now(),
})
```
I fetch two messages when I fetch the messages, but I only expected to pull one message.

Appreciate your help :)

**Comment by twmb** [comment]
Pausing does not skip messages, it pauses where you're at and then resumes from that same location.

If you want to skip all messages while pausing, why not close the client and then recreate the client? How long do you expect to pause for? Another two options are to:
* Don't pause; continue consuming but just discard the messages you read (this still consumes network traffic, though)
* Pause, and then use SetOffsets to set to the end of the partition once resuming (I think you can use EpochOffset{-1, -1}

**Comment by hugosjoberg** [comment]
Thank you for your reply.

I don't want to close the client, in reality I just want to stop consuming from one of the topics to reduce network traffic during certain circumstances. I'll try out to set-offsets when I resume.

Thank you!

**Comment by hugosjoberg** [comment]
Alright, is this what you had in mind?

```golang
c.ResumeFetchTopics(topics...)
offsets := c.CommittedOffsets()
for topic, partition := range offsets {
	for i := range partition {
		offsets[topic][i] = kgo.EpochOffset{Epoch: -1, Offset: -1}
	}
}
c.SetOffsets(offsets)
```

I this what you had in mind?
