### ISSUE TITLE
Buffering unknown topics

### ISSUE THREAD

**Issue by yomikaze** [twmb/franz-go#86]
By default, producing records to an unknown topic will indefinitely append to the client's "unknown topic buffer" without any feedback or a way to flush the buffered records outside of closing the client. 

I see the unknown topic buffer has a capacity of 100 (https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L678), but it does not get respected by appends (https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L683). Therefore, it looks like the unknown topic buffer will grow indefinitely in size.

With auto topic creation not enabled and no timeouts configured, `client.ProduceSync` on an unknown record will hang indefinitely and the callback function for`client.Produce` will not be called. I understand that this would not be an issue with `AllowAutoTopicCreation` enabled, but we do not wish to enable auto topic creation. My workaround at the moment is simply to set a client timeout through `RecordDeliveryTimeout`, but the growing buffer issue still exists especially during high throughput.

It would be useful if there were an error specifically for records written to unknown topics when auto topic creation is not enabled. Alternatively, it would be nice if [errRecordTimeout](https://github.com/twmb/franz-go/blob/master/pkg/kgo/errors.go#L132) were exposed so I can easily and cleanly determine if an error from `client.ProduceSync` or `client.Produce` is a timeout error and therefore potentially an "unknown topic" error. Perhaps a ProductOpt config such as `OnRecordDeliveryTimeout` could be helpful as well.

**Comment by twmb** [comment]
Good note! Per our discussion on slack, I've decided to change producing to unknown topics to failing after 5 load failures. This should cover the problem you're running into.

I've also gone ahead and exported `ErrRecordTimeout` and `ErrRecordRetries`.

Thanks for the report, this is a good idea. I've tagged v1.1.0 with this new behavior, which closes this issue. Please let me know if you have more good ideas, thank you!
