### ISSUE TITLE
ability to get internal state via some event interface

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#861]
Hi, we using this beautiful kafka package in production. But when something happens in kafkaesque server (node down, network lost and so) we dont know from application POV about this.

To get ability to handle such issues we need to have some Event (also when autocommit processed records failed).
Can you add some helpers to do that?

**Comment by weeco** [comment]
Have you looked at the hooks funcs? https://github.com/twmb/franz-go/blob/master/pkg/kgo/hooks.go

These allow you to observe quite a lot of what's going on already. Is there something missing you want to observe?

**Comment by twmb** [comment]
Please let me know if the hooks do not provide the needed insight -- if not, propose a hook that would

**Comment by vtolstov** [comment]
i'm review hooks and have some questions:
1) if default commit failed - this is not exposed via hook, so my service does not know about that, but this is very urgent flag - if commit failed my service must fail k8 probe
2) we have connects and disconnects, how to deal with it? How understand what we need to do?
3) when kafkaesque server under high load or node with service under high load i have errors like "unable to open connection to broker" if i have one of such message may be this is not fatal, but i have service that have such error 24 hours... on which hook/metrics i can understand that service must be stopped?

**Comment by vtolstov** [comment]
also note 
```
func (g *groupConsumer) defaultCommitCallback(_ *Client, _ *kmsg.OffsetCommitRequest, resp *kmsg.OffsetCommitResponse, err error) {
	if err != nil {
		if !errors.Is(err, context.Canceled) {
			g.cfg.logger.Log(LogLevelError, "default commit failed", "group", g.cfg.group, "err", err)
		} else {
			g.cfg.logger.Log(LogLevelDebug, "default commit canceled", "group", g.cfg.group)
		}
		return
	}
	for _, topic := range resp.Topics {
		for _, partition := range topic.Partitions {
			if err := kerr.ErrorForCode(partition.ErrorCode); err != nil {
				g.cfg.logger.Log(LogLevelError, "in default commit: unable to commit offsets for topic partition",
					"group", g.cfg.group,
					"topic", topic.Topic,
					"partition", partition.Partition,
					"error", err)
			}
		}
	}
}

```

can you fix error field consistent with all code to have "error" field in logs, not err/error ?

**Comment by vtolstov** [comment]
on metadata update
```
	g.cfg.logger.Log(LogLevelError, "join and sync loop errored",
			"group", g.cfg.group,
			"err", err,
			"consecutive_errors", consecutiveErrors,
			"backoff", backoff,
		)
```

no hooks called on error, but if service cant get metadata updates i need to restart it or something else

**Comment by vtolstov** [comment]
```
	g.cfg.logger.Log(LogLevelDebug, "heartbeat complete", "group", g.cfg.group, "err", err)
			if force != nil {
				force(err)
			}
			```
on heartbeat error also no hooks called

**Comment by vtolstov** [comment]
@twmb may be we need to reopen this issue ?

**Comment by vtolstov** [comment]
@twmb ?

**Comment by twmb** [comment]
> if default commit failed

The default commit is very primitive; it's the fallback used if no commit callback is provided by you. If you want more information, you should override the default commit. All it does is [log errors](https://github.com/twmb/franz-go/blob/d8562fe83ca0b101174c5206a2960bdb003e5add/pkg/kgo/consumer_group.go#L2131-L2150).

> we have connects and disconnects

OnBrokerConnect && OnBrokerDisconnect.  You can stuff any logic in there, example: https://github.com/twmb/franz-go/blob/master/plugin/kvictoria/kvictoria.go#L150-L176. It's informational; the client retries. It's probably worth inspecting errors and having some logic around what should be done -- e.g. reload a cert if necessary.

> unable to open connection to broker

OnBrokerDisconnect -- I don't know what application side service you want to hook into; the library is just telling you there's a problem.

> can you fix error field consistent with all code to have "error" field in logs, not err/error ?

```
[21:40:37]
@m4x3r:~/src/twmb/franz-go/pkg/kgo
$ rg '"err"' | wc -l
      48

[21:40:42]
@m4x3r:~/src/twmb/franz-go/pkg/kgo
$ rg '"error"' | wc -l
       1
```
I'm going to change `error` to `err` actually to be consistent -- error is probably better, but it's a smaller change to go to err for now 😅 

> https://github.com/twmb/franz-go/issues/861#issuecomment-2558268952

Above, https://github.com/twmb/franz-go/blob/d8562fe83ca0b101174c5206a2960bdb003e5add/pkg/kgo/consumer_group.go#L417

OnGroupManageError: https://github.com/twmb/franz-go/pull/387

> on heartbeat error also no hooks called

The heartbeat error is what is eventually passed to OnGroupManageError. You don't really need to know _every_ heartbeat error result.

**Comment by vtolstov** [comment]
Thank you for detailed answer, so what you recommend to use to know when the service can’t operate normally after Kafka servers issues?
My use case - know when the producer can’t produce and know when the subscriber can’t operate - lost group and don’t get any partitions and can’t commit offsets

**Comment by twmb** [comment]
> so what you recommend to use to know when the service can’t operate normally after Kafka servers issues

I'd use a combination of metrics & logs. I don't know what errors you're running into / could run into, but I think the client gives you most or all information it can so that you can instrument your application / monitoring stack.
