### ISSUE TITLE
Panic in takeNBuffered

### ISSUE THREAD

**Issue by serge-v** [twmb/franz-go#87]
Sometimes pCursor is nil and it crashes on this line:
https://github.com/twmb/franz-go/blob/631cabec1251bdec6b95977deab38cee9648f75b/pkg/kgo/source.go#L383

**Comment by twmb** [comment]
I'll look into this immediately, thanks.

**Comment by twmb** [comment]
@serge-v how often, and are you reliably able to trigger this? Wondering if I could create a reproducer on my side.

**Comment by twmb** [comment]
I have an idea as to what this could be. Are you using closest replica fetching? Alternatively, when this panic happens, is there cluster instability that causes some partitions to move between brokers / have their leader epoch's bumped?

**Comment by serge-v** [comment]
my case is: t.Partitions has 10 partitions, but only one item in tCursors.
> === cursors: map[46:0xc0000a8680]
=== partition: 0 {Partition:28 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 1 {Partition:58 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 2 {Partition:64 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 3 {Partition:94 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 4 {Partition:4 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 5 {Partition:16 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 6 {Partition:40 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 7 {Partition:46 Err:<nil> HighWatermark:1767802 LastStableOffset:1767802 LogStartOffset:1767798 Records:[0xc000280480]}
=== partition: 8 {Partition:70 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 9 {Partition:76 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 10 {Partition:88 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 11 {Partition:10 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}
=== partition: 12 {Partition:34 Err:<nil> HighWatermark:-1 LastStableOffset:-1 LogStartOffset:-1 Records:[]}

**Comment by twmb** [comment]
@serge-v if possible, can you confirm https://github.com/twmb/franz-go/commit/847aeb918ebc35a059cb2977424f16272c4e81bd fixes it? I plan to tag with v1.1.1 soon regardless, but having some confirmation here would be great.

**Comment by serge-v** [comment]
Works good now. No panic. Thank you.

**Comment by twmb** [comment]
Thanks! I've tagged this as v1.1.1.
