### ISSUE TITLE
Is there a plan to implement KIP-890 ?

### ISSUE THREAD

**Issue by cupcicm** [twmb/franz-go#873]
Hello,

[KIP-890](https://cwiki.apache.org/confluence/display/KAFKA/KIP-890:+Transactions+Server-Side+Defense) will see the brokers respond in the `EndTxnResponse` with two extra fields: `ProducerID` and `ProducerEpoch` and will expect the clients to locally bump the `ProducerID` and `ProducerEpoch` of the transactional producer to what the server has sent back. 

I would like to know if there is a plan to implement this in franz-go ? It is going to be released in Apache Kafka 4.0

I could also help in implementing this feature if I was given enough pointers to know exactly what is needed.

**Comment by twmb** [comment]
This is noted as partially supported in the README. Kafka itself doesn't support KIP-890 fully -- notably, EndTxn does not yet return the pid nor epoch as of Kafka 3.8.

**Comment by twmb** [comment]
(Closing as "done as much as possible at the moment", and I'll add support when it's added to Kafka)
