### ISSUE TITLE
Option to persist produce records to disk

### ISSUE THREAD

**Issue by chrjen** [twmb/franz-go#88]
I can't find any options for re-transmission of records after a program restart. Nor any good ways to implement this myself.

I have a device that may occasionally lose internet so I need to persist records to disk to both save on memory usage, but also guard against crashes, loss of power or a device restart. Then re-transmit when internet comes back.

One possible solution I have tried is to use `context.WithTimeout` with `client.Produce` to try to detect when the client has lost connection to the kafka cluster and then persisting the record. However I have no idea if the client has been able to reconnect other than re-transmitting the message immediately.

**Comment by twmb** [comment]
I think an option to persist records to disk doesn't quite belong in the client (very niche use), but: is it possible to use `RecordDeliveryTimeout`? 

The client lazily connects, so it will only try to connect for producing if there are records to be produced. I'm not sure of another to force this _without_ re-transmitting immediately.

I think one algorithm would be to set a `RecordDeliveryTimeout`, and then if any record fails with `ErrTimeout`, start buffering everything to disk, and try to only send one record. And then, repeatedly send that one record until it is successful, and when it finally is, unbuffer from disk and send everything else.

What do you think?

**Comment by chrjen** [comment]
I see, but yeah I think your idea could work. Definitely some edge cases though. I will give it a try, and if doesn't actually work then I might reopen this issue. :)

**Comment by chrjen** [comment]
It works. I found this nice library that implements a queue back by a disk, https://github.com/joncrlsn/dque. So I just queue any records that fails, then start dequeue messages as soon as a record successfully gets published.

**Comment by twmb** [comment]
Awesome, happy you were able to get it to work out!
