### ISSUE TITLE
ReadOnly config keys

### ISSUE THREAD

**Issue by peter-evans** [twmb/franz-go#91]
Hi 👋 

Thanks as always for this great library.

I've run into a bit of an issue with the following two config keys.
```
leader.replication.throttled.rate
follower.replication.throttled.rate
```
I'm adding them to all brokers in a cluster using the `AlterConfigsRequest` and not specifying `ResourceName` so it updates the cluster-wide dynamic config. Then if I do a `DescribeConfigsRequest` for the cluster-wide dynamic config I'm seeing the above two config keys have been added, but they are marked as `ReadOnly = true`. These are dynamic keys which can definitely be altered at any time, so I'm not sure why they are marked as read-only. I've successfully altered/deleted these keys multiple times using this library's APIs. I was hoping to use the `ReadOnly` flag to filter out actual read-only config, but it filters out these dynamic config keys that I care about.

Is the read-only status of a key coming from the Kafka cluster itself, or is that something this library has configuration for?

**Comment by twmb** [comment]
The `ReadOnly` field is set by the cluster itself, but it is odd that this isn't showing dynamic. What does the `ConfigSource` field say?

**Comment by peter-evans** [comment]
`ConfigSource` is 3 (`ConfigSourceDynamicDefaultBrokerConfig`)

**Comment by twmb** [comment]
I remember when I added this that some values can only be set on a per-resource basis. It is possible that in this case, `ResourceName` would need to be specified. I'm not 100% sure on the semantics of when or why Kafka requires this.

Looking at Kafka's source, when describing configs, if the resource name is empty when describing, then it returns dynamic default broker config.

What happens when you describe the broker directly (if you're using kcl, `kcl admin configs describe -tb 1` or so). Does it show the config value as non-dynamic in that case? If so, then it may be that the config is read only when describing the cluster, but is actually dynamic. If not, then it may be that the config needs to be set on a per-broker basis.

Config describing isn't too obvious because I think it quickly gets into zookeeper code behind the scenes. Let me know what the above shows and if things aren't working out, I could maybe try to dig in a bit more?

**Comment by peter-evans** [comment]
I just tried adding/describing in exactly the same way (cluster-wide) with a different dynamic key, `background.threads`. That one works fine.

Here's a bit of debug output:
```
leader.replication.throttled.rate is readonly=true, source=3
follower.replication.throttled.rate is readonly=true, source=3
background.threads is readonly=false, source=3
```

I also tried what you suggested, querying the broker directly, and it still returns `readonly=true, source=3`.

Perhaps the `*.throttled.rate` keys are special in some way because I noticed that they aren't listed under [Broker Configs](https://kafka.apache.org/documentation/#brokerconfigs) in the documentation. Instead, they appear in a separate section about [limiting bandwidth](https://kafka.apache.org/documentation/#rep-throttle). So it may be a bug with those keys due to them being treated in some special way.

**Comment by twmb** [comment]
Well, these keys certainly are special, but checking the source, they're especially dynamic: https://github.com/apache/kafka/blob/361b7845c6e6badc4be19fec596380a3de7a5c98/core/src/main/scala/kafka/server/DynamicConfig.scala#L31-L40

It looks like the truly "dynamic" configs are their own static set: https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/DynamicBrokerConfig.scala#L80-L86

And when describing, if the config being described is _not_ in that set, it is ReadOnly: https://github.com/apache/kafka/blob/0888953e0e834bf849751a36ae5adf92b20ec0a5/core/src/main/scala/kafka/server/ConfigHelper.scala#L158

Not sure why that is. The keys your setting aren't in that set, so they're being returned as read only.

The KIP itself, although old, mentions "brokers don't have any dynamic configs currently": https://cwiki.apache.org/confluence/display/KAFKA/KIP-133%3A+Describe+and+Alter+Configs+Admin+APIs. However it also mentions that altering a read only config returns an error, and you didn't experience that.

AFAICT the logic around ReadOnly looks pretty questionable, and the ConfigSource field may be a better bet to determine whether something is dynamic.

**Comment by peter-evans** [comment]
Good find! So [these three config keys](https://github.com/apache/kafka/blob/361b7845c6e6badc4be19fec596380a3de7a5c98/core/src/main/scala/kafka/server/DynamicConfig.scala#L39-L41) are especially dynamic because they "have no physical manifestation in the server.properties and can only be set dynamically."

> the ConfigSource field may be a better bet to determine whether something is dynamic

Ah, yes. That does seem like the best way to proceed. I'll try that for the solution.

Thanks for your quick response!

**Comment by peter-evans** [comment]
Turns out that just using ConfigSource isn't good enough. Take these two keys as an example:

```
controller.socket.timeout.ms is readonly=true, source 5
min.insync.replicas is readonly=false, source 5
```
Both are defaults (`ConfigSourceDefaultConfig`), but a dynamic key overriding the default can only be created for `min.insync.replicas`.

To solve the problem I added a new "super-dynamic" category and just made an exception for [these three config keys](https://github.com/apache/kafka/blob/361b7845c6e6badc4be19fec596380a3de7a5c98/core/src/main/scala/kafka/server/DynamicConfig.scala#L39-L41). It seems to work ok. 🤞

**Comment by peter-evans** [comment]
With fresh eyes the next day I did figure out a way to use the `ConfigSource` to filter out readonly (non-dynamic) keys, without resorting to a list of exceptions. 👍 

Just something I wanted to add that I noticed. In addition to [these three](https://github.com/apache/kafka/blob/361b7845c6e6badc4be19fec596380a3de7a5c98/core/src/main/scala/kafka/server/DynamicConfig.scala#L39-L41) "super-dynamic" keys, there are other keys which behave the same way. There are a number of broker keys that require the `listener.name.{listenerName}.` prefix when altering configs. The resulting key is "super-dynamic," i.e. is readonly=true, but source=`ConfigSourceDynamicBrokerConfig`.

**Comment by twmb** [comment]
After reading that comment three times now, I think I still am not making sense of exactly why Kafka is operating that way... heh. Glad you figured it out though :)

If I knew what to translate into docs, I would, but I'm not sure I do.

**Comment by peter-evans** [comment]
I don't really understand why Kafka behaves this way either, but not trusting the `ReadOnly` property seems to be the best way to handle it. I think if you wanted to add something to the docs you could say that the `ReadOnly` property returned by Kafka is not always correct. I've not investigated further, but my suspicion is that it was an oversight that some of these dynamic keys aren't set to `ReadOnly=false`, and perhaps it's not easy to fix now.

**Comment by twmb** [comment]
Awesome, easy enough to mention that and this issue, I've gone ahead and done that in https://github.com/twmb/franz-go/commit/16677574439f08b19530e5dc346d0dba0fbc3616.

**Comment by peter-evans** [comment]
Thanks again for this great library and for answering a number of my questions late last year. I had a lot of fun working on my project using franz-go. Just made it public and thought you might be interested.

https://github.com/peter-evans/kdef

**Comment by twmb** [comment]
Some of the option handling there looks a bit familiar ;)

Very cool though! Happy to see another OS project using this one!
